### ISSUE TITLE
[BUG] EnumToBool Converter causing application crash when used in a data trigger

### ISSUE THREAD

**Issue by adlartuten** [CommunityToolkit/Maui#2062] opened 2024-07-25 17:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When using the EnumToBool converter in a data trigger, the application crashes showing "Non-nullable are not valid" error

### Expected Behavior

Converter should be able to be used inside of a data trigger

### Steps To Reproduce

Open solution
Run

### Link to public reproduction project repository

https://github.com/adlartuten/ToolkitTest

### Environment

```markdown
- .NET MAUI CommunityToolkit:9.0.2
- OS: Windows, Android, iOS
- .NET MAUI:8.0.70
```

### Anything else?

This does not happen on version 9.0.1, it first appeared in 9.0.2

**Comment by bijington** [comment] 2024-07-25 18:04
Thanks for this report, it is actually a duplicate of https://github.com/CommunityToolkit/Maui/issues/2046 which has a fix. We haven't released the fix yet but it will be coming soon. For now please stay on 9.0.1 and know that the next published version will include a fix.

**Closed by bijington** 2024-07-25 18:04 UTC
Labels: bug, duplicate, unverified
