### ISSUE TITLE
[Bug] build error with maui preview 14

### ISSUE THREAD

**Issue by ialbert-AUT** [CommunityToolkit/Maui#330] opened 2022-03-18 09:30 UTC
### Description

- open a new maui app template
- add nuget package communitytoolkit.maui, 1.0.0-pre7 
- switch to windows 
and you get build errors:
1>WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
1>WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI222: 0x80073b0f - Unspecified error occurred.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: 1.0.0-pre7 + maui preview 14
- Last known good version: maui preview 13
- IDE: vs 17.2.0 preview 2
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by VladislavAntonyuk** [comment] 2022-03-18 09:34
It will be released today.
Duplicate of https://github.com/CommunityToolkit/Maui/issues/328

**Closed by VladislavAntonyuk** 2022-03-18 09:34 UTC
Labels: bug, unverified
