### ISSUE TITLE
Building the Toolkit Sample project requires Long Path Support to be enabled.

### ISSUE THREAD

**Issue by bakerhillpins** [CommunityToolkit/Maui#414] opened 2022-05-19 12:41 UTC
### Description

One cannot build the Toolkit Sample project without [Enabling Long Path support](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later) in windows. It appears that the Source generators are using some sort of mixed Project/TypeName scheme to store output files and avoid name collisions.  

I've looked but not located any Wiki or other build discussion that mentions the Long Path support requirement. TBH, I didn't look that hard even after the issue, and I didn't dig farther than the landing page readme.md when I cloned the project.

One example of many that results from the output of building Project: CommunityToolkit.Maui.Sample:
```
4>CSC : error CS0016: Could not write to output file 'C:\MauiTesting\Maui\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.EnumToBoolConverterViewModel.cs' -- 'Could not find a part of the path 'C:\MauiTesting\Maui\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.EnumToBoolConverterViewModel.cs'.'
```

I cloned the project into the default `C:\MauiTesting\` folder that VS2022 preview uses as the default project dir. So the root path is just about as small as it gets. Thus `C:\MauiTesting\Maui\samples\CommunityToolkit.Maui.Sample\obj` is the project contribution to the path and the generator adds: 

```
\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.EnumToBoolConverterViewModel.cs
```

While I understand the basic premise here is to avoid name collisions I wonder if the same effect might be observed by removing all the path/folder redirection and sticking with namespace prefixed filenames? In my Source Generator code I inject information about the Generator that created the file using attributes such as: (I'm using Scriban templates here and can provide an example if you'd like)

```
namespace {{ RootNamespace }}
{
    [ GeneratedCode("{{ GeneratorName }}", "{{ Version }}" ) ]
    [ CompilerGenerated ]
    internal class AGeneratedClass : ISomeInterface
```

While not an issue for me at the moment some organizations lock users out of OS changes as well which might be a bit of a struggle if the IS organizations are like most I've encountered over the years.

### Link to Reproduction Sample

[Toolkit Sample Project ](https://github.com/CommunityToolkit/Maui/tree/main/samples)

### Steps to Reproduce

1. Disable Long Path support in windows if you already have it.
2. Build the sample project.

### Expected Behavior

You can build the project without taking extra OS configuration steps.

### Actual Behavior

Confusing build errors and Registry edits required to get it to build.

- IDE: VS2022 17.3.0 Preview 1

### Workaround
 [Enabling Long Path support](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later) in windows.

**Comment by bijington** [comment] 2022-05-19 13:54
@bakerhillpins thanks for the report. Sadly this is a limitation of Windows as you have pointed out. I really hope the path limit will disappear entirely at some point.

We do currently have a discussion here #399 that helps consumers learn how to solve the issue but it does keep cropping up. I am going to close this for now as there isn't anything we can action.

**Closed by bijington** 2022-05-19 13:54 UTC
Labels: bug, unverified

**Comment by bakerhillpins** [comment] 2022-05-19 14:40
The discussion you mention is clearly NOT enough. 

> I am going to close this for now as there isn't anything we can action.

I'm sorry but that's just not true. It maybe something that you don't want to do but there are clearly things you can do.  The absolute bear minimum would be to edit the root readme.md 

Disappointing to say the least.

**Comment by bijington** [comment] 2022-05-19 14:51
> The discussion you mention is clearly NOT enough. 
> 
> 
> 
> > I am going to close this for now as there isn't anything we can action.
> 
> 
> 
> I'm sorry but that's just not true. It maybe something that you don't want to do but there are clearly things you can do.  The absolute bear minimum would be to edit the root readme.md 
> 
> 
> 
> Disappointing to say the least. 
> 
> 

Sorry I see my message wasn't very clear. I meant there wasn't anything to action in terms of a code change. The linked discussion already suggests we will look at adding the information to the readme file and I would like to keep the information in one place. I have some other thoughts now so I'll place them on the discussion.

**Comment by bakerhillpins** [comment] 2022-05-19 15:06
> I meant there wasn't anything to action in terms of a code change.

Disagree, You could change the way the generators layout files on disk.  I provided one such option using .NET attributes that actually embed the generator info in the source which would remove the need to use the directory structure to do so.

That being said, I am not fully aware of why those structural decisions were made but I've seen lots of generator implementations where that level of verbosity is not required so it's difficult to understand the need.

**Comment by pictos** [comment] 2022-05-19 15:07
@bakerhillpins you can also comment those lines in your `csproj` to not copy those generated files to the obj folder
https://github.com/CommunityToolkit/Maui/blob/dfe36fc475d3f5a5ebb06b6d8399032bc024b46e/samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj#L23-L24

This should avoid this long path error to show up

**Comment by bakerhillpins** [comment] 2022-05-19 15:16
@pictos  Agreed, I could do that.  I'd say that the greater issue here is that there is a basic assumption (well founded I'd argue) that users of the sample projects should not have to edit the source code to get it to work.  I'd also go so far as to say they shouldn't have to alter the operating system configuration to do so.  Apparently I'm in the minority.

**Comment by bakerhillpins** [comment] 2022-05-19 15:20
> > @bakerhillpins you can also comment those lines in your `csproj` to not copy those generated files to the obj folder
> > https://github.com/CommunityToolkit/Maui/blob/dfe36fc475d3f5a5ebb06b6d8399032bc024b46e/samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj#L23-L24
> > 
> > This should avoid this long path error to show up
> 
> @pictos what impact does not copying to the obj folder have? Would it stop things like be able to view the definition from inside VS?

I don't currently copy my generated files to an output directory. They are available to be viewed if you expand the Analyzers in Solution explorer:

![image](https://user-images.githubusercontent.com/5980709/169333708-d4ff6343-446d-4174-8c52-f8bbadcdb9ed.png)

**Comment by bijington** [comment] 2022-05-19 15:30
@bakerhillpins having read your error message again I can see that the issue is in one of the samples dependencies `CommunityToolkit.Mvvm.SourceGenerators` and not actually our source generators. 

That toolkit is over at: https://github.com/CommunityToolkit/dotnet

This information may be beneficial to them.

**Comment by pictos** [comment] 2022-05-19 15:31
@bijington will not affect any functionality around VS and generated code. That configuration is there to workaround some issues, at the time that we implemented the SGs, on VS Windows and Mac.

@bakerhillpins yes, you're right, but at the time that we did the SG that view was broken and on VSMac you can't see the generated files inside the IDE. We'll disable that csproj configuration by default to avoid devs to hit this issue.

**Comment by bakerhillpins** [comment] 2022-05-19 15:38
@bijington  Thank you for pointing that out. I failed to dig deep enough into the output to realize that it was not the source generators included in this project.

@pictos  I see the dilemma you face. While I don't have any direct experience with VS for Mac I do now understand why this path was chosen.  Thanks for that!
