### ISSUE TITLE
[Bug]  Maui Preview 12 will not build with latest CommunityToolkit.Maui nuget

### ISSUE THREAD

**Issue by Orgbrat** [CommunityToolkit/Maui#256] opened 2022-01-22 17:41 UTC
### Description

After updating to VS2022 Preview 3 which updates to Maui Preview 12 my Maui project would not build
with the below errors

### Errors

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.	
MyApp E:\Work - VS.NET 2022\Maui\MyApp\WINAPPSDKGENERATEPROJECTPRIFILE

Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI222: 0x80073b0f - Unspecified error occurred.	
MyApp E:\Work - VS.NET 2022\Maui\MyApp\WINAPPSDKGENERATEPROJECTPRIFILE

**Comment by brminnick** [comment] 2022-01-22 17:53
Hi @Orgbrat! This is a duplicate of https://github.com/CommunityToolkit/Maui/issues/253

We had to first update the .NET MAUI Community Toolkit for P12 ([PR completed here](https://github.com/CommunityToolkit/Maui/pull/252)), and we will be release CommunityToolkit.Maui-pre5 this upcoming week which will work with .NET MAUI Preview 12 included in VS 2022 Preview 3 👍

**Closed by brminnick** 2022-01-22 17:53 UTC
Labels: bug, unverified
