### ISSUE TITLE
[BUG] filesystem:// does not work for MediaElement.Source using MVVM

### ISSUE THREAD

**Issue by Cywizz** [CommunityToolkit/Maui#1177] opened 2023-05-09 13:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Hardcoding a file system path for the MediaElement's Source property in XAML works as expected. 
It does NOT work when you use databinding in MVVM pattern.
The MediaFailed event handler returns SourceNotSupported.

### Expected Behavior

Video should render and play using hardcoded or mvvm databinding

### Steps To Reproduce

1. Open and run repro project
2. Click Load Video button
3. Comment and uncomment the 2 scenarios as described above to see 2 different behaviors

### Link to public reproduction project repository

https://github.com/Cywizz/MediaElementFileSystemIssue

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.1.0
- OS Windows 10 21H2:
- .NET MAUI: latest on VS 2022 17.6.0 Preview 3.0
- Net MAUI CT MediaElement: 1.0.2
```

### Anything else?

I have not included a video in the repro, so replace it with a local file system video to reproduce.

**Comment by BobSammers** [comment] 2023-05-18 12:21
I've just run into a similar problem. I think the issue is that the `Source` property in the `MediaElement` is of type `MediaSource` and the string value is not being converted when applied via a binding, whereas it is (because of a `TypeConverter` attribute on the property) when it's set directly.

This looks like #7683 in dotnet/maui, which was apparently recently fixed. Until it's in a release, I've worked around the bug by changing my Source property from `string` to `MediaSource` and run the `MediaSource.FromFile()` on the `string` argument when setting it.

**Comment by Cywizz** [comment] 2023-05-19 04:48
@BobSammers Thanks for the workaround suggestion, didn't think of that. 
I broke the MVVM principle temporarily by getting a handle to the MediaElement directly from the page in the viewmodel...until things are fixed.

**Comment by BobSammers** [comment] 2023-05-22 14:26
> I broke the MVVM principle temporarily

I don't think putting `MediaSource` in the VM (like I did) is exactly in the spirit of MVVM either... :)

**Comment by brminnick** [comment] 2023-06-05 22:34
Fixed in https://github.com/dotnet/maui/issues/7683

**Closed by brminnick** 2023-06-05 22:34 UTC
Labels: bug, unverified
