### ISSUE TITLE
[BUG] StateContainer always returns infinity as height 

### ISSUE THREAD

**Issue by mattleibow** [CommunityToolkit/Maui#1293] opened 2023-07-11 18:20 UTC
---
**Issue moved from dotnet/maui#16085**
- Please respond to @NirmalKumarYuvaraj.

---

_From @NirmalKumarYuvaraj on Tuesday, July 11, 2023 1:39:58 PM_

### Description

StateContainer always returns height as infinity for its child elements.

### Steps to Reproduce

1. Create a StackLayout or Grid Layout.
2. Add a custom box view inside the Grid Or StackLayout.
3. Run the sample.

### Link to public reproduction project repository

https://github.com/NirmalKumarYuvaraj/StateContainer

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 11 and Up

**Comment by cat0363** [comment] 2023-07-28 04:50
Hi, @mattleibow 
I tried not to use StateContainer by laying out as follows.

    <Grid RowDefinitions="*" VerticalOptions="FillAndExpand">
        <StackLayout>
            <custom:CustomBoxView />
        </StackLayout>
    </Grid>

With or without a StateContainer, it will have an infinite height.
Is this a StateContainer issue?

Isn't it related to child elements in the StackLayout not being given an explicit size?
Sorry if I misunderstood.

**Comment by johnernest02** [comment] 2023-08-15 06:59
Yep, getting this same issue. I have a list screen and no matter what I use, BindableLayout or CollectionView, the lists always display everything and it doesn't scroll. It will only work if the list container (or the direct child of the containerView having the `StateKey` has a fixed height

**Comment by vhugogarcia** [comment] 2024-07-22 17:48
> ```
> <Grid RowDefinitions="*" VerticalOptions="FillAndExpand">
>     <StackLayout>
>         <custom:CustomBoxView />
>     </StackLayout>
> </Grid>
> ```
> 
> With or without a StateContainer, it will have an infinite height. Is this a StateContainer issue?
> 
> Isn't it related to child elements in the StackLayout not being given an explicit size? Sorry if I misunderstood.

After spending a couple of hours on this issue. @cat0363 is correct, the CollectionView, ListView and BindableLayouts grow infinite to display all the elements on the screen at least there is an element after the collection view that stops it to grow, or by setting a height of the screen area you are expecting. @NirmalKumarYuvaraj, this article shows how to calculate the height and width of the screen and set the container sizes as expected: https://dev.to/vhugogarcia/responsive-flyout-in-net-maui-4ll1 you can use it as base sample to achieve what you need for your UI.

.NET MAUI on recent updates have been improving the rendering of the CollectionView layout. @NirmalKumarYuvaraj The attached sample is not complete and uses syncfusion controls, could you please confirm what @cat0363 mentioned?, and if you confirm it, maybe create a ticket on the .NET MAUI repository with the full sample repro without syncfusion, so the team can test without third-party controls.

For what I mentioned above, I'm closing this issue since we are unable to reproduce the issue specifically for the StateContainer layout.

cc: @brminnick

**Closed by vhugogarcia** 2024-07-22 17:48 UTC
Labels: bug, unverified, area/layouts
