### ISSUE TITLE
[BUG] Non-nullable are not valid InvalidOperationException is thrown when using VariableMultiValueConverter

### ISSUE THREAD

**Issue by usefulBeeing** [CommunityToolkit/Maui#2003] opened 2024-07-06 21:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

System.InvalidOperationException: 'Non-nullable are not valid'

### Expected Behavior

MultiBinding works as it used to in prior versions.

### Steps To Reproduce

1- Give MainPage a reference name
     `x:Name="ThisPage"`

2- Copy and paste the following code in MainPage:

```
    <ContentPage.Resources>
        <toolkit:VariableMultiValueConverter ConditionType="All" x:Key="VariableMultiValueConverterAll" />
        <toolkit:InvertedBoolConverter x:Key="InvertedBoolConverter" />
    </ContentPage.Resources>

    <ScrollView>
        <VerticalStackLayout
            Padding="30,0"
            Spacing="25">
            <VerticalStackLayout.IsEnabled>
                <MultiBinding Converter="{StaticResource VariableMultiValueConverterAll}">
                    <Binding Path="IsEnabled" Source="{x:Reference ThisPage}" Converter="{StaticResource InvertedBoolConverter}" />
                    <Binding Path="IsVisible" Source="{x:Reference ThisPage}" Converter="{StaticResource InvertedBoolConverter}" />
                </MultiBinding>
            </VerticalStackLayout.IsEnabled>
        </VerticalStackLayout>
    </ScrollView>
```
3- Make sure CommunityToolkit.Maui 9.0.2 is installed
4- Non-nullable are not valid exception is thrown
5- Revert back to CommunityToolkit.Maui 9.0.1 to avoid this issue

<img width="794" alt="Non-nullable2" src="https://github.com/CommunityToolkit/Maui/assets/174826497/3553cc97-23b0-4d24-b32c-365068000032">
 

### Link to public reproduction project repository

https://github.com/usefulBeeing/MauiNonNullableError

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: Windows 10.0.22631 Build 22631
- .NET MAUI: 8.0.61
```

**Comment by MauiUIui** [comment] 2024-07-07 22:12
I can confirm the existence of this issue, however I don't think the mentioned converter is the reason behind.
See with me it happened after I used the `MathExpressionConverter` in a base project (not my main project). However after removing the usage, the exception didn't go away. So when I gave it a thought, I remembered that I also did upgrade to version 9.0.2 of the community toolkit just before using the converter. I downgraded back to 9.0.1 and all works fine now. So I guess it's some kind of a bug with the latest versions. @usefulBeeing Please give feedback whether you also upgraded and downgrading helps.

**Comment by usefulBeeing** [comment] 2024-07-07 23:02
@MauiUIui , thank you for recording your experience. I'm also in doubt that it's `VariableMultiValueConverter` issue.  With that said, I tried something like this without encountering any failure while using 9.0.2:

  `<VerticalStackLayout
              Padding="30,0"
              Spacing="25" IsEnabled="{Binding Path=IsVisible, Source={x:Reference ThisPage}, Converter={StaticResource InvertedBoolConverter}}">`

In order to use `VariableMultiValueConverter` successfully, I had to downgrade to 9.0.1, as I hinted in step 5 of issue reproduction.

For more in depth look. here is the StackTrace:

```
1.    at CommunityToolkit.Maui.Extensions.ValueConverterExtension.<IsValidTargetType>g__IsValidNullableValueType|2_2[TTarget](Type targetType)
2.    at CommunityToolkit.Maui.Extensions.ValueConverterExtension.IsValidTargetType[TTarget](Type& targetType, Boolean shouldAllowNullableValueTypes)
3.    at CommunityToolkit.Maui.Extensions.ValueConverterExtension.ValidateTargetType[TTarget](Type targetType, Boolean shouldAllowNullableValueTypes)
4.    at CommunityToolkit.Maui.Converters.BaseConverter`2.CommunityToolkit.Maui.Converters.ICommunityToolkitValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
5.    at CommunityToolkit.Maui.Converters.ICommunityToolkitValueConverter.Microsoft.Maui.Controls.IValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
6.    at Microsoft.Maui.Controls.Binding.GetSourceValue(Object value, Type targetPropertyType)
7.    at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
8.    at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity)
9.    at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity)
10.    at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
11.    at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding)
12.    at Microsoft.Maui.Controls.MultiBinding.Apply(Object context, BindableObject targetObject, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity)
13.    at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
14.    at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding)
15.    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.TrySetBinding(Object element, BindableProperty property, String localName, Object value, IXmlLineInfo lineInfo, BindingBase& binding, Exception& exception)
16.    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.TrySetPropertyValue(Object element, XmlName propertyName, String xKey, Object value, Object rootElement, IXmlLineInfo lineInfo, IServiceProvider serviceProvider, Exception& xpe)
17.    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
18.    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
19.    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
20.    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
21.    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
22.    at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
23.    at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
24.    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
25.    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
26.    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
27.    at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType)
28.    at MauiApp3.MainPage.InitializeComponent() in C:\Users\....\source\repos\MauiApp3\MauiApp3\obj\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\MainPage.xaml.sg.cs:line 26
29.    at MauiApp3.MainPage..ctor() in C:\Users\...\source\repos\MauiApp3\MauiApp3\MainPage.xaml.cs:line 9
30.    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```
<img width="1102" alt="Non-nullable3" src="https://github.com/CommunityToolkit/Maui/assets/174826497/66b89aab-94e5-4cb3-ae8f-8ffe9311df64">

**Comment by bijington** [comment] 2024-07-08 05:05
Thanks for the details. I suspect the cause of this was this change https://github.com/CommunityToolkit/Maui/pull/1926 I thought I had tested all scenarios but I must have missed one. I can try to take a look 👍

**Comment by awasilik** [comment] 2024-07-08 09:56
I encountered the same issue with 9.0.2, downgraded to 9.0.1. This probably needs top priority cause all future versions will have the same problem

**Comment by sumowesley** [comment] 2024-07-08 13:37
I have another instance here, using an IValueConverter. Going back to version 9.0.1 works fine.

**Comment by MauiUIui** [comment] 2024-07-08 19:59
@usefulBeeing Sorry, I hadn't made it till step 5 while reading 😛
Anyway I'm glad that there is a solution (workaround) for the issue and thankful or the team, and especially @bijington, for taking the issue seriously and in such a timely manner. I hope it gets fixed soon 👍

**Comment by softlion** [comment] 2024-07-09 14:19
There is a breaking change in InvertedBoolConverter

That converter throws an exception when the binded value is null. Before this release, it would not.

I understand why it is throwing now, because it does not know what to return when the bool is null.

But in the context of binding, while the BindingContext is not yet set, most boolean will be null. That does happen a lot.

**Comment by usefulBeeing** [comment] 2024-07-09 18:24
@softlion , thank you for sharing your thoughts and solution. While your InvertedNullableBoolConverter does work flawlessly :), I believe many developers prefer CommunityToolkit Converters for convenience vs speed.

In addition, the `Non-nullable are not valid` exception doesn't only affect `InvertedBoolConverter` but extends to other converters, such as but not limited to:  `IsListNullOrEmptyConverter`, `IsListNotNullOrEmptyConverter`, `IsNotNullConverter`, `StateToBooleanConverter` ...etc

**Comment by bijington** [comment] 2024-07-09 18:36
To add some context, the converters in the scenario reported are not through compiled bindings and therefore the `targetType` being passed into the `InvertedBoolConverter` is of type `object`. The fix might be to undo the original PR or handle the specific case for `object`.

**Comment by LaBoss** [comment] 2024-07-10 13:16
The IsNotNullConverter throw same error on 9.0.2 in 9.0.1 is Ok

**Comment by MichaelShapiro** [comment] 2024-07-16 14:30
Experiencing the same identical issue in 9.0.2. Had to downgrade back to 9.0.1 to restore workability of my code. Hoping that it is being addressed soon.

**Comment by daltzctr** [comment] 2024-07-17 15:31
I'm surprised this hasn't been fixed yet or caught in any tests as it's extremely easy to reproduce. It also critically breaks many applications. 

Either null checking should get added to the converters or the PR should get reverted.

**Comment by turdmaggot** [comment] 2024-07-20 16:38
I need to get this System.InvalidOperationException: 'Non-nullable are not valid' error fixed as it is causing a lot of crashes on our end while opening popups.

I can't roll back to 9.0.1, as we are having critical popup issues in Windows that can only be fixed by https://github.com/CommunityToolkit/Maui/pull/1932, which is only available in 9.0.2.

**Comment by vhugogarcia** [comment] 2024-07-22 14:03
Closing this issue, since the fix has been merged into main, and the related issue #2046 has been closed as well. A new version is expected to be released soon.

**Comment by bijington** [comment] 2024-07-22 16:02
@vhugogarcia the PR hasn't merged just yet

**Comment by vhugogarcia** [comment] 2024-07-22 16:04
oh! you are right! Sorry for jumping ahead. thanks @bijington for catching up.

**Closed** 2024-07-24 18:41 UTC
Labels: bug, area/behaviors
