### ISSUE TITLE
[Bug] Build error on Windows

### ISSUE THREAD

**Issue by davidortinau** [CommunityToolkit/Maui#416] opened 2022-05-20 02:16 UTC
![image](https://user-images.githubusercontent.com/41873/169434586-cf051046-c92c-4f16-b673-0f0f6439e8a2.png)

### Description

I'm getting this WinAppSDK build error on multiple projects after I add CommunityToolkit.Maui to a project and build it for Windows. The only thing I'm trying to use is the bool to object converter.

### Stack Trace

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.	ControlGallery	C:\work\ControlGallery\src\ControlGallery\WINAPPSDKGENERATEPROJECTPRIFILE	1	
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		PRI222: 0x80073b0f - Unspecified error occurred.	ControlGallery	C:\work\ControlGallery\src\ControlGallery\WINAPPSDKGENERATEPROJECTPRIFILE	1	
```

### Link to Reproduction Sample

https://github.com/davidortinau/ControlGallery

### Steps to Reproduce

Just add the NuGet, init in MauiProgram, and build for Windows. 

### Expected Behavior

Successful build

### Actual Behavior

Errors ^

### Basic Information

- Version with issue: 1.0.0-rc3 with MAUI 6.0.400-preview.1.5823 (main branch)

### Workaround

write my own converter

**Comment by pictos** [comment] 2022-05-20 04:13
@davidortinau if you try it using the public version of .NET MAUI does it compiles?
I'm asking because we always need to rebuild the project on top of a specific .NET MAUI version

**Comment by VladislavAntonyuk** [comment] 2022-05-20 06:32
It's expected.
We have this issue with each new .NET MAUI release: https://github.com/CommunityToolkit/Maui/issues/328

**Comment by Orgbrat** [comment] 2022-05-23 19:52
@VladislavAntonyu @jfversluis @brminnick  Are we working on the fix for this? I opened a Visual Studio problem before I realized this was a toolkit issue caused by a MAUI update. Keep us updated as we are broken till we get a fix.

**Comment by VladislavAntonyuk** [comment] 2022-05-23 19:58
as for the GA, we may release it very soon,
as for the MAUI 6.0.400-preview.1.5823 (main branch) we haven't discussed it, we plan to support a stable version of .NET MAUI after GA

**Comment by Orgbrat** [comment] 2022-05-23 20:25
@VladislavAntonyuk  So since VS2022 17.3.0 Preview 1.1 is MAUI workload GA Build, you are going to release a GA CommunityToolkit.Maui pretty soon so we can build again?

**Comment by VladislavAntonyuk** [comment] 2022-05-23 20:35
yes, exactly as we did for previews and rc builds.

**Comment by Orgbrat** [comment] 2022-05-23 20:35
Thank you and have a great day. You guys are the best...

**Comment by VladislavAntonyuk** [comment] 2022-05-24 12:12
@davidortinau we have released version 1.0.0 
Does it work with .NET MAUI main branch?

**Comment by VladislavAntonyuk** [comment] 2022-06-09 22:02
as we plan to fix .NET MAUI version (https://github.com/CommunityToolkit/Maui/issues/424) can we close this issue?
@brminnick what do you think?

**Comment by brminnick** [comment] 2022-06-09 23:09
Agreed. This can be closed.

**Comment by pictos** [comment] 2022-06-09 23:18
Closing this issue then.

**Closed by pictos** 2022-06-09 23:18 UTC
Labels: bug, unverified
