### ISSUE TITLE
[BUG] DisplayAlert not working on Popup 

### ISSUE THREAD

**Issue by acaliaro** [CommunityToolkit/Maui#1168] opened 2023-05-02 06:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I opened an issue in Maui, but I don't know if it's a Maui or a Toolkit issue. Trying to display a DisplayAlert by pressing a Button in a CommunityToolkit.Maui Popup. The DisplayAlert is not displayed

https://github.com/dotnet/maui/issues/14870

### Expected Behavior

The DisplayAlert should show up

### Steps To Reproduce

Take a look to https://github.com/dotnet/maui/issues/14870

### Link to public reproduction project repository

https://github.com/acaliaro/MauiPicker

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: iOS 15.7
- .NET MAUI: 

Microsoft Visual Studio Community 2022
Versione 17.5.5
VisualStudio.17.Release/17.5.5+33627.172
Microsoft .NET Framework
Versione 4.8.09032

Edizione installata: Community

Visual C++ 2022   00482-90000-00000-AA928
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.5.320.55692
ASP.NET and Web Tools

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.5.320.55692
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Gestione pacchetti NuGet   6.5.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web https://docs.nuget.org/

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
Fornisce servizi di linguaggio per ASP.NET Core Razor.

ResX Resource Manager   ResXManager
Manage localization of all ResX-based resources in one place. Shows all resources of a solution and lets you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   17.2.40120.0
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.8
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

Strumenti C#   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti comuni di Azure   1.10
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.

Strumenti del Servizio app di Azure versione 3.0.0   17.5.320.55692
Strumenti del Servizio app di Azure versione 3.0.0

Strumenti di Microsoft Azure per Visual Studio   2.9
Supporto per i progetti di Servizi cloud di Azure

Strumenti di Visual Basic   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti TypeScript   17.0.20105.2003
Strumenti TypeScript per Microsoft Visual Studio

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
Sviluppo assistito conl'intelligenza artificiale per Visual Studio.

VisualStudio.DeviceLog   1.0
Informazioni sul pacchetto

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.5.0.173 (d17-5@33e727c)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Estensione di Visual Studio per abilitare gli strumenti di Xamarin Designer in Visual Studio.

Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77


Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by acaliaro** [comment] 2023-05-05 05:15
@bijington this is what I would like to have

![image](https://user-images.githubusercontent.com/5759350/236382028-822bbbfb-499e-47bd-a165-b8d2e87999a5.png)


it works in android, I would expect it to work in iOS and other platforms as well, otherwise it's not Cross Platform
Thanks

**Comment by marekm294** [comment] 2023-05-05 17:02
This is probably a duplicate of https://github.com/CommunityToolkit/Maui/issues/1106

**Comment by bijington** [comment] 2023-05-06 12:03
Sorry to confirm does it only work on Android? Or does it only not work on iOS?

Thanks for the update, I saw you replied on Twitter too but here is probably a better place to track it. I would personally suggest avoiding the alert in this scenario and moving to showing the validation in the popup itself. This could be achieve through the use of our [`ValidationBehaviors`](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/) and possibly even making use of the [`AnimationBehavior`](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/animation-behavior) to shake or similar in order to highlight that the controls are invalid. You also have space to the left of your buttons at the bottom which could present a message indicating that the action cannot be completed.

What do you think?

**Comment by acaliaro** [comment] 2023-05-06 21:50
Hi @bijington 
yes, it works on Android and does not work on iOS.
Thanks for the reply.
I can also understand your suggestion not to use DisplayAlert on a popup, and that they may even be better choices, but in a Cross Platform product, I expect that if it works on Android, it also works on iOS and on Windows, otherwise it can't. define a Cross Platform product. It seems that the reason why it doesn't work on iOS has already been found, it is to be understood whether or not it can be solved

**Comment by brminnick** [comment] 2023-05-06 21:58
We likely won't be able to address this until the .NET MAUI team addresses https://github.com/dotnet/maui/issues/14258.

Until then, I recommend dismissing the Popup before calling `DisplayAlert()`:

```cs
myPopup.Close();

// Wait for iOS to fully dismiss Popup
await Task.Delay(750);

await DisplayAlert("Title", "Description", "OK");
```

**Comment by pictos** [comment] 2023-05-07 00:04
So, AFAIK this an .NET MAUI limitation, and when they implement the fix for it, this scenario will work by default, so can we close this issue?

If after the .NET MAUI implementation this scenarios still doesn't work we can re-open this or open a new one

**Comment by brminnick** [comment] 2023-08-08 20:14
Fixed in https://github.com/dotnet/maui/pull/16046

**Closed by brminnick** 2023-08-08 20:14 UTC
Labels: bug, unverified
