### ISSUE TITLE
[BUG] Wrong item is registered when pressing an item in a CollectionView using TouchBehavior

### ISSUE THREAD

**Issue by TiicTac54** [CommunityToolkit/Maui#1865] opened 2024-05-08 15:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When I press an item in a CollectionView using a TouchBehavior, another item is recorded as pressed.

https://github.com/CommunityToolkit/Maui/assets/56891833/5074828b-864d-4697-b6b3-a25ee0e307ae

Here's how I configure my TouchBehavior on each element of my list
```
 <CollectionView Grid.Row="1" ItemsSource="{Binding Items}">
    <CollectionView.ItemsLayout>
        <LinearItemsLayout ItemSpacing="4" Orientation="Vertical" />
    </CollectionView.ItemsLayout>
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <VerticalStackLayout
                Padding="6"
                BackgroundColor="LightGray"
                HeightRequest="50">
                <Label Text="{Binding .}" />
                <VerticalStackLayout.Behaviors>
                    <toolkit:TouchBehavior Command="{Binding Source={x:Reference This},  Path=BindingContext.ItemTapCommandCommand}" CommandParameter="{Binding .}" />
                </VerticalStackLayout.Behaviors>
            </VerticalStackLayout>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

### Expected Behavior

If I press any item in the CollectionView, only the one I press should be registered.

### Steps To Reproduce

1. Have any list with enough items to be able to scroll.
2. Scroll the list.
3. Press any items

### Link to public reproduction project repository

https://github.com/TiicTac54/TouchBehaviorBugWithCollectionView.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:8.0.x
- OS:Android, iOS
- .NET MAUI:8.0.20
```

### Anything else?

Using a TapGestureRecognizer does not cause this issue.

**Comment by tranb3r** [comment] 2024-05-08 19:08
Isn't it a duplicate of #1804 ?

**Comment by TiicTac54** [comment] 2024-05-08 19:19
It could be, but for me regressing to 8.0.0 didn't work for me. I have the same issue whatever version I use

**Comment by pictos** [comment] 2024-05-08 20:50
From what I can see the issue is the same as #1804.

 @TiicTac54  can you test the nuget generated by this [PR](https://github.com/CommunityToolkit/Maui/pull/1815) and tell me if that fixes your issue

**Comment by holesnap** [comment] 2024-05-09 10:26
> From what I can see the issue is the same as #1804.
> 
> @TiicTac54 can you test the nuget generated by this [PR](https://github.com/CommunityToolkit/Maui/pull/1815) and tell me if that fixes your issue

how can I test the nuget generated by the PR? do you have the link?

**Comment by TiicTac54** [comment] 2024-05-09 15:20
@pictos I tried your fix and it works for android, but not for iOS. On iOS, the first press can be wrong, but if I do not scroll the second press will always be right. Adding ItemSizingStrategy="MeasureFirstItem" on the collectionView fixes the issue. However, that property with the TouchBehavior breaks on Android. 

Finally, the issue (on iOS) only seems to occurs when navigating to a page from the collectionView, coming back and then press a new item. If I remove the navigation part, it works with no problem (fix and without the fix)

**Comment by pictos** [comment] 2024-05-09 17:53
@TiicTac54 thanks for the info and try out, I'll see if I can address it on my current PR

**Comment by maexsp** [comment] 2024-05-16 09:05
Run into same issue. When navigating into a sub page and navigate back than the registered item is wrong.

**Comment by Hackmodford** [comment] 2024-05-17 17:07
Just noticed this today.

```C#
<CollectionView.ItemTemplate>
                    <DataTemplate x:DataType="foot:DebugCommand">
                        <Grid>
                            <Border x:Name="AdvancedView"
                                    Margin="16,0"
                                    Style="{StaticResource AppGradientBorderNoOutline}">
                                <Border.Behaviors>
                                    <mct:TouchBehavior DefaultAnimationDuration="250"
                                                       Command="{Binding Command}"
                                                       DefaultAnimationEasing="{x:Static Easing.SpringOut}"
                                                       PressedScale=".95" />
                                </Border.Behaviors>
                                <Grid ColumnDefinitions="Auto, *" ColumnSpacing="16">
                                    <Label Grid.Column="0"
                                           Text="{StaticResource CircleDot}"
                                           TextColor="{Binding Command.IsRunning, Converter={StaticResource IsExecutingToColorConverter}}"
                                           FontSize="18"
                                           FontFamily="FontAwesome-Solid"
                                           VerticalOptions="Center" />
                                    <Label Grid.Column="1"
                                           Text="{Binding Title}"
                                           TextColor="{StaticResource TitleTextColor}"
                                           VerticalOptions="Center"
                                           FontSize="18" />
                                </Grid>
                            </Border>
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
```

I'm literally binding the command to a command property in the datasource

**Comment by vtserej** [comment] 2024-11-08 17:11
It is an absolute disaster this feature is still not fixed. even with the launch of 9.11. There are people to rely on these packages on their daily job and having this critical, yes critical bug open for that much time it is not the way to go.

**Comment by brminnick** [comment] 2024-11-08 17:23
Hi @vtserej! Do you have a solution to fix it, and would you like to submit the fix in a PR?

The core maintainers of this repo are all volunteers. None of us get paid to work on this project. We don't work for Microsoft. Rather, we donate time away from our friends and families on nights and weekends to working on this project and helping the .NET MAUI community. 

This is an open source project for the community by the community. If you're able to provide a solution, please do! But please do not belittle the efforts of my team.

**Comment by brminnick** [comment] 2024-11-08 17:26
This Issue is resolved as a breaking change in our .NET 9 PR:  https://github.com/CommunityToolkit/Maui/pull/2215

**Comment by brminnick** [comment] 2024-11-08 17:27
Closing as duplicate: https://github.com/CommunityToolkit/Maui/issues/1804

**Closed** 2024-11-08 17:27 UTC
Labels: bug, unverified, area/behaviors
