### ISSUE TITLE
[BUG] If the interval between the popup show and the close method is less than 300 ms, the closeAsync() call fails to close the spinner popup on windows

### ISSUE THREAD

**Issue by kaushik-sarker** [CommunityToolkit/Maui#1705] opened 2024-02-22 14:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

If the interval between the popup show and the close method call is less than 300 ms, the close() call fails to close the spinner popup. 
Why do I want something like that? I am making a network request in the OnAppearing() method, and I want to display a loading spinner while making the request (please ignore the visual effect on the user). The network request might be resolved very quickly. I noticed that if the interval between Show and Close is very minimal, the popup is not closing, and this happens only inside the OnAppearing overridden method.

### Expected Behavior

The popup should be shown and closed properly.

### Steps To Reproduce

1. Open and run the solution.
2. The popup is displayed but not closing, though I have called the CloseAsync() method.

Please look into the OnAppearing() method inside MainPage.xaml.cs

### Link to public reproduction project repository

https://github.com/kaushik-sarker/PopupIssueDemo

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7.0.1
- OS: Windows 10
- .NET MAUI: net8.0
```

**Comment by vhugogarcia** [comment] 2024-07-23 20:38
Thanks @kaushik-sarker for creating this issue, after reviewing this issue in-depth I found the following:
 
I can confirm that if you try to show up the popup and then close it before 300ms, it won't close. However, the Popup has the following event that is triggered once the UI is fully loaded: 
```csharp
void Spinner_Opened(object? sender, CommunityToolkit.Maui.Core.PopupOpenedEventArgs e)
{
    Console.WriteLine("Popup Openned.");
    ((SpinnerPopup)sender).Close();
    Console.WriteLine("Popup Closed.");
}
``` 
On your sample, the popup won't be able to be closed, because the UI has not been initialized for instance it cannot close something that hasn't loaded visually speaking.

If by adding the Task.Delay(300) does not work for your scenario, I have a few recommendations that could work:

- Try to execute the network request on the Popup.OnOpened event, so you can safely close the popup when the request finishes.
- Don't use the popup to show a busy indicator and instead use a different busy indicator approach to show or hide the loading icon for example, the .NET MAUI activity indicator and render it on the UI somewhere you believe it fits better. 
- Use StateView from Maui Community Toolkit, it allows to show your own personal skeletons o loading indicators in your UI without obstructing the UI for the user.
- There are other third-party plugins that show loading indicators on MAUI that could help as well such as the one from [Sharpnado](https://www.sharpnado.com/).
- Don't show an indicator at all, if the network request you are going to perform is taking less than 250ms and it is running async maybe you don't need an indicator at all, but just leave that to happen so quickly that nobody will notice it.

I don't think this is an issue of the Popup itself but rather than the native platform itself, and what it takes the time to process the UI and hide it.

I'm closing this issue, however, if none of the recommendations mentioned above work for you, we can discuss it on a discussion topic, and generate ideas to solve it.

**Closed by vhugogarcia** 2024-07-23 20:38 UTC
Labels: bug, unverified, area/views
