### ISSUE TITLE
[BUG] Popup CanBeDismissedByTappingOutsideOfPopup=false doesn't work when changing window size on Windows

### ISSUE THREAD

**Issue by SunshineSpring666** [CommunityToolkit/Maui#684] opened 2022-10-09 08:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a lock popup is shown (CanBeDismissedByTappingOutsideOfPopup=false), changing the window size like dragging window border or maximizing it, makes the lock popup immediately close automatically.

### Expected Behavior

Such lock popup (with CanBeDismissedByTappingOutsideOfPopup=false) should not be able to be dismissed by user via window size changing on Windows.

### Steps To Reproduce

    public Popup LockPopup { get; set; } = new Popup();

    private void LockApp(object sender, EventArgs e)
    {
        Label titleLabel = new Label { Text = " This is a lock popup, which SHOULD NOT be CLOSED by changing window size (Maximize or drag window border on Windows)", FontSize = 14, Margin = 20 };
        Entry entry = new Entry { Placeholder = "Enter password: 1", IsPassword = true, ReturnType = ReturnType.Go, WidthRequest = 240, Margin = 10 }; entry.Completed += Unlock; entry.Focus();
        Button unlockButton = new Button { Text = "Unlock", HeightRequest = 50, VerticalOptions = LayoutOptions.End, Margin = 10, BindingContext = entry }; unlockButton.Clicked += Unlock;
        StackLayout rootStack = new StackLayout { };
        rootStack.Children.Add(titleLabel); rootStack.Children.Add(entry); rootStack.Children.Add(unlockButton);

        LockPopup = new Popup() { Content = rootStack, CanBeDismissedByTappingOutsideOfPopup = false, Color = Color.FromRgba("#222222") };
        this.ShowPopup(LockPopup);
    }

    private void Unlock(object sender, EventArgs e)
    {
        Entry entry = sender.GetType() == typeof(Entry) ? sender as Entry : (sender as VisualElement).BindingContext as Entry;
        if (entry.Text == "1")
            LockPopup.Close();
    }

### Link to public reproduction project repository

https://github.com/SunshineSpring666/PopupCloseBug.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:1.3.0
- OS:Windows 11 build 25217
- .NET MAUI: 6.0.424
```

**Comment by VladislavAntonyuk** [comment] 2023-01-13 15:37
duplicate of https://github.com/CommunityToolkit/Maui/issues/684

**Closed by VladislavAntonyuk** 2023-01-13 15:37 UTC
Labels: bug, unverified
