### ISSUE TITLE
[BUG]  VS Code  - `.UseMauiCommunityToolkit()` must be chained to `.UseMauiApp<T>()` 

### ISSUE THREAD

**Issue by stephenhauck** [CommunityToolkit/Maui#1619] opened 2023-12-22 10:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

when I add the code to use the community toolkit like so 
.UseMauiCommunityToolkit()

I get an error ...

`.UseMauiCommunityToolkit()` must be chained to `.UseMauiApp<T>()` [/Users/stephenhauck/MAUI_8_VS/MauiApp1/MauiApp1.csproj::TargetFramework=net8.0-android]

<img width="647" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/12648793/ffaba95c-26f0-44f5-8926-d3afb765804f">

### Expected Behavior

I expect it to be ready to go .... no matter what I do with the "suggestions" offered nothing resolves the error

### Steps To Reproduce

Create a new MAUI app ...
Add the community toolkit 
Add the initialization code ...

### Link to public reproduction project repository

https://github.com/stephenhauck/MAUI_8_VS

### Environment

```markdown
- .NET MAUI CommunityToolkit: 7
- OS: OSX
- .NET MAUI: 8.0.3/8.0.100
```

### Anything else?

Just getting everything setup and making sure it works since Visual Studio Mac is going away

**Comment by vhugogarcia** [comment] 2024-01-03 22:09
Thanks @stephenhauck for reporting the issue and upload a sample project. I tried your sample project on VS Code in macOS, and I had no issues at all loading/building the project. Also, the analyzer does not throw any error like the one you mentioned on the issue.

<img width="1019" alt="image" src="https://github.com/CommunityToolkit/Maui/assets/1047398/53d78b8f-2fd5-45af-8bbb-57802ce79c1b">

Please make sure you have installed the following VS Code extensions:
- C#
- C# Dev Kit
- .NET MAUI
- IntelliCode for C# Dev Kit
- .NET Install Tool

I'm closing this issue, however, if there are any additional technical questions, please feel free to start a [discussion](https://github.com/CommunityToolkit/Maui/discussions) so others can also provide some insights.

**Closed by vhugogarcia** 2024-01-03 22:09 UTC
Labels: bug, unverified, area/core

**Comment by twannie83** [comment] 2024-02-14 20:14
I got this exact issue. Strange thing is that it only occurs with archiving to real iOS device. Debug and Release on simulator no problem.
My versions are all to the latest stable. Can issue be reopend?
![image](https://github.com/CommunityToolkit/Maui/assets/25795066/9a291019-53da-4fe0-9f85-dd52e6597f37)

**Comment by pictos** [comment] 2024-02-14 22:29
@twannie83 can you provide a sample that reproduces your issue?

**Comment by twannie83** [comment] 2024-02-15 05:10
@pictos Thanx for the quick response. With preparing the branche for you I noticed my mistake in readme from nuget MauiProgram.cs This line has to be added, I totally missed! Thanx for the rubber ducking 👍 

![image](https://github.com/CommunityToolkit/Maui/assets/25795066/d756119f-b634-40ce-8f2d-3c61284da4c4)

**Comment by bryandam** [comment] 2024-06-19 18:52
Posting this here since this is currently a high-ranking search result.
Using the latest version of Visual Studio 2022 on Windows 11 I got this same error and had to resolve it by chaining the extension methods directly onto the CreateBuilder call:
![image](https://github.com/CommunityToolkit/Maui/assets/5198361/a170f779-9d36-4e92-939a-8f558168ebbd)
