### ISSUE TITLE
LazyView 

### ISSUE THREAD

**Issue by kphillpotts** [CommunityToolkit/Maui#722] opened 2022-11-02 00:33 UTC
# LazyView 

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary
The LazyView control allows you to delay the initialization of a View. You need to provide the type of the View that you want to be rendered, using the x:TypeArguments XAML namespace attribute, and handle its initialization using the LoadViewAsync method. The IsLoaded property can be examined to determine when the LazyView is loaded.

> Note: This proposal is a to port the existing LazyView functionality from the Xamarin Community Toolkit
* [Existing Docs](https://learn.microsoft.com/en-us/xamarin/community-toolkit/views/lazyview)
* [Xamarin Community Toolkit Implementation](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/LazyView)

## Motivation
[motivation]: #motivation
LazyView is one of the views that exist in the Xamarin Community Toolkit that has been requested as a missing piece in the migration of some big apps from Xamarin to MAUI.

## Detailed Design
[design]: #detailed-design

To provide a migration path forward from Xamarin Community Tookit, I see no reason to update the API surface area, as such it would be:

### Properties:
Property | Type | Description
-- | -- | --
IsLoaded | bool | Gets the loaded status of the LazyView.

### Methods:
Method | Return Type | Description
-- | -- | --
LoadViewAsync | ValueTask | Initialize the View.
Dispose | void | Cleans up the View, if required.

## XAML Usage
[usage]: #usage-syntax
```xml
     <StackLayout>
        <toolkit:LazyView x:TypeArguments="local:LazyTestView" IsLoaded = "{Binding IsLoaded}" />
    </StackLayout>
```

## C# Implementation of a LazyView derived 
```csharp
/// <summary>
/// This a basic implementation of the LazyView based on <see cref="BaseLazyView"/> use this an exemple to create yours
/// </summary>
/// <typeparam name="TView">Any <see cref="View"/></typeparam>
public class LazyView<TView> : BaseLazyView where TView : View, new()
{
  /// <summary>
  /// This method initializes your <see cref="LazyView{TView}"/>.
  /// </summary>
  /// <returns><see cref="ValueTask"/></returns>
  public override ValueTask LoadViewAsync()
  {
    View view = new TView { BindingContext = BindingContext };
    
    Content = view;
    
    SetIsLoaded(true);
    return new ValueTask(Task.FromResult(true));
  }
}
```

## Drawbacks
[drawbacks]: #drawbacks
No drawbacks I'm aware of, other than potentially competing priorities

## Unresolved Questions
[unresolved]: #unresolved-questions
* Are there any complications with a straight port across due to MAUI changes?
* Are there any feature requests, bugs that should be resolved at the time of porting

**Comment by bijington** [comment] 2022-11-02 19:50
The usage of `new TView` requires a parameterless constructor which matches what we had in Xamarin however could/should we allow for more power through the magic of DI?

**Comment by bijington** [comment] 2023-01-05 20:27
Is this a duplicate of #112? Or vice-versa?

**Comment by bijington** [comment] 2023-01-07 16:51
@kphillpotts is this something you are looking at implementing or would you be willing for some help? I need to find something to get involved with now.

**Comment by VladislavAntonyuk** [comment] 2023-01-21 09:23
Closing as duplicate of #112

**Closed** 2023-01-21 09:25 UTC
