### ISSUE TITLE
[BUG] [iOS] StatusBarBehavior breaks status bar background in landscape mode

### ISSUE THREAD

**Issue by ewerspej** [CommunityToolkit/Maui#662] opened 2022-09-28 08:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On iOS (15.5), when using the StatusBarBehavior app, the background rectangle of the status bar is displayed when rotating the device into landscape mode. The rectangle stays visible on the upper left corner, covering parts of the navigation bar/title bar while it should actually disappear entirely, because iOS 15.5 does not show the status bar in landscape mode at all.

### Expected Behavior

The status bar background is hidden, because iOS does not display the status bar at all in landscape mode

### Steps To Reproduce

1. Create a MAUI App with a Shell
2. Add the MAUI CommunityToolkit
3. Add a StatusBarBehavior to MainPage.xaml.cs and provide an explicit background color
4. Run the app on iOS
5. Rotate into landscape mode

### Link to public reproduction project repository

https://github.com/ewerspej/dotnet-maui-ct-bug-repro-status-bar-ios

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: Windows 10, running iOS 15.5 on an iPhone X remotely
- .NET MAUI: .NET 7.0-rc1 (7.0.100-rc.1.22431.12)
- Visual Studio 17.4 Preview 2.1
```

**Comment by jfversluis** [comment] 2022-09-28 08:27
Duplicate of #637

**Closed by jfversluis** 2022-09-28 08:27 UTC
Labels: bug, unverified

**Comment by ewerspej** [comment] 2022-09-28 08:50
@jfversluis Thanks, I didn't find that other issue, due to its description.
