### ISSUE TITLE
[Bug] Error XFC0000 `Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:toolkit:EventToCommandBehavior`

### ISSUE THREAD

**Issue by sam-wheat** [CommunityToolkit/Maui#427] opened 2022-05-25 14:33 UTC
Was receiving same error with last RC so I updated to 1.0.0 to try to resolve it but no luck.

Thanks

> Error	XFC0000	Cannot resolve type "http://schemas.microsoft.com/dotnet/2022/maui/toolkit:toolkit:EventToCommandBehavior".	

Namespace declaration:

	xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"

XAML:

		<CheckBox Margin="3,0,0,0"
				  IsChecked="{Binding ViewBuilder.DisplayGrandTotals}" 
				  IsVisible ="{Binding DisplayGrandTotalOption}"
				  Style="{TemplateBinding MeasureCheckBoxStyle}"
				  Grid.Row="2" >
			<CheckBox.Behaviors>
				<toolkit:EventToCommandBehavior 
								EventName="CheckedChanged" 
								Command="{Binding ReloadDataCommand}" >
				</toolkit:EventToCommandBehavior>
			</CheckBox.Behaviors>
		</CheckBox>
		
MauiProgram:

	var builder = MauiApp.CreateBuilder();
			builder
				.UseMauiApp<App>()
				.UseMauiCommunityToolkitCore()
				.UseMauiCommunityToolkit()
				.UseMauiCommunityToolkitMarkup()
				

Project:

      <PackageReference Include="CommunityToolkit.Maui" Version="1.0.0" />
	  <PackageReference Include="CommunityToolkit.Maui.Core" Version="1.0.0" />
	  <PackageReference Include="CommunityToolkit.Maui.Markup" Version="1.0.0" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="7.1.2" />
				
Visual Studio:

Microsoft Visual Studio Community 2022
Version 17.3.0 Preview 1.1
VisualStudio.17.Preview/17.3.0-pre.1.1+32519.111
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.3.122.33185
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.3.122.33185
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.3.122.33185
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22115.6
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.11 (4f73250)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Django support   17.0.22115.6
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.22115.6
Profiling support for Python projects.

Python with Pylance   17.0.22115.6
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2222701+751db1ebea5e6a9ecc7fa57fe447180422afa610
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10420.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22178.3+6da0245a7ce4bb8483b8d1f2993c8ecaea967ad9
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.151 (d17-3-p1.1@5a59bfa)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.33 (remotes/origin/d17-3-1@9c0d11a29)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   12.3.99.58 (main/64b22fc)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/release/6.0.3xx@2a882d2d
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fc3c2ac

**Comment by pictos** [comment] 2022-05-25 15:41
@sam-wheat if you try to build and deploy does it work?

**Comment by brminnick** [comment] 2022-05-25 16:01
Just FYI (I don't think this is the root cause of your issue)

You do not need to call `.UseMauiCommunityToolkitCore()` when calling `UseMauiCommunityToolkit()`. 

`UseMauiCommunityToolkit()` calls `UseMauiCommunityToolkitCore()` for you. 

Here's how the `CreateBuilder()` code should look:

```cs

var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.UseMauiCommunityToolkit()
			.UseMauiCommunityToolkitMarkup()

```

**Comment by brminnick** [comment] 2022-05-25 21:03
Is anyone able to reproduce this error?

**Comment by pictos** [comment] 2022-05-25 22:49
@brminnick it works on my machine...

@sam-wheat 
Could you attach a small repro?

**Comment by sam-wheat** [comment] 2022-05-26 01:39
This project is very early in development and will not run even if you build it. 

https://github.com/leaderanalytics/LeaderPivot.XAML.MAUI

![Capture](https://user-images.githubusercontent.com/16885210/170397317-9cbb2b4f-9058-4520-8ceb-bada7ddc1842.PNG)

**Comment by pictos** [comment] 2022-05-26 02:58
@sam-wheat as pointed out by my good friend @brminnick you need to have some C# code in your project in order to our custom `xml-schema` you have it in the `MauiProgram` class inside the `LeaderPivot.XAML.MAUI.Host` project. But you don't have it in the `LeaderPivot.XAML.MAUI` project.

To solve the issue, you need to call some API from `CommunityToolkit.MAUI` in C# or not use the custom `xml-schema`. If you want to use the C# code, something like `_ = new Snackbar();` should do the job.

After adding the C# reference I couldn't reproduce the error anymore (for MCT)
![image](https://user-images.githubusercontent.com/20712372/170406540-ca217a1d-395d-4216-b9a4-f13d35b575e4.png)

**Comment by sam-wheat** [comment] 2022-05-26 14:42
@pictos Sorry I don't completely understand your last post.  

I took a stab and added `Snackbar z = new Snackbar();` to the constructor of `LeaderPivotControl` in the library project.  That didn't work so I added same to `MauiProgram.CreateMauiApp` in host project.  Still no luck.

> or not use the custom xml-schema

What is the custom xml-schema?

**Comment by pictos** [comment] 2022-05-26 15:07
@sam-wheat can you push your changes? That way I can take a look and see what's going on

**Comment by pictos** [comment] 2022-05-26 16:51
@sam-wheat I'll take a look later

**Comment by pictos** [comment] 2022-05-27 22:12
@sam-wheat just tried your last sample it builds here. Please make sure that you've all the latest bits from VS and .NET MAUI
![image](https://user-images.githubusercontent.com/20712372/170795356-cdf18057-66ae-480b-90a3-a48d6cddf17b.png)

**Comment by sam-wheat** [comment] 2022-05-27 23:07
Hey Pedro I got the issue solved yesterday, should have told you sorry.  I dropped maui toolkit for now, will reconsider it when I have some time.  I will reach out if I need further assistance.  Thanks much for your help.

**Comment by pictos** [comment] 2022-05-27 23:22
@sam-wheat great! Anything that you need (;

I'll close this issue then.

**Closed by pictos** 2022-05-27 23:22 UTC
Labels: bug, unverified, needs reproduction

**Comment by sam-wheat** [comment] 2022-05-27 23:35
@pictos You may want to post the root cause/fix in case someone else runs into it.

**Comment by brminnick** [comment] 2022-05-28 00:03
> You may want to post the root cause/fix in case someone else runs into it.

@pictos shared the root cause and a fix here: https://github.com/CommunityToolkit/Maui/issues/427#issuecomment-1138094787

**Comment by sam-wheat** [comment] 2022-05-28 00:10
@brminnick  That did not fix it.

**Comment by pictos** [comment] 2022-05-28 00:11
@sam-wheat that is curious, since that fixed for me and other team members wasn't able to reproduce the issue. Anyway, I added more info into the readme that is shipped with the NuGet package. Please open a new issue if you still face any issue (:

**Comment by oclockvn** [comment] 2022-08-06 14:00
i encountered the same issue, so I used clr-namespace instead of schema and it worked

```
xmlns:behaviors="clr-namespace:CommunityToolkit.Maui.Behaviors;assembly=CommunityToolkit.Maui"
```

**Comment by jupagose** [comment] 2022-10-19 18:09
> xmlns:behaviors="clr-namespace:CommunityToolkit.Maui.Behaviors;assembly=CommunityToolkit.Maui"

It worked for me !!!!
