### ISSUE TITLE
[BUG] [MacCatalyst] IconTintColorBehavior Throwing Null Exception

### ISSUE THREAD

**Issue by Bensley96** [CommunityToolkit/Maui#2313] opened 2024-11-05 03:53 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

If you change the image source of an Image on MacCatalyst (and I'm assuming iOS as they share the same behaviour) a null exception is thrown due to what I believe is a race condition.

In the best-case scenario, the image just disappears. In the worst-case scenario, if the exception happens somewhere unhandled, the app will crash.

### Expected Behavior

That when you adjust the image of a button, the image updates and the tint is applied without throwing the null exception and potentially crashing the app.

### Steps To Reproduce

1. Open and run the solution
2. Click Button 1; Observe it disappears and the console shows a null reference
3. Click Button 2; Observe the image source updates correctly

### Link to public reproduction project repository

https://github.com/Bensley96/CommunityToolKit-Maui-Bugs

### Environment

- .NET MAUI CommunityToolkit:9.1.0
- OS: MacOS 15.0.1
- .NET MAUI: 9.0.0-rc.2.24503.2

### Anything else?

You'll notice under the MacCatylst folder i have a SafeIconTintColorBehavior.cs script that has a null check for 'button.currentImage'. The second button uses this script and updates the image correctly.

Curiously in the demo, if you use Shell the image disappears whereas without Shell the exception is catchable.

I have a pull request ready to submit for this bug once this is approved that updates line 101 on 'IconTintColorBehavior.macios.cs' to:

`if (button.ImageView.Image is null || button.CurrentImage is null)
{
	return;
}`

This is the same fix I made to the SafeIconTintcolorBehavior in my project. If this is ok I'll submit the pull request

Thanks,

Bensley

**Comment by brminnick** [comment] 2024-11-05 03:59
Can you reproduce this using .NET 8.0? We don't yet support .NET 9.0.

**Comment by Bensley96** [comment] 2024-11-05 07:24
Was able to reproduce in .NET Version: 8.0.10

**Comment by bijington** [comment] 2024-11-05 09:14
Yes please do submit the pull request

**Comment by vhugogarcia** [comment] 2024-12-18 15:02
Closing this issue since the PR has been merged, and published on Maui Community Toolkit version https://github.com/CommunityToolkit/Maui/releases/tag/9.1.1

**Closed by vhugogarcia** 2024-12-18 15:02 UTC
Labels: bug, unverified
