### ISSUE TITLE
[Bug] Popout displays again on right click UWP

### ISSUE THREAD

**Issue by gktval** [CommunityToolkit/Maui#568] opened 2022-08-25 15:15 UTC
### Description

After a popup is initially shown, interacted with, and closed, the popup will reappear when the user right clicks anywhere on the previous page.

### Code
Here is applicable code for displaying and closing a popup:

```public class PopupNavigation
    {
        private static Page _page;
        private Stack<Popup> _popupStack;
        public static PopupNavigation Instance { get; private set; }

        public  PopupNavigation(Page mainPage)
        {
            _popupStack = new Stack<Popup>();
            _page = mainPage;
            Instance = this;
        }

        public async Task<bool> PushAsync(Popup popup)
        {
            _popupStack.Push(popup);
            popup.CanBeDismissedByTappingOutsideOfPopup = false;
            var result = await _page.ShowPopupAsync(popup);
            if (result is bool boolResult)
                return boolResult;
            else
                return false;
        }

        public void Pop()
        {
            Popup popup = _popupStack.Pop();
            popup.Close();
        }

        internal static void Initialize(ContentPage mainPage)
        {
            _page = mainPage;
        }
    }
```

### Steps to Reproduce

1. Open the popup
2. Close the popup
3. Right click anywhere on the page after the popup closes

### Expected Behavior
I expect the popup to remained closed and only display again when ```await _page.ShowPopupAsync(popup);``` code is ran again.

### Actual Behavior
The popup displays again after ```popup.Close();``` was performed and the user right clicks.

**Comment by VladislavAntonyuk** [comment] 2022-08-26 16:35
duplicate of https://github.com/CommunityToolkit/Maui/issues/462

**Comment by u1-kino** [comment] 2022-09-08 05:55
@VladislavAntonyuk   @gktval 
With the following countermeasure code, the popup is no longer displayed on right click.
The point is to assign null to the ContextFlyout property after ShowPopupAsync.

```
      var result = await _page.ShowPopupAsync(popup);
      if (result is bool boolResult)
            return boolResult;
      else
            return false;

#if WINDOWS
       var mauiPopup = (CommunityToolkit.Maui.Core.Views.MauiPopup)popup.Handler?.PlatformView;                    
       var panel = (Microsoft.Maui.Platform.ContentPanel)mauiPopup.Target;
       panel.ContextFlyout = null;  // ★
       
       //  or  
      //var pagePanel = (Microsoft.Maui.Platform.ContentPanel)_page.Handler?.PlatformView;
      //pagePanel.ContextFlyout = null;     
#endif
```

**Closed** 2022-09-10 04:50 UTC
Labels: bug, unverified
