### ISSUE TITLE
[Proposal] CameraView

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#106] opened 2021-09-28 02:19 UTC
# CameraView

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
  * [ ] iOS Support
  * [ ] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [ ] Unit Tests: Not Started
* [ ] Sample: Not Started
* [ ] Documentation: Not Started

## Summary
[summary]: #summary

The CameraView control enables the user to display a preview of the camera output. In addition, it can take photos or record videos. The CameraView also offers the options you would expect to support taking photos and recording videos such as turning the flash on or off, saving the captured media to a file, and offering different hooks for events

## Detailed Design
[design]: #detailed-design

### CameraView.shared.cs

```cs
public class CameraView : View
{
  public static readonly BindableProperty IsBusyProperty;
  public static readonly BindableProperty IsAvailableProperty;
  public static readonly BindableProperty CameraOptionsProperty;
  public static readonly BindableProperty CaptureModeProperty;
  public static readonly BindableProperty VideoStabilizationProperty;
  public static readonly BindableProperty FlashModeProperty;
  public static readonly BindableProperty ZoomProperty;
  public static readonly BindableProperty MaxZoomProperty;
  
  public event EventHandler<bool>? OnAvailable;
  public event EventHandler<MediaCapturedEventArgs>? MediaCaptured;
  public event EventHandler<string>? MediaCaptureFailed;
  
  public ICommand? ShutterCommand { get; }
  
  public bool IsBusy { get; set; }
  public bool IsAvailable { get; set; }
  public CameraOptions CameraOptions { get; set; }
  public CameraCaptureMode CaptureMode { get; set; }
  public bool VideoStabilization { get; set; }
  public CameraFlashMode FlashMode { get; set; }
  public double Zoom { get; set; }
  public double MaxZoom { get; set; }
  
  public void Shutter();
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="MyLittleApp.MainPage">

     <StackLayout>

        <xct:CameraView
                x:Name="cameraView"
                CaptureMode="Video"
                FlashMode="On"
                MediaCaptured="CameraView_MediaCaptured"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand" />

    </StackLayout>

</ContentPage>
```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
    Content = new CameraView
    {
      CaptureMode = CameraCaptureMode.Video,
      FlashMode = CameraFlashMode.Off,
    }.FillAndExpand()
     .Invoke(cameraView => cameraView.MediaCaptured += HandleMediaCaptured);
  }

  void HandleMediaCaptured(object? sender, MediaCapturedEventArgs e)
  {
    //...
  }
}
```

**Comment by jfversluis** [comment] 2021-09-29 12:41
We might want to check this with @Redth who has https://github.com/Redth/BigIslandBarcoding/tree/refactor-cameraview with a CameraView and additional barcode scanning (latter in a separate package) he wishes to donate

**Comment by jfversluis** [comment] 2021-10-05 09:51
Taking in regard the above comment, I definitely thing we should have this, but it will need work one way or the other.

**Comment by Redth** [comment] 2021-10-05 11:21
Yeah we can move my barcode stuff over. The question is how to do it for the android dependencies. Split into another nuget?

**Comment by Axemasta** [comment] 2022-01-18 14:20
The XCT version of this control suffered from a niche bug on Android where certain devices could not display the selfie preview. This was addressed in [#1780](https://github.com/xamarin/XamarinCommunityToolkit/pull/1780).

The root issue of the bug was caused by using an older implementation for setting the preview surface which can be seen in deprecated google samples ([repo](https://github.com/googlearchive/android-Camera2Basic), [code](https://github.com/googlearchive/android-Camera2Basic/blob/4cc1c3e219d8d168b7893f7a6b2b348740679e5a/Application/src/main/java/com/example/android/camera2basic/Camera2BasicFragment.java#L384)). The up to date [Camera2 samples](https://github.com/android/camera-samples) use different ways of setting the [preview size](https://github.com/android/camera-samples/blob/b814a4523fecbf0ed6c361830ed04c1b33cda5e1/Camera2Basic/app/src/main/java/com/example/android/camera2/basic/fragments/CameraFragment.kt#L166) and there are other xamarin controls which work with affected phones due to an alternate implementation using [preview builder](https://github.com/JimmyPun610/BarcodeScanner.XF/blob/dd8c0d099b4c155a9aefd2accb92afe28affcf51/GoogleVisionBarCodeScanner/Android/Renderer/CameraViewRenderer.cs#L88).

Whilst its fresh in my mind I thought I'd mention it so that the control is as compatible with as many devices as possible 😊

**Comment by curelom** [comment] 2022-03-12 19:47
The ability to compress video is greatly needed.

**Comment by brminnick** [comment] 2022-05-02 19:50
Closing in favor of duplicate proposal #259

**Closed** 2022-05-02 20:20 UTC
Labels: proposal
