### ISSUE TITLE
[BUG] StatusBarBehavior StatusBarColor DynamicResource binding not working

### ISSUE THREAD

**Issue by Cybrosys** [CommunityToolkit/Maui#1056] opened 2023-03-01 23:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I am trying to bind the `StatusBarColor` of `StatusBarBehavior` using a `DynamicResource`-binding, to support theming:

```
<ContentPage.Behaviors>
    <toolkit:StatusBarBehavior StatusBarColor="{DynamicResource Tertiary}" />
 </ContentPage.Behaviors>
```

This results in the StatusBarColor being white/transparent instead of the Tertiary color.

Using a `StaticResource`-binding works as expected.

I have only tested this on Android but @brminnick was able to reproduce it on iOS.

### Expected Behavior

The status bar color should reflect the color referenced by the `DynamicResource`-binding.

### Steps To Reproduce

1. Open and run the sample on Android and iOS

### Link to public reproduction project repository

https://github.com/Cybrosys/Sandbox/tree/master/MauiAppStatusBarColorDynamicResource

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.0.0
- OS: Android Emulator running Android 13.0 - API 33
- .NET MAUI: 7.0.59/7.0.100         VS 17.5.33424.131
```

**Comment by Cybrosys** [comment] 2023-03-03 08:16
Out of curiosity, who would own the dynamic resource binding, the page or the behavior itself? Just to get a hint at where to begin looking/debugging this.

Could the issue I am experiencing be a core issue in MAUI related to bindings, behaviors and/or dynamic resources (there are issues reported related to DynamicResource in .NET 7 MAUI that people claim works in .NET 6)?

I did a test where I copied the `StausBarBehavior` code into my `MainPage` and in the ctor set the binding using the `SetDynamicResource` method:
`SetDynamicResource(StatusBarColorProperty, "Tertiary");`

This resulted in the expected behavior, but also negated the purpose of using `Behavior`s.

The method `SetDynamicResource` is exposed/made public on `Element` but appears to come from `BindableObject`. The method `SetDynamicResource` is not exposed through `Behavior` but `Behavior` does inherit from `BindableObject`.

Thus back to my original question and some more:
- Who would "own" the binding?
  - Looks like each `BindableObject` would own their own bindings?
- Who would create the binding when defined in XAML, is it the XAML parser?

If I put a breakpoint inside the `StatusBarBehavior.StatusBarColorProperty` (not the one I made), it is only accessed by itself in `OnAttachedTo`. So maybe this is a XAML parser issue and/or some check that says that this type of binding is not valid?

**Comment by pictos** [comment] 2023-03-03 15:00
@Cybrosys the Behaviors, since XF, don't inherit the BindingContext of the AssociatedObject, so if you don't set that manually, the BindingContext will be null.

**Comment by Cybrosys** [comment] 2023-03-03 22:00
> @Cybrosys the Behaviors, since XF, don't inherit the BindingContext of the AssociatedObject, so if you don't set that manually, the BindingContext will be null.

I have tried assigning a `BindingContext` to the `StatusBarBehavior` and that works for "normal" bindings "{Binding ...]" to a property on the owning `ContentPage` (view model binding, or what you want to call it). I have however not gotten the `DynamicResource` binding to work in the same way

**Comment by pictos** [comment] 2023-03-03 22:03
@Cybrosys I've no clue if Behaviors do support DynamicResources... I would say they should, but I'm not sure. Maybe you can rise this question on Maui's repo.

**Comment by Cybrosys** [comment] 2023-03-04 00:17
Started a discussion in the main MAUI repo:
https://github.com/dotnet/maui/discussions/13691

**Comment by brminnick** [comment] 2023-03-06 16:46
`Behavior` in .NET MAUI does not have support for `ResourceDictionary` and thus do not support `StaticResource` or `DynamicResource`

In .NET MAUI, [`Behavior` inherits from `BindableObject`](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/Interactivity/Behavior.cs#L10).

For a class to support `ResourceDictionary`, it needs to either inherit from [`VisualElement` where `public ResourceDictionary Resources { get; set; }` exists](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/VisualElement.cs#L770), or implement [`IResourceProvider`](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/IResourcesProvider.cs).

Closing because this is not a bug specific to the .NET MAUI Community Toolkit.

**Closed by brminnick** 2023-03-06 16:46 UTC
Labels: bug

**Comment by Cybrosys** [comment] 2023-03-06 20:31
Thank you for the information @brminnick. 

I would however like to mention that it does work with `StaticResource`:
![image](https://user-images.githubusercontent.com/2155376/223221585-e73e50b3-209e-41a1-9847-c156c88fe5e8.png)

`StaticResourceExtension` has quite a lot more code compared to `DynamicResourceExtension` where the static one has several fallbacks to resolving a value:
https://github.com/dotnet/maui/blob/main/src/Controls/src/Xaml/MarkupExtensions/StaticResourceExtension.cs

https://github.com/dotnet/maui/blob/main/src/Controls/src/Xaml/MarkupExtensions/DynamicResourceExtension.cs

But, as you said, it is not an issue with MCT but rather with MAUI.

Going back to the mention that the solution is to implement `IResourceProvider`, would it really be just that simple? I would guess that something has to feed it a `ResourceDictionary` instance. Maybe the `DynamicResourceExtension` class would be the one to do that?

**Comment by pictos** [comment] 2023-03-06 22:05
@Cybrosys I agree that would be a great addition, please open an issue on .NET MAUI repo asking for it

**Comment by Cybrosys** [comment] 2023-03-06 22:13
> @Cybrosys I agree that would be a great addition, please open an issue on .NET MAUI repo asking for it

https://github.com/dotnet/maui/issues/13724

**Comment by brminnick** [comment] 2023-03-06 22:59
Thanks @Cybrosys! 

I agree with @pictos. We get a lot of Issues opened here in the `CommunityToolkit.Maui` repo when things like DynamicResources and Bindings don't work as expected for `Behavior`s  because of this.
