### ISSUE TITLE
SetFocusOnEntryCompletedBehavior not focusing to next element in Android

### ISSUE THREAD

**Issue by fmir864** [CommunityToolkit/Maui#708] opened 2022-10-22 15:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The focus not shifted to referenced control when tap next on Android emulator.

### Expected Behavior

The focus should be shifted to referenced control

### Steps To Reproduce

1. Create two entries
2. Set SetFocusOnEntryCompletedBehavior on first entry and reference the second entry as next element
3. Set Return type as next on first entry

```
                 <Entry
                    Text="{Binding Username, Mode=TwoWay}"
                    Placeholder="Enter Username"
                    Keyboard="Text"
                    ClearButtonVisibility="WhileEditing"
                    ReturnType="Next"
                    toolkit:SetFocusOnEntryCompletedBehavior.NextElement="{Reference PasswordEntry}">
                    <Entry.Behaviors>
                        <toolkit:EventToCommandBehavior
                            EventName="TextChanged"
                            Command="{Binding ValidateEditorsCommand}" />
                    </Entry.Behaviors>
                </Entry>

                <Entry
                    x:Name="PasswordEntry"
                    IsPassword="True"
                    Text="{Binding Password, Mode=TwoWay}"
                    Placeholder="Enter Password"
                    Keyboard="Text"
                    ClearButtonVisibility="WhileEditing"
                    ReturnType="Done"
                    ReturnCommand="{Binding LoginCommand}">
                    <Entry.Behaviors>
                        <toolkit:EventToCommandBehavior
                            EventName="TextChanged"
                            Command="{Binding ValidateEditorsCommand}" />
                    </Entry.Behaviors>
                </Entry>
```

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample

### Environment

```markdown
- .NET MAUI CommunityToolkit:1.3.0
- OS:Windows 11 22000.1098
- .NET MAUI:6.0.541
```

### Anything else?

The issue exists in Android platform, in my emulator Pixel 5 API 30 but its working as a Windows app. The issue also reproducible in sample app [here]
(https://github.com/CommunityToolkit/Maui/tree/main/samples/CommunityToolkit.Maui.Sample);

Also the focus shifting when pressed enter key but emulator keyboard next doesn't shift the focus.

**Comment by pictos** [comment] 2022-10-22 23:09
Hey @fmir864, thanks for your report. I tried, on my end implement the `Completed` event in code-behind and that doesn't trigger at all, so looks like the issue is on .NET MAUI. Can you check that as well?

**Comment by pictos** [comment] 2022-10-22 23:19
Yeap, I can confirm. Isn't on us
- https://github.com/dotnet/maui/issues/9796

**Comment by XJonOneX** [comment] 2022-10-31 01:53
It's definitely .NET MAUI. If the ReturnType on the Entry is set to anything but Done, SetFocusOnEntryCompletedBehavior won't work, in addition to ReturnCommand and the Completed event.

**Comment by jacobkktan** [comment] 2022-11-08 03:59
Looks like there's an issue with windows too, I believe `SetFocusOnEntryCompletedBehavior` is triggered when `Complete` event is fired. On windows that event is not triggering when `Tab` key is pressed (tested), only fired when user clicks `Enter` key. I have not tried it on Mac yet (since I'm working on a windows machine now).

**Comment by vhugogarcia** [comment] 2023-10-31 18:35
@brminnick since this is an active bug on the .NET MAUI repository as Pedro pointed it here: https://github.com/dotnet/maui/issues/9796 and it is not on us, should we close this?

Regards,
Victor

**Comment by brminnick** [comment] 2023-10-31 18:37
Closing. Bug confirmed in .NET MAUI https://github.com/dotnet/maui/issues/9796

**Closed by brminnick** 2023-10-31 18:37 UTC
Labels: bug, blocked
