### ISSUE TITLE
Icon Tint Color Behavior does not color images on IOS under certain conditions

### ISSUE THREAD

**Issue by SteveJML** [CommunityToolkit/Maui#1139] opened 2023-04-13 16:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I am trying to color icons at runtime in a collectionview based on AppthemeBinding using Maui Community Toolkit IconTint Behavior. 
The process in the content page loops through each process which queries a server database, once completed the egg timer icon gets replaced with a tick icon based on the response from the server.

For testing purposes i'm using an Await.Delay(500) to simulate the server trip, this is mostly functioning correctly with the exception that the icon tint behavior does not get applied and retains its original color, this is only happening on IOS, on Android it works perfectly. This has also happened on several other views where i have an Await.Delay(), as soon as i remove this, the behavior gets applied. The data is in an observable collection within a collectionview.

Also, if I put an Await.Delay before using Shell.Current.GoToAsync, the icons on my custom navigation bar retain their original color.

### Expected Behavior

I'm expecting the icons to adopt the new color like they do when running on android.

### Steps To Reproduce

Create a Content Page, in XAML

 <Image Source="check" WidthRequest="80" HeightRequest="80" >
        <Image.Behaviors>
            <mct:IconTintColorBehavior TintColor="Orange" />
        </Image.Behaviors>
    </Image>

In the code behind or VM:
  await Task.Delay(1000);
  await Shell.Current.GoToAsync(nameof(Test_landing));

Run on IOS, the icon retains it's original color, run on Android and it adopts the new color

Remove the await Task.Delay and it works fine. I'm using await delay to allow a popup page that I have close then displaying a new page based on the selection.

### Link to public reproduction project repository

https://github.com/SteveJML/Tint-Image-Test

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

### Anything else?

Images in a collection view cannot be coloured per item based on the binding. I have images that I wanted to color based on their extension, ie .pdf, docx etc.

**Comment by Dokug** [comment] 2023-04-15 08:53
Since the toolkit update to version 5.1.0 the IconTintColorBehaviour stopped working completely for me (on iOS at least).
Even a directly supplied color without any binding does not work any more..

**Comment by pictos** [comment] 2023-04-15 14:04
@Dokug can you provide a repro? I tested on `main` branch and everything the behavior is working as expected

**Comment by pictos** [comment] 2023-04-16 02:46
@SteveJML looks like this is more a Maui issue than us... The workaround is to add the Behavior on the Loaded event on the page, just like this:

```csharp
public Test_Image()
    {
        InitializeComponent();

        Loaded += (_, __) =>
        {
            this.img.Behaviors.Add(new IconTintColorBehavior()
            {
                TintColor = Colors.Fuchsia
            });
        };
    }
```

WHen I did that change it worked 100% of the time

**Comment by SteveJML** [comment] 2023-04-16 10:00
> 

Thanks for the workaround, this works if the xaml is connected to the code behind, I have a custom toolbar which is just the properties in a cs file inheriting from ContentView, I then use control templates depending on which UI I need, the templates reside in a resource dictionary, I'm not sure how I will reference the images, any ideas?

Also, if this is a MAUI issue, should I raise a bug report on their GitHub?

**Comment by pictos** [comment] 2023-04-16 22:20
@SteveJML if you can rise the issue there, it will be great. The root cause is that `img.Loaded` didn't trigger, so the IconTintColor behavior will not work

**Comment by fischberg** [comment] 2023-05-02 22:07
I'm having an issue only on iOS that I believe is a symptom of the same problem. I have a page containing many icons buried in a CollectionView each icon of which is tinted differently based on the AppThemeBinding. I add to that CollectionView from another page. When I return to the original page, the icons in the new items in the CollectionView aren't tinted. How can I apply the the IconTintColorBehavior to all icons in every item in the CollectionView?

**Comment by vhugogarcia** [comment] 2023-11-28 23:01
Hello @pictos ,

I'm unable to reproduce the issue on .NET MAUI 8 and using the latest version of the MAUI Community Toolkit 7.0.0. Please find below a video I recorded trying to reproduce the issue. I updated the sample project uploaded by @SteveJML to .NET MAUI 8 and added `AppThemeBinding` to the `IconTintColorBehavior`, and finally added/removed the `Task.Delay(1000)` before navigating, and all is looking OK to me in any scenario.

```xml
<Image Source="close.png"  HeightRequest="80" WidthRequest="80" >
          <Image.Behaviors>
              <mct:IconTintColorBehavior TintColor="{AppThemeBinding
                                                    Light=Red,
                                                    Dark=Orange}" />

          </Image.Behaviors>
    </Image>
```
https://github.com/CommunityToolkit/Maui/assets/1047398/660e26be-bcc3-4064-9e15-1805accdd538


@pictos do you know if I'm missing something on the testing, or do you think this issue is already fixed by the tests I ran above?

cc: @brminnick

**Comment by pictos** [comment] 2023-11-28 23:25
Let's close this issue then, if anyone faces it they can open a new issue

**Closed by pictos** 2023-11-28 23:25 UTC
Labels: bug
