### ISSUE TITLE
[BUG] System.ArgumentException: '1' cannot be greater than 0.

### ISSUE THREAD

**Issue by BaY1251** [CommunityToolkit/Maui#2071] opened 2024-07-30 07:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

   When nothing in UniformItemsLayout(et. BindableLayout.ItemsSource set to null), an exception will throw.

at System.Math.ThrowMinMaxException[T](T min, T max)
   at CommunityToolkit.Maui.Core.Layouts.UniformItemsLayoutManager.GetColumnsCount(Int32 visibleChildrenCount, Double widthConstraint)
   at CommunityToolkit.Maui.Core.Layouts.UniformItemsLayoutManager.Measure(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Platform.MauiPanel.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)

### Expected Behavior

NO exception 

### Steps To Reproduce

Open ToolkitIssue2071\ ToolkitIssue2071.sln
Click 'Click me' 

### Link to public reproduction project repository

https://github.com/BaY1251/MauiDebug.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:9.0.2
- OS:-
- .NET MAUI:8.0.61
```

**Comment by BaY1251** [comment] 2024-08-01 06:31
@pictos I uploaded a repository, and edited description

**Comment by VladislavAntonyuk** [comment] 2024-08-03 14:59
duplicate of #1816

**Comment by vhugogarcia** [comment] 2024-08-16 20:29
Thanks @VladislavAntonyuk  for finding the duplicate.

I'm closing this issue since we can follow up on the original issues.

**Closed by vhugogarcia** 2024-08-16 20:29 UTC
Labels: bug, unverified
