### ISSUE TITLE
[BUG] MediaElement sounds choppy when playing in background on Android

### ISSUE THREAD

**Issue by andyfmking** [CommunityToolkit/Maui#1171] opened 2023-05-03 06:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When playing video or audio using the CommunityToolkit MediaElement, pressing the home button on Android, or when switching app while MediaElement is playing, the audio does not play smoothly (choppy sound).
When we return to our app with the MediaElement, it sounds okay again until when we switch to a different app.

### Expected Behavior

The audio should sound smooth even when we switch to a different app or when we are on the launcher while our app plays the media file using MediaElement.

### Steps To Reproduce

1. Create a new Maui App.
2. Add and initialize CommunityToolkit.Maui.MediaElement on the project.
3. Create a page with MediaElement that has an audio or video source.
4. Play the Media
5. Switch to a different app or to Home (Launcher) while MediaElement is playing

### Link to public reproduction project repository

Coming soon

### Environment

```markdown
- .NET MAUI CommunityToolkit:5.1.0
- .NET MAUI CommunityToolkit:1.0.2
- OS:Android 13.0
- .NET MAUI:7.0.70.11
```

**Comment by jfversluis** [comment] 2023-07-04 10:43
I wonder if the bug for this one is that it sounds choppy in the background or that it plays in the background at all 😅  I don't think that is intended behavior.

**Comment by ne0rrmatrix** [comment] 2023-09-11 01:51
I have had it play in background just fine. It was not intended and a bug in the app I was working on though. I have had audio that was choppy but that was in an emulator where hardware acceleration in windows was not working on android emulator. I have had zero issues on modern devices but my some older samsung phones have had issues playing in background. I imagine in those cases it is simply a matter of resources and/or lack there of.

**Comment by ne0rrmatrix** [comment] 2024-06-18 03:15
@vhugogarcia this is an old issue and we have had zero replication in recent versions of android. I use android media element extensively on both physical devices and emulators with zero issues.

**Comment by vhugogarcia** [comment] 2024-06-18 04:22
Thanks @ne0rrmatrix for the report. I'm closing this issue, and we can reopen it if needed.

**Closed by vhugogarcia** 2024-06-18 04:22 UTC
Labels: bug, unverified, 📽️ MediaElement
