### ISSUE TITLE
[Bug] Edit And Continue doesn't work as soon as the CommunityToolkit is installed

### ISSUE THREAD

**Issue by cargnel** [CommunityToolkit/Maui#402] opened 2022-05-11 16:32 UTC
### Description

Edit And Continue doesn't work as soon as the CommunityToolkit is installed

### Stack Trace

N/A

### Link to Reproduction Sample

N/A

### Steps to Reproduce

1. Open Visual Studio, create a new MauiApp.
2. Hello World with "click me" button is created.
3. Clicking the button increase the counter and the button text updates accordingly.
4. Under MainPage.xaml.cs, change
`count++;` to
`count+=2;`
5. Saving the page (Hot Reload on file save is checked) and clicking the button, the counter changes adding 2 every time as expected.
5b. stop the debug
6. NuGet - Solution, install CommunityToolkit.Maui 1.0.0-rc3
readme.txt pops up and, under MauiProgram.cs add:
7. `using CommunityToolkit.Maui;` as first row
8. ```
      // Initialise the toolkit
      builder.UseMauiApp<App>().UseMauiCommunityToolkit();
after `var builder = MauiApp.CreateBuilder();` as requested

9. The following new lines appear in .csproj file
```
<ItemGroup>
  <PackageReference Include="CommunityToolkit.Maui" Version="1.0.0-rc3" />
</ItemGroup>
```
10. Debug -> Windows Machine...

11. Repeat action 3 and 4
12. Saving the page (Hot Reload on file save is checked) the following popup appears

```
Hot Reload
Hot Reload can't automatically apply your changes. The app needs to be rebuilt to apply updates
[...]
[Rebuild and Apply Changes] [Continue Editing]

```

### Expected Behavior
Edit And Continue working
### Actual Behavior
Edit And Continue not working
### Basic Information

- Version with issue: 1.0.0-rc3
- Last known good version: 
- IDE: Visual Studio 2022 preview 17.3 Preview 1
- Platform Target Frameworks: 
  - windows 
- Nuget Packages:
  - Microsoft.Maui.Dependencies 6.0.300-rc.3.5667
  - Microsoft.Maui.Extensions  6.0.300-rc.3.5667
  - Microsoft.Windows.SDK.BuildTools 10.0.22000.194
  - System.Runtime.InteropSerivices.NFloat.Internal 6.01
  - CommunityToolkit (the only one added to the original solution)
- Affected Devices:

### Workaround
Removing the toolkit the issue disappears:
- REMOVE `using CommunityToolkit.Maui;`
- REMOVE
```
// Initialise the toolkit
      builder.UseMauiApp<App>().UseMauiCommunityToolkit();
```
- AND REMOVE
```
<ItemGroup>
  <PackageReference Include="CommunityToolkit.Maui" Version="1.0.0-rc3" />
</ItemGroup>
```

### Reproduction imagery
N/A

**Comment by pictos** [comment] 2022-05-11 16:41
Not sure if this is an issue with us, since we don't do anything fancy on the tooling.
@brminnick @jfversluis can you ask someone at the tooling team?

**Comment by bijington** [comment] 2022-05-11 17:50
Oh I wonder... do source generators play nicely with .NET Hot Reload?

**Comment by cargnel** [comment] 2022-05-11 18:08
> @cargnel did you try with another packages?

I've just tried with Newtonsoft.Json 13.0.1 (without CommunityToolkit ) and EnC works

**Comment by cargnel** [comment] 2022-05-11 18:08
> Just to confirm did you stop the application debugging when adding the NuGet package, then build and run?

Yes

**Comment by pictos** [comment] 2022-05-11 20:26
> > @cargnel did you try with another packages?
> 
> I've just tried with Newtonsoft.Json 13.0.1 (without CommunityToolkit ) and EnC works

I mean, with another package that targets .NET MAUI, like the CommunityToolkit does

**Comment by brminnick** [comment] 2022-05-11 20:31
Try reproducing it with [MR.Gestures v3.0.0-pre1](https://www.nuget.org/packages/MR.Gestures/3.0.0-pre1)

**Comment by cargnel** [comment] 2022-05-11 21:43
> > I mean, with another package that targets .NET MAUI, like the CommunityToolkit does
> 
> Try reproducing it using [MR.Gestures v3.0.0-pre1](https://www.nuget.org/packages/MR.Gestures/3.0.0-pre1)

I tried the [GestureSample](https://github.com/MichaelRumpler/GestureSample) as is and EnC works:
Layout -> Grid Sample (GridXaml.xml) tapping twice on the same cell (TicTacToeViewModel.cs, 50) shows "Field {0}/{1} is already filled.". I changed it to "AAAA Field {0}/{1} is already filled.", pressed "hot reload" and the message is shown es expected.

**Comment by thomiel** [comment] 2022-06-16 19:28
I have spent some hours pinpointing the failing EnC to the MAUI CommunityToolit now. Please just create a project with the default MAUI-app template, add UseMauiCommunityToolkit() to MauiProgram.cs, break at count++, hit the button, and observe a failing EnC. Should be done in three minutes...

**Comment by mikemccaughan** [comment] 2022-06-17 12:20
I've added many, many packages to an WIP project, and wondered which one broke Hot Reload. Now I know. Thank you for this bug report 👍

**Comment by bijington** [comment] 2022-06-17 12:22
> Tested successfully using toolkit v1.0.0 with VS 2022, 17.3.0 Preview 2.0.

Does this mean that you no longer experience the issue?

**Comment by thomiel** [comment] 2022-06-29 13:01
Just tested again with Preview 2.0 (Android Emulator) and EnC failed. Then removed package and App initialization; result: failed.

**Comment by drasticactions** [comment] 2022-06-30 13:28
@cargnel (And those experiencing this) I would file this to VS Feedback (https://developercommunity.visualstudio.com/home)

The likelyhood of this being specific to this package is, as far as I can see, _very_ slim. They are not doing anything different that would cause Hot Reload to break (Also note that EnC and C# Hot Reload are not _exactly_ the same mechanics under the covers for different platforms and runtimes.). I don't think this would ever get fixed in this repo, it needs to be looked at in Visual Studio.

**Comment by brminnick** [comment] 2022-07-15 17:45
Confirmed EnC is working
https://github.com/CommunityToolkit/Maui/discussions/496#discussioncomment-3158586

**Closed by brminnick** 2022-07-15 17:45 UTC
Labels: bug, unverified
