### ISSUE TITLE
[BUG] Referencing Community Toolkit in shared library causes warnings

### ISSUE THREAD

**Issue by jenscski** [CommunityToolkit/Maui#618] opened 2022-09-09 06:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm creating a .NET MAUI application, where I have a library with ui elements, and I want to use Community Toolkit in this library.

When I'm referencing this library with the .NET MAUI App, I get several warnings.

```
Warning	CS0436	The type 'ColorAnimationExtensions_Button' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Button' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs	41	Active
Warning	CS0436	The type 'ColorAnimationExtensions_DatePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_DatePicker' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs	41	Active
Warning	CS0436	The type 'ColorAnimationExtensions_Editor' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Editor' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs	41	Active
Warning	CS0436	The type 'ColorAnimationExtensions_Entry' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Entry' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs	41	Active
Warning	CS0436	The type 'ColorAnimationExtensions_Label' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Label' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs	41	Active
Warning	CS0436	The type 'ColorAnimationExtensions_Picker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Picker' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs	41	Active
Warning	CS0436	The type 'ColorAnimationExtensions_RadioButton' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_RadioButton' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs	41	Active
Warning	CS0436	The type 'ColorAnimationExtensions_SearchBar' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_SearchBar' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs	41	Active
Warning	CS0436	The type 'ColorAnimationExtensions_TimePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_TimePicker' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs'.	CTMShareLib (net6.0-android)	***\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs	41	Active
```

### Expected Behavior

No warnings when compiling

### Steps To Reproduce

Open and build solution, warnings should appear

### Link to public reproduction project repository

https://github.com/jenscski/CTMShareLib

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.2.0
- OS: Edition	Windows 10 Pro 21H2 19044.1949
- .NET MAUI: 6.0.486
```

**Comment by marcmognol** [comment] 2022-09-09 08:20
Hi, I think it is duplicate of issue #411

**Comment by bijington** [comment] 2022-09-09 08:27
@marcmognol yes it is a duplicate of that. Thanks for finding it.

@jenscski this hasn't been resolved in a public release yet but one should be coming very soon (within the next week I think)

**Closed by bijington** 2022-09-09 08:27 UTC
Labels: bug, unverified

**Comment by jenscski** [comment] 2022-09-09 09:21
Is there a daily build or something of this library?

I checked out the source for CommunityToolkit Maui and built a new local nuget,but I still get the warnings ...

**Comment by bijington** [comment] 2022-09-09 09:34
> Is there a daily build or something of this library?
> 
> I checked out the source for CommunityToolkit Maui and built a new local nuget,but I still get the warnings ...

Yes you should be able to gain access to a preview build based on this article:

https://github.com/CommunityToolkit/Maui/wiki/Preview-Packages

**Comment by jenscski** [comment] 2022-09-12 08:58
I have tested with build from `https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json`, but the latest version is 1.0.0-preview2964, but it's from septemer 10, 2022. Is this newer than 1.2.0 from nuget.org despite its name?

If it's never I'm still getting build errors.
Reproduction repository is updated


```
Rebuild started...
Restored C:\Temp\CTMShareLib\MauiLib1\MauiLib1.csproj (in 164 ms).
1>------ Rebuild All started: Project: MauiLib1, Configuration: Debug Any CPU ------
Restored C:\Temp\CTMShareLib\CTMShareLib\CTMShareLib.csproj (in 348 ms).
1>MauiLib1 -> C:\Temp\CTMShareLib\MauiLib1\bin\Debug\net6.0\MauiLib1.dll
1>MauiLib1 -> C:\Temp\CTMShareLib\MauiLib1\bin\Debug\net6.0-android\MauiLib1.dll
2>------ Rebuild All started: Project: CTMShareLib, Configuration: Debug Any CPU ------
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs(41,89,41,124): warning CS0436: The type 'ColorAnimationExtensions_TimePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_TimePicker' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs'.
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs(41,89,41,120): warning CS0436: The type 'ColorAnimationExtensions_Editor' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Editor' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs'.
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs(41,89,41,120): warning CS0436: The type 'ColorAnimationExtensions_Button' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Button' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\ButtonTextColorTo.g.shared.cs'.
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs(41,89,41,124): warning CS0436: The type 'ColorAnimationExtensions_DatePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_DatePicker' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\DatePickerTextColorTo.g.shared.cs'.
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs(41,89,41,119): warning CS0436: The type 'ColorAnimationExtensions_Entry' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Entry' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EntryTextColorTo.g.shared.cs'.
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs(41,89,41,123): warning CS0436: The type 'ColorAnimationExtensions_SearchBar' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_SearchBar' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\SearchBarTextColorTo.g.shared.cs'.
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs(41,89,41,119): warning CS0436: The type 'ColorAnimationExtensions_Label' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Label' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\LabelTextColorTo.g.shared.cs'.
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs(41,89,41,120): warning CS0436: The type 'ColorAnimationExtensions_Picker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Picker' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\PickerTextColorTo.g.shared.cs'.
2>C:\Temp\CTMShareLib\CTMShareLib\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs(41,89,41,125): warning CS0436: The type 'ColorAnimationExtensions_RadioButton' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_RadioButton' in 'MauiLib1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\RadioButtonTextColorTo.g.shared.cs'.
2>CTMShareLib -> C:\Temp\CTMShareLib\CTMShareLib\bin\Debug\net6.0-android\CTMShareLib.dll
2>Done building project "CTMShareLib.csproj".
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

```

**Comment by 0x0041764C** [comment] 2022-11-27 09:19
Hi @jenscski.

I have the same problem and was able reproduce it with your sample.

My projects are using version 3.0.0 of CommunityToolkit.Maui.
Then I tested the Preview 1.0.0-preview3406 which also has the problem.

A workaround is to ignore that warning CS0436. But that is quite global which might hide other issues down the road.
And the workaround in #411 is also not favorable.

Did you find a solution?

**Comment by jenscski** [comment] 2022-11-28 07:32
Hi @0x0041764C 

No, I found a solution, I'm using the workaround from #411.

@bijington this is not solved in latest release, please reopen.

Maybe I have time later to take a deeper look into the library, but time is a limited resource ...

**Comment by jenscski** [comment] 2022-11-30 07:28
Repro updated to NET 7 & CommunityToolkit.Maui 3.0.0, still same warnings!

@bijington
