### ISSUE TITLE
[Popup] ScrollView & Scroll inside of collection view not working on Android

### ISSUE THREAD

**Issue by SamJames101** [CommunityToolkit/Maui#803] opened 2022-12-02 11:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create a popup.
I fetch the item source in the popups view model from an HTTP request to a server.
The collection view however just cuts off at the end regardless if I specify a height or not for the popup.
If I wrap the collectionView in a scroll view I am unable to scroll or if I remove the scroll view the collectionView still does not let me scroll.

It only lets the scroll functionality work once I set a maximum height on collectionView.

(Side note it also cuts off width-wise unless I specify a width for the popup, slightly annoying that it can't work out the size needed based on the screen size and then wrap the text.)

### Expected Behavior

Scroll view or collectionView works when collectionView takes up more space than the popup will allow vertically.

### Steps To Reproduce

1. Create a popup.
2. Create a collectionView that takes up more space than the popup allows.

### Link to public reproduction project repository

https://github.com/SamJames101/CommunityToolKitPopupScrollingIssue.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

**Comment by VladislavAntonyuk** [comment] 2022-12-02 21:04
What I can definitely say, you don’t need to wrap CollectionView in scroll view, because it is already support scrolling.
As for the Popup size, it needs investigation.
Most likely the problem is in the measurement of the Popup content

**Comment by SamJames101** [comment] 2022-12-05 11:42
@VladislavAntonyuk Yeah I know you don't need a scrollView for a collectionView but wanted to make sure I put that so people didn't recommend that as a potential workaround.

**Comment by shikha-shriya** [comment] 2023-01-13 09:39
I am also facing the same issue. The scroll is not working in popup unless there is MaximumHeight is set.

**Comment by cat0363** [comment] 2023-10-04 04:57
This is a workaround, but by changing from VerticalStackLayout to Grid and using the latest version of main, it will work.

    <Grid RowDefinitions="Auto,Auto,*">
        <Label Grid.Row="0" Text=" I am  the title" Margin="15,10,15,0" FontSize="21" FontAttributes="Bold" HorizontalTextAlignment="Start" VerticalOptions="Center"/>
        <Label Grid.Row="1" Text="I am the subtitle and in fact may take up more than one line if I wrapped, but I only wrap if I am given a size" Margin="15,10,5,0" FontSize="18"  AutomationProperties.IsInAccessibleTree="True" LineBreakMode="WordWrap"/>
        <CollectionView Grid.Row="2" ItemsSource="{Binding BackupDataList, Mode=TwoWay}" Margin="10" HorizontalOptions="FillAndExpand" VerticalScrollBarVisibility="Always">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*"/>
                            <ColumnDefinition Width="Auto"/>
                        </Grid.ColumnDefinitions>

                        <Label Grid.Column="0" Text="{Binding Name}" Margin="10" LineBreakMode="WordWrap"/>
                        <RadioButton VerticalOptions="CenterAndExpand" BorderColor="Black" Grid.Column="1" IsEnabled="True" IsChecked="{Binding IsSelected, Mode=OneWay}" />
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>        
    </Grid>

https://github.com/CommunityToolkit/Maui/assets/125236133/614ae6aa-94ba-4d99-a4ec-f96031af942a

**Comment by vhugogarcia** [comment] 2023-10-31 19:07
@SamJames101 I have faced this issue in the past and not only within the Popup, but also on the normal pages in .NET MAUI. There is an active issue on the MAUI repository where other users also face the same issue with the CollectionView. This is indeed a .NET MAUI issue, and it is not related a Community Toolkit issue.

The workaround our friend mentioned by using **Grids** is perfectly fine and performant, in fact I am also using Grids on my UI apps when rendering CollectionViews.

Here are few issues reported in .NET MAUI about the issue with VerticalStackLayout, so you can follow up on those:

- https://github.com/dotnet/maui/issues/18207
- https://github.com/dotnet/maui/issues/15148

@brminnick Based on the information shared above, I think we can close this ticket, since this is not a bug specific for the Popup.

**Closed** 2023-11-28 23:10 UTC
Labels: bug, unverified
