### ISSUE TITLE
MAUI Community Toolkit Popup Background Is Not Transparent

### ISSUE THREAD

**Issue by mattleibow** [CommunityToolkit/Maui#899] opened 2023-01-16 15:29 UTC
---
**Issue moved from dotnet/maui#12654**
- Please respond to @vsfeedback.

---

_From @vsfeedback on Friday, January 13, 2023 7:08:52 PM_

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-Community-Toolkit-Popup-Background-/10191178)._

---
I have two issues concerning the MAUI Community Toolkit Popup page on iOS:

1. Popup background is not transparent on iOS it shows blurry translucent area, I need to be able to see the contents of the page behind the popup page, I tried everything to make the blurry part of the page fully transparent with no luck what so ever.
I tried to modify the PageHandler platform view with everything I couldn't find on how to make the UIViewController transparent but nothing worked.

2. Also I can't get rid of the margin around the popup page on iOS, no matter what page Size I use there is always margin around the page, how can I remove it, I need the popup contents to touch the screen edges.

Below screenshot is what I get when I run it on "iPhone 14 Pro Max iOS 16.0", and its the same on real device as well:

![image](https://user-images.githubusercontent.com/1096616/212772215-4e8fd4e3-429b-4aad-92f1-efa199099568.png)

And I am also attaching the test project I created to show these problems.

**Comment by mattleibow** [comment] 2023-01-16 22:05
From the internal testing team: 

> Reproducible on 17.3.6 using a user-provided Sample project. As users said, I debugged it on Android and Windows machine, and it works fine. But the iOS simulator cannot display the background as transparent. So add the recommend investigation tag. Please help to investigate. Thanks!

![image](https://user-images.githubusercontent.com/1096616/212772281-9dc07b3c-a9e3-4770-b911-2f6357fc0671.png)

**Comment by mattleibow** [comment] 2023-01-16 22:09
@TamerIrdais is this your issue? I am unable to find a sample to test. Not sure where you attached it but if you could re-upload?

**Comment by mattleibow** [comment] 2023-01-16 22:13
This may be the sample from this other issue: https://github.com/CommunityToolkit/Maui/issues/898
 https://github.com/CommunityToolkit/Maui/files/10429707/B389524bfec434cc78c182040a3af7f8c638037812804422574_MauiAppNet7.zip

**Comment by pictos** [comment] 2023-01-17 02:02
Maybe it's fixed by #789

**Comment by TamerIrdais** [comment] 2023-01-17 07:15
> @TamerIrdais is this your issue? I am unable to find a sample to test. Not sure where you attached it but if you could re-upload?

Hello @mattleibow you can use the same sample you mentioned for issue #898 
https://github.com/CommunityToolkit/Maui/files/10429707/B389524bfec434cc78c182040a3af7f8c638037812804422574_MauiAppNet7.zip

I can see above that your testing team was able to reproduce it with my sample and provided the screenshot of how the app looks like in iOS vs Android.

If you still need any more info please let me know.

Some people say it ight be fixed with #789 and they say it should be released in one week.

**Comment by TamerIrdais** [comment] 2023-01-22 06:25
@mattleibow I have replied to your question 5 days ago, why is this issue marked as stale?

**Comment by TamerIrdais** [comment] 2023-01-22 06:43
@mattleibow if you need the sample code for this issue on github and not as zip file you can find it here:

https://github.com/TamerIrdais/MAUI-Community-Toolkit-Popup-Displayed-Out-Window-Bounds-On-MacCatalyst

**Comment by pictos** [comment] 2023-01-23 01:48
@TamerIrdais I believe this is fixed by #789, which should be in our next release. If you see this issue when you update your package to the next release, please reopen this issue.

**Closed by pictos** 2023-01-23 01:48 UTC
Labels: bug
