### ISSUE TITLE
[BUG] TouchBehavior crash 

### ISSUE THREAD

**Issue by eduardoagr** [CommunityToolkit/Maui#1783] opened 2024-03-31 17:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

I have a CollectionView like this

```
<CollectionView
    IsVisible="{Binding isNotBusy}"
    ItemsSource="{Binding CoursesAssigned}">
    <CollectionView.ItemTemplate>
        <DataTemplate x:DataType="model:Course">
            <Border
                Margin="50"
                Stroke="Purple"
                StrokeThickness="1">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="8,8,8,8" />
                </Border.StrokeShape>
                <Border.Behaviors>
                    <mct:TouchBehavior Command="{Binding Path=GoToDetailsCommand, Source={x:RelativeSource AncestorType={x:Type vm:MyCoursesPageViewModel}}}"
                        CommandParameter="{Binding .}"
                        DefaultBackgroundColor="Transparent"
                        HoveredBackgroundColor="CornflowerBlue"
                        PressedBackgroundColor="CornflowerBlue" />
                </Border.Behaviors>`
```

But when I run it, I get the error

`Operation is not valid due to the current state of the object.`

### Expected Behavior

My command is declared in my viewModel

```
 [RelayCommand]
 async Task GoToDetails(Course course) {

     await appService.NavigateTo($"{nameof(MyCoursesDetailPage)}",
         true, new Dictionary<string, object> {
         {"Course", course }
     });
 }
```

So I am expecting my command to go the MyCoursesDetailPage when I click the border

### Steps To Reproduce

1. Create a new Maui project
2. Install the mct (Maui community toolkit)
3. Create some sort of class to represent an object, like fruits. 
4. create a collectionView
5. Create a border
6. attach the Touch behavior to a border

### Link to public reproduction project repository

https://github.com/eduardoagr/TouchBehaviorExample

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS: Windows, Android
- .NET MAUI:
```

**Comment by bijington** [comment] 2024-03-31 17:37
What if you try something like the following:

```xaml 

<CollectionView
    IsVisible="{Binding isNotBusy}"
    ItemsSource="{Binding CoursesAssigned}"
    x:Name="collectionView">
    <CollectionView.ItemTemplate>
        <DataTemplate x:DataType="model:Course">
            <Border
                Margin="50"
                Stroke="Purple"
                StrokeThickness="1">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="8,8,8,8" />
                </Border.StrokeShape>
                <Border.Behaviors>
                    <mct:TouchBehavior Command="{Binding Path=BindingContext.GoToDetailsCommand, Source={x:Reference CollectionView}}"
                        CommandParameter="{Binding .}"
                        DefaultBackgroundColor="Transparent"
                        HoveredBackgroundColor="CornflowerBlue"
                        PressedBackgroundColor="CornflowerBlue" />
                </Border.Behaviors>
```

This provides a name to the CollectionView and then uses that in the Binding

**Comment by eduardoagr** [comment] 2024-03-31 18:30
Already tried and nothing

**Comment by r-work** [comment] 2024-04-01 09:12
Same issue, except I'm adding the touch behavior to a `Frame`.

**Comment by r-work** [comment] 2024-04-01 11:16
Here is a repro:
https://github.com/r-work/TouchBehaviorBug.git

**Comment by Axemasta** [comment] 2024-04-01 13:28
@eduardoagr & @r-work can you have a look at this post from @brminnick on [SO](https://stackoverflow.com/questions/78245724/both-touchbehavior-commandparameter-and-touchbehavior-longpresscommandparamet/78245725#78245725). Here he shows exactly how to set the binding context on the behavior appropriately, I have seen the crashes when not setting it the recommended way too.

I'm currently in the process of updating the MCT samples & documentation to explicitly call this issue out and show the appropriate way to use the behavior, I have put this in my docs pr but the way you should setup the behavior to pass a command is here:
```xaml
<ContentPage x:Name="Page">
    <HorizontalStackLayout HorizontalOptions="CenterAndExpand" VerticalOptions="Center">
        <HorizontalStackLayout.Behaviors>
            <mct:TouchBehavior
                BindingContext="{Binding Source={x:Reference Page}, Path=BindingContext}"
                Command="{Binding IncreaseTouchCountCommand}"
                DefaultAnimationDuration="250"
                DefaultAnimationEasing="{x:Static Easing.CubicInOut}"
                PressedOpacity="0.6"
                PressedScale="0.8" />
        </HorizontalStackLayout.Behaviors>

        <ContentView
            BackgroundColor="Gold"
            HeightRequest="100"
            WidthRequest="10" />
        <Label
            LineBreakMode="TailTruncation"
            Text="The entire layout receives touches"
            VerticalOptions="Center" />
        <ContentView
            BackgroundColor="Gold"
            HeightRequest="100"
            WidthRequest="10" />
    </HorizontalStackLayout>
</ContentPage>
```
The checklist is:

- Put an `x:Name="Page` on your root element (assuming `ContentPage`)
- Set the `BindingContext`: `BindingContext="{Binding Source={x:Reference Page}, Path=BindingContext}"`
- Reference the `Command` normally: `Command="{Binding IncreaseTouchCountCommand}"`

**Comment by eduardoagr** [comment] 2024-04-01 13:55
Why do we have to use a name for the page, I always reference the vm, and that is what I was trying to do

**Comment by eduardoagr** [comment] 2024-04-01 14:00
Why do we have to use a name for the page, I always reference the vm, and that is what I was trying to do 

```

    <CollectionView
        x:Name="ff"
        Margin="20"
        HorizontalOptions="Center"
        ItemsSource="{Binding Students}">
        <CollectionView.ItemTemplate>
            <DataTemplate x:DataType="model:DemyUser">
                <Border
                    Padding="10"
                    StrokeShape="RoundRectangle 8"
                    StrokeThickness="2">
                    <Grid RowDefinitions="20,20">

                        <Label
                            FontAttributes="Bold"
                            Text="{Binding DemyId, StringFormat='Id: {0}'}" />

                        <Label
                            Grid.Row="1"
                            FontAttributes="Bold"
                            Text="{Binding FullName, StringFormat='Name: {0}'}" />

                        <Label
                            Grid.RowSpan="2"
                            FontFamily="Mat"
                            FontSize="Header"
                            HorizontalTextAlignment="End"
                            Text="{x:Static helpers:IconFont.Email}"
                            VerticalTextAlignment="Center">
                            <Label.Behaviors>
                                <mct:TouchBehavior
                                    BindingContext="{Binding Source={x:RelativeSource AncestorType={x:Type vm:MyCoursesDetailPageViewModel}}, Path=BindingContext}"
                                    Command="{Binding ContactCommand}" />
                            </Label.Behaviors>
                        </Label>
                    </Grid>
                </Border>
```

    [RelayCommand]
    async Task Contact(string email) {

        await EmailHelper.OpenEmailClientAsync(email);
    }

**Comment by bijington** [comment] 2024-04-01 17:48
@r-work can you name your `Frame` instead?

**Comment by pictos** [comment] 2024-04-01 21:25
> @r-work can you name your `Frame` instead?

Can you use Border instead? AFAIK `Frame` is kind `compatibility`, in .NET MAUI, and should be replaced by `Border`. From [docs](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/frame?view=net-maui-8.0)

![image](https://github.com/CommunityToolkit/Maui/assets/20712372/05f3465e-7a31-4696-99b8-65c55e20bc64)

**Comment by hansmbakker** [comment] 2024-04-02 08:31
@eduardoagr this is a duplicate of https://github.com/CommunityToolkit/Maui/issues/1781 - @Axemasta is right in https://github.com/CommunityToolkit/Maui/issues/1783#issuecomment-2030510397.

It's a but confusing for existing users of Axemasta's initial port of the TouchEffect or even of `TapGestureRecognizer`. In that regard, it would have been easier if it was implemented as a `GestureRecognizer`, but inheriting from `Behavior` probably brings other advantages.

**Comment by tranb3r** [comment] 2024-04-02 08:44
Not exactly a duplicate.

It seems like setting the BindingContext with RelativeSource does not work. It just crashes.
How do you set the BindingContext to the parent viewmodel using Source (not RelativeSource) when your control xaml is in a separate file?

Also, why do we need to set the BindingContext, when the Command binding defines its own Source or RelativeSource?

**Comment by hansmbakker** [comment] 2024-04-02 11:50
@tranb3r excuse me, I didn't pick up those points.

**Comment by MitchBomcanhao** [comment] 2024-04-02 13:39
I'm not getting crashes, but whenever I set a command like so
`Command="{Binding BindingContext.ToggleCommand, Source={x:Reference Page}}"`
the related pressing actions of the behavior do not function at all. This is weird because the same command referenced via a different control works perfectly, and looking at the sample app (where it seems to work) it also looks the same. so something isn't getting set here, and results in broken stuff.

**Comment by eduardoagr** [comment] 2024-04-02 19:18
I fixed it guys thanks the only problem is that I am using a label with a custom font, so I want to change the text color when hover.

**Comment by Axemasta** [comment] 2024-04-03 10:07
Binding issues will be fixed in the next release, see #1791 for details.

The `TouchBehavior` from this release will inherit the `BindingContext` of the `VisualElement` it is attached to (if it exists). This means it will behave in the same way the XCT effect did & the way my Maui.TouchEffect port did. I believe the change will be hotfixed so it should be available soon!

**Comment by maonaoda** [comment] 2024-04-04 10:36
@Axemasta 
seems that TouchBehavior can`t use TemplateBinding
```
                <ContentPresenter BackgroundColor="#FFFFFF"
                                  Padding="15, 20">
                    <ContentPresenter.Behaviors>
                        <mct:TouchBehavior PressedBackgroundColor="LightGray"
                                           IsEnabled="{TemplateBinding BindingContext.IsSelectable}"
                                           Command="{Binding Source={x:Reference page}, Path=BindingContext.TappedCommand}"
                                           CommandParameter="{TemplateBinding BindingContext}"/>
                    </ContentPresenter.Behaviors>
                </ContentPresenter>
```
unless I change to this:
```
                <ContentPresenter BackgroundColor="#FFFFFF"
                                  BindingContext="{TemplateBinding BindingContext}"
                                  Padding="15, 20">
                    <ContentPresenter.Behaviors>
                        <mct:TouchBehavior PressedBackgroundColor="LightGray"
                                           IsEnabled="{Binding IsSelectable}"
                                           Command="{Binding Source={x:Reference page}, Path=BindingContext.TappedCommand}"
                                           CommandParameter="{Binding}"/>
                    </ContentPresenter.Behaviors>
                </ContentPresenter>
```

I also got the same error:
```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Operation is not valid due to the current state of the object.
[mono-rt]    at Microsoft.Maui.Controls.Binding.ApplyRelativeSourceBinding(BindableObject targetObject, BindableProperty targetProperty, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:line 152
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 26
```

**Comment by Axemasta** [comment] 2024-04-04 20:52
Can everyone please update to [8.0.1](https://github.com/CommunityToolkit/Maui/releases/tag/8.0.1), this release should fix all the issues we are seeing with data binding!

You can migrate normally now, I've added a little XCT to MCT [migration guide](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/behaviors/touch-behavior?tabs=toucheffect-xaml#migrating-from-xamarin-community-toolkit) on the TouchBehavior docs incase it is of use to anyone!

**Comment by maonaoda** [comment] 2024-04-05 00:09
also can`t use TemplateBinding directly under ContentPresenter.

**Comment by Axemasta** [comment] 2024-04-05 10:00
I'm finishing the migration of my app to `TouchBehavior` and the Relative Bindings don't seem to work at all, same crash reported in this thread.

I can work around by referencing the command via an `x:Reference` to the page:
```xml
Command="{Binding Source={x:Reference Page}, Path=BindingContext.FormSelectedCommand}"
```

But its not super convenient, Im not sure why the underlying maui framework is throwing an `InvalidOperationException`...

[This is the method](https://github.com/dotnet/maui/blob/7b27403abb365ee296c225d8e259f5f8b565ea3c/src/Controls/src/Core/Binding.cs#L142) throwing the exception on the maui side, I have no idea where the blame lies for this issue... could it be a maui problem?

**Comment by maonaoda** [comment] 2024-04-05 10:34
which MauiVersion are you using?
I`m using 8.0.20-ci.net8.10420 (Maui)
and 8.0.1 (CommunityToolkit.Maui)。
x:Reference works fine.

**Comment by Axemasta** [comment] 2024-04-05 10:40
> which MauiVersion are you using?

`8.0.14`, the `x:Reference` works for me, I'm talking about the relative binding `Command="{Binding Source={RelativeSource AncestorType={x:Type vm:MyViewModel}}, Path=MyCommand}"` not working.

This is definitely a regression from XCT since my Maui TouchEffect was able to use relative bindings, I noticed this issue when removing my port from my apps.

**Comment by maonaoda** [comment] 2024-04-05 10:50
> 8.0.14, the x:Reference works for me, I'm talking about the relative binding Command="{Binding Source={RelativeSource AncestorType={x:Type vm:MyViewModel}}, Path=MyCommand}" not working.
> 
> This is definitely a regression from XCT since my Maui TouchEffect was able to use relative bindings, I noticed this issue when removing my port from my apps.

Yes, as TemplateBinding does, No issues with Maui TouchEffect

**Comment by MitchBomcanhao** [comment] 2024-04-05 14:42
ugh just got into this RelativeSource crashing issue now while adapting TouchBehavior to my existing project... :(

**Comment by tranb3r** [comment] 2024-04-05 15:18
https://github.com/CommunityToolkit/Maui/issues/1783#issuecomment-2031418276

**Comment by MitchBomcanhao** [comment] 2024-04-05 15:20
not sure what you meant there, @tranb3r  - the binding situation has changed since 8.0.1 was released, but it seems the relative source crashing (in my case when binding a command) is still there.

**Comment by tranb3r** [comment] 2024-04-05 15:42
> not sure what you meant there, @tranb3r - the binding situation has changed since 8.0.1 was released, but it seems the relative source crashing (in my case when binding a command) is still there.

Exactly. I just wanted to remind that this issue has already been reported.
There is crash when using RelaliveSource. This has nothing to do with the BindingContext being set automatically in 8.0.1 or manually in 8.0.0.

**Comment by LennoxP90** [comment] 2024-04-10 04:19
I am using version 8.0.1 and I am experiencing the crash with
`Operation is not valid due to the current state of the object.`
```
<CollectionView Grid.Row="2"
                BackgroundColor="Black"
                VerticalScrollBarVisibility="Never"
                ItemsSource="{Binding FilteredConversationList}"
                ItemSizingStrategy="MeasureAllItems"
                ItemsUpdatingScrollMode="KeepScrollOffset"
                IsVisible="{Binding IsSearching}">
  <CollectionView.ItemsLayout>
    <LinearItemsLayout Orientation="Vertical" ItemSpacing="5"/>
  </CollectionView.ItemsLayout>
  <CollectionView.ItemTemplate>
    <DataTemplate x:DataType="models:ConversationModel">
      <Grid Margin="0"
            Padding="4"
            x:DataType="models:ConversationModel"
            RowDefinitions="Auto,Auto"
            ColumnDefinitions="*,*,25"
            BackgroundColor="#1C1C1C">
        
        <Grid.Behaviors>
          <toolkit:TouchBehavior Command="{Binding PressedCommand,
                                                   Source={RelativeSource AncestorType={x:Type viewmodels:ConversationsViewModel}}}"
                                 CommandParameter="{Binding .}"/>
        </Grid.Behaviors>
```

**Comment by zafrkaya** [comment] 2024-04-14 10:48
I was so excited for this but:
_'Operation is not valid due to the current state of the object.'_

```
 <Grid VerticalOptions="Center"
       Margin="0,120,0,0"
       ZIndex="5">
     <Image
         x:Name="LikeButton" 
         Margin="0,0,0,0"
         ZIndex="2"
         HeightRequest="35" 
         WidthRequest="35" 
         Source="{Binding LikeButtonImage}"
         IsVisible="{Binding IsLikeButtonVisible}">
         <Image.Shadow>
             <Shadow
             Radius="5"
             Brush="Black"
             Opacity="0.6"
             Offset="3,0"/>
         </Image.Shadow>
         <Image.Behaviors>
             <toolkit:TouchBehavior
                 DefaultAnimationDuration="250"
                 DefaultAnimationEasing="{x:Static Easing.CubicInOut}"
                 Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:DiscoverViewModel}}, Path=LikeOrUnlikeContentCommand}"
                 PressedOpacity="0.8"
                 PressedScale="0.8" />
         </Image.Behaviors>
     </Image>
```

**Comment by pictos** [comment] 2024-04-14 22:14
Can some one provide an sample? The sample provide by @r-work is hitting a 404 page.

**Comment by eduardoagr** [comment] 2024-04-14 22:56
this is how you can fix this.

1. Use then x:Name, for naming your XAML Page
2. Create a relay command in your viewModel
3. When binding the command, use BindingContext.YourCommand and as reference, use the name of the XAML 

As a workaround, you could do something like 

`    <CollectionView
        Grid.Row="1"
        Grid.ColumnSpan="3"
        Margin="5"
        IsVisible="{Binding isNotBusy}"
        ItemsSource="{Binding CoursesAssigned}">

        <CollectionView.ItemTemplate>
            <DataTemplate x:DataType="model:Course">
                <Border StrokeThickness="2">
                    <Border.StrokeShape>
                        <RoundRectangle CornerRadius="8" />
                    </Border.StrokeShape>
                    <Border.Behaviors>
                        <mct:TouchBehavior
                            DefaultBackgroundColor="Transparent"
                            HoveredBackgroundColor="CornflowerBlue"
                            PressedBackgroundColor="CornflowerBlue" />
                    </Border.Behaviors>
                    <Border.GestureRecognizers>
                        <TapGestureRecognizer
                            Command="{Binding Path=GoToDetailsCommand, Source={x:RelativeSource AncestorType={x:Type vm:MyCoursesPageViewModel}}}"
                            CommandParameter="{Binding .}" />
                    </Border.GestureRecognizers>
                    <Grid
                        Margin="5"
                        RowDefinitions="20,20"
                        VerticalOptions="Center">
                        <Label
                            FontAttributes="Bold"
                            Text="{Binding Name, StringFormat='Course name: {0}'}"
                            VerticalTextAlignment="Center" />

                        <Label
                            Grid.Row="1"
                            Text="{Binding Path=Total, Source={x:RelativeSource AncestorType={x:Type vm:MyCoursesPageViewModel}}, StringFormat='Students: {0}'}"
                            VerticalTextAlignment="Center" />

                        <Label
                            Grid.RowSpan="2"
                            FontFamily="Mat"
                            FontSize="40"
                            HorizontalTextAlignment="End"
                            Text="{x:Static helpers:IconFont.Read_more}"
                            VerticalTextAlignment="Center" />
                    </Grid>
                </Border>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</Grid>`

**Comment by r-work** [comment] 2024-04-15 07:41
@pictos my apologies, just realized the repo was private, I've just made it public.

**Comment by PauchardThomas** [comment] 2024-04-24 13:07
> I was so excited for this but: _'Operation is not valid due to the current state of the object.'_
> 
> ```
>  <Grid VerticalOptions="Center"
>        Margin="0,120,0,0"
>        ZIndex="5">
>      <Image
>          x:Name="LikeButton" 
>          Margin="0,0,0,0"
>          ZIndex="2"
>          HeightRequest="35" 
>          WidthRequest="35" 
>          Source="{Binding LikeButtonImage}"
>          IsVisible="{Binding IsLikeButtonVisible}">
>          <Image.Shadow>
>              <Shadow
>              Radius="5"
>              Brush="Black"
>              Opacity="0.6"
>              Offset="3,0"/>
>          </Image.Shadow>
>          <Image.Behaviors>
>              <toolkit:TouchBehavior
>                  DefaultAnimationDuration="250"
>                  DefaultAnimationEasing="{x:Static Easing.CubicInOut}"
>                  Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:DiscoverViewModel}}, Path=LikeOrUnlikeContentCommand}"
>                  PressedOpacity="0.8"
>                  PressedScale="0.8" />
>          </Image.Behaviors>
>      </Image>
> ```

Same crash Maui 8.0.20

**Comment by PauchardThomas** [comment] 2024-04-24 14:00
> yes, you'll get that crash if using relativesource on the command. there's the workaround that puts the command in a tapgestureRecognizer for you to get something that kind of works

But I lose the toucheffect UI....

**Comment by MitchBomcanhao** [comment] 2024-04-24 14:02
afaik you can leave the rest of the stuff, just put the command on the tap gesture recognizer. the rest of the touch behavior stuff should still happen

**Comment by zafrkaya** [comment] 2024-04-30 18:12
> afaik you can leave the rest of the stuff, just put the command on the tap gesture recognizer. the rest of the touch behavior stuff should still happen

I guess this workaround doesn't work for relativesource on Android, touch effect works but commands are not triggered. Btw iOS is okay

**Comment by LennoxP90** [comment] 2024-05-13 19:23
I am still in need of a solution for longpress, which is the entire point of using the original touch effect in my project

**Comment by bijington** [comment] 2024-05-14 21:34
> I am still in need of a solution for longpress, which is the entire point of using the original touch effect in my project

That sounds like an unrelated issue to this one. Have you raised an issue for that?

**Comment by LennoxP90** [comment] 2024-05-14 21:39
it is the same issue with relative source

**Comment by bijington** [comment] 2024-05-15 01:00
Have you tried the suggested workaround by avoiding RelativeSource?

**Comment by LennoxP90** [comment] 2024-05-15 01:16
I cannot avoid relative source as i am using datatemplates that switch depending on context

**Comment by LennoxP90** [comment] 2024-05-15 01:17
for now i just reverted my usage of the touchbehaviour and I will continue to use the TouchEffect source compiled in my project

**Comment by MattePozzy** [comment] 2024-05-17 13:48
Any news about this issue?
I have updated to CommunityToolkit.Maui 9.0.0 but it still persist for example with:

```
    <Grid 
        Padding="10"  Grid.Column="1"
        BackgroundColor="#fdd6a3" RowDefinitions="20,auto,auto" ColumnDefinitions="*,*,*" RowSpacing="0" ColumnSpacing="0" HorizontalOptions="FillAndExpand">
        <Grid.Behaviors>
            <toolkit:TouchBehavior 
                LongPressCommand="{Binding Source={RelativeSource AncestorType={x:Type vm:ChatViewModel}}, Path=ApriLogLetturaCommand}"
                LongPressDuration="1500"
                LongPressCommandParameter="{Binding .}"/>
        </Grid.Behaviors>
```

**Comment by bijington** [comment] 2024-05-17 14:05
@MattePozzy there is a workaround mentioned somewhere in the comments that suggests avoiding RelativeSource bindings. I would recommend trying that for now if you can

**Comment by MattePozzy** [comment] 2024-05-17 14:15
Changed code in this way and works:

```
<ContentView
 [..]
    x:Name="Me">

        <Grid 
            Grid.Row="0" Grid.Column="0" BackgroundColor="#F99209" Padding="10"
            RowDefinitions="20,auto,auto" ColumnDefinitions="auto,auto,auto" RowSpacing="0" ColumnSpacing="0" HorizontalOptions="Fill">
            <Grid.Behaviors>
                <toolkit:TouchBehavior 
                    BindingContext="{Binding Source={x:Reference Me}, Path=BindingContext}"
                    LongPressCommand="{Binding ApriLogLetturaCommand}"
                    LongPressDuration="1500"
                    LongPressCommandParameter="{Binding .}"/>
            </Grid.Behaviors>
```
But it doesn't work because the template is for an element list and the `BindingContext` of `Me` is the element itself and not the Viewmodel where the `Command` is.

**Comment by bijington** [comment] 2024-05-17 15:13
So you are using this inside a DataTemplate? Yes I don't think that will work right now

**Comment by Axemasta** [comment] 2024-05-17 17:36
Are we sure `RelativeSource`'s in maui are working the way they are intended to? I feel like this behaviour should be a bug, if it isn't a bug we need to support it properly because data templates do become very annoying to work with when using the MCT version!

**Comment by bijington** [comment] 2024-05-17 17:46
I've not had a chance to test whether this is a MAUI or MCT issue. I agree we need to find a solution though

**Comment by fourad** [comment] 2024-05-19 01:46
the tapgesture workaround don't work, when the user makes a long press the tap wont be recognized on android

**Comment by CodingOctocat** [comment] 2024-07-04 13:34
It work for me:

```csharp
LongPressCommand="{Binding Source={x:Reference YourContentPageName}, Path=BindingContext.YourLongPressCommand}"
```

**Comment by nor0x** [comment] 2024-07-30 11:57
this could be a related issue 🤔

the proposed solutions with `x:Reference` by name won't work anymore in .NET 9
https://github.com/dotnet/maui/issues/23711

**Comment by Axemasta** [comment] 2024-08-19 16:06
I've opened an [issue](https://github.com/dotnet/maui/issues/24313) with maui because I'm convinced the `RelativeSource` should be working... We will see that what say!

**Closed** 2024-12-18 01:14 UTC
Labels: bug, unverified, area/behaviors
