### ISSUE TITLE
Toast Position Issue on iOS: Overlapping with Keyboard

### ISSUE THREAD

**Issue by satish-dnv** [CommunityToolkit/Maui#1916] opened 2024-06-06 08:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When implementing the toast notification from the Maui Community Toolkit, I encountered an issue specific to iOS. On Android, the toast's position adjusts correctly based on the keyboard's appearance. However, on iOS, the toast gets blocked by the keyboard and does not reposition itself accordingly, making it completely hidden. The toast is triggered using the focus method of the keyboard.

The toast is blocked by the keyboard on iOS and does not change its position.

### Expected Behavior

The toast should reposition itself to remain visible above the keyboard, similar to its behavior on Android.

### Steps To Reproduce

1. Implement the toast notification using the Maui Community Toolkit.
2. Set up the toast to trigger when an input field gains focus 
3. Run the application on an iOS simulator or physical device.
4. Focus on an input field to bring up the keyboard and trigger the toast notification.

### Link to public reproduction project repository

https://github.com/satish-dnv/toastReproduce.git

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.1.0
- OS: Windows 10 Build 19045.4474
- .NET MAUI: 7
```

**Comment by satish-dnv** [comment] 2024-06-07 04:05
> I am not sure we can do it, as the toast on iOS is a part of the app, not the whole system as on Android

So, it means, it is not a bug?

**Comment by vhugogarcia** [comment] 2024-06-21 16:38
Thanks @satish-dnv for the report. However, as our friend @VladislavAntonyuk  mentioned it, on iOS it is displayed at the app level not the OS level as it is on Android. So, the keyboard will always be on top of the layers per Apple's OS.

Our recommendation is for you to play with a way to prevent the keyboard to be shown until the Toast is hidden and then you show the keyboard. Or maybe display a different alert in a different position of the screen. In other platforms they also faced the issue specifically for iOS like the one below in REACT and also on Flutter:

https://github.com/vonovak/react-native-simple-toast/issues/62

In this particular case, I'm closing this issue, since it is not a bug but a expected behavior from the OS.

**Closed by vhugogarcia** 2024-06-21 16:38 UTC
Labels: bug, unverified, area/alerts
