### ISSUE TITLE
[BUG] Resizing window (windows desktop) closes an open popup

### ISSUE THREAD

**Issue by peterjgould** [CommunityToolkit/Maui#888] opened 2023-01-11 01:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file.

### Current Behavior

Resizing a window when a popup is active closes the popup, works ok when window is minimized. Error is when resizing by dragging the corner.

![image](https://user-images.githubusercontent.com/91109453/211693082-4f63a43a-f241-4561-a3ce-5044afc86b06.png)

### Expected Behavior

Popup stays active when window is resized or minimized

### Steps To Reproduce

1) Run the application from the repo, size the window so it fits easily on the desktop
2) Click the button, a popup is displayed
3) Grab the bottom left corner to resize the windows, the popup closes

### Link to public reproduction project repository

https://github.com/peterjgould/PopupResize.git

### Environment

```markdown
- .NET MAUI CommunityToolkit: 3.1.0
- OS: Windows 10 build 19045.2364
- .NET MAUI:7.0.52/7.0.100
```

**Comment by VladislavAntonyuk** [comment] 2023-01-11 15:00
Duplicate of https://github.com/CommunityToolkit/Maui/issues/371

**Closed by VladislavAntonyuk** 2023-01-11 15:00 UTC
Labels: bug, unverified
