### ISSUE TITLE
[Bug] Popup does not respect Marigns when Stacklayout vertical layout options are set to expand

### ISSUE THREAD

**Issue by gktval** [CommunityToolkit/Maui#575] opened 2022-08-31 18:50 UTC
### Description

When the main Stacklayout in the popup has VerticalOptions="StartAndExpand" and Margin="20", the layout ignores any margin spacing.

![image](https://user-images.githubusercontent.com/7605046/187755601-028b0e64-5e43-483a-8b8e-fc6c991f7cbb.png)

If VerticalOptions="Start", then issues similar to this happen: https://github.com/CommunityToolkit/Maui/issues/388 (the layout is not fully utilized) except that any VerticalOptions="End" are ignored.

### Link to Reproduction Sample

Example Xaml code for popup:
```
<StackLayout  Orientation="Vertical" Margin="20" BackgroundColor="Gray">
        <StackLayout Orientation="Vertical" VerticalOptions="StartAndExpand">
            <Label Text="Workspace" HorizontalOptions="Center" FontSize="Title" />
            <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                <Label HorizontalOptions="FillAndExpand" />
                <ImageButton Source="dotnet_bot.png" HeightRequest="36" HorizontalOptions="End" />
            </StackLayout>
            <StackLayout  >
                <Picker Title="Select a root path" x:Name="RootPathPicker"/>
            </StackLayout>
        </StackLayout>
        <StackLayout Spacing="10">
            <Button x:Name="okBtn" Text="OK" Command="{Binding OKCommand}"/>
            <Button x:Name="cancelBtn" Text="Cancel" Command="{Binding CancelCommand}" />
        </StackLayout>
    </StackLayout>
```
### Expected Behavior
Margins around the inside of popup
### Actual Behavior
Margins are ignored

**Comment by pictos** [comment] 2022-08-31 19:06
@gktval 
Could you attach a small repro?

**Comment by gktval** [comment] 2022-08-31 19:54
Here is a link to a small example
https://www.dropbox.com/s/bkwf5wwjp6gl808/StackLayoutExample.zip?dl=0

**Comment by gktval** [comment] 2022-08-31 20:00
Here is an example
[StackLayoutExample.zip](https://github.com/CommunityToolkit/Maui/files/9464655/StackLayoutExample.zip)

**Comment by bijington** [comment] 2023-05-06 12:25
This certainly appears to be happy testing on MacCatalyst. @gktval what platform were you seeing this on?

<img width="516" alt="Screenshot 2023-05-06 at 13 25 08" src="https://user-images.githubusercontent.com/17139988/236623894-6e90fbea-76b0-4252-a488-2abc694d1d1e.png">

**Comment by gktval** [comment] 2023-05-06 13:51
Windows and Android last I checked

**Comment by vhugogarcia** [comment] 2023-10-31 18:10
I am unable to reproduce this issue. I tested it on Android and iOS. This error was reported on .NET MAUI 6 using .NET MCT 1.0.x , I upgraded the sample to .NET MAUI 7 and .NET MCT 6.0.0 and the margins and layout options are working as expected.

![Screenshot_1698775624](https://github.com/CommunityToolkit/Maui/assets/1047398/9dce2030-f81d-4008-b7ba-0077b789b22a)


I believe we can close this ticket. 

cc: @brminnick

**Closed** 2023-10-31 18:15 UTC
Labels: bug, unverified

**Comment by gktval** [comment] 2023-10-31 18:58
Also not working on Android. 

![image](https://github.com/CommunityToolkit/Maui/assets/7605046/9bcfc1f5-ba2c-4a9c-bd9b-6a0f0a961d37)
@brminnick 
@vhugogarcia

**Comment by gktval** [comment] 2023-10-31 19:19
Padding does apply the border. Thanks! The only other issue I see is in Windows. The height of the contents in the stack layout are ignored.

![image](https://github.com/CommunityToolkit/Maui/assets/7605046/b51a0150-ac3f-403a-9fef-c3c34c55efe6)
