### ISSUE TITLE
[Bug] In the Windows platform, Popup gets dismissed automatically when the context is switched to a different Window and returned

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/Maui#446] opened 2022-06-09 19:33 UTC
### Description

In the Windows platform, Popup gets dismissed automatically when the context is switched to a different Window and returned

### Steps to Reproduce

1. Add a Popup control in the new or existing .NET MAUI App
2. Add an option to invoke the Popup
3. Set Windows as the Target platform, build and run the app
4. Invoke the popup and switch the context to a different Window and come back, the Popup in this application gets dismissed automatically

### Expected Behavior
The Popup should stay open if the `CanBeDismissedByTappingOutsideOfPopup` property is set to `False`.

### Actual Behavior
Popup gets closed automatically, not even able to Debug it. Switching to VS closes the popup.

### Basic Information

- Version with issue: v1.0.0
- Last known good version: NA
- IDE: VS2022 17.3.0 Preview 1.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
  - WinUI: net6.0-windows10.0.19041.0 running on Windows 11 OS
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Nope

**Comment by pictos** [comment] 2022-06-09 19:37
This isn't a bug. This is how `Flyout` (The platform code that we use) works on Windows. We'll look at another control and see if that fits better with our usage.

So closing this issue.

**Closed by pictos** 2022-06-09 19:37 UTC
Labels: bug, unverified

**Comment by egvijayanand** [comment] 2022-06-09 19:41
Then how come the DisplayAlert stays in the foreground even after the context switch?

**Comment by VladislavAntonyuk** [comment] 2022-06-09 19:53
That is a different platform control

**Comment by egvijayanand** [comment] 2022-06-09 19:55
It would be highly expected that if the light dismissal is set to False, the Popup control should remain active until dismissed. **Could not even debug it.**

**Comment by bijington** [comment] 2022-06-09 20:01
I think this topic is certainly something that we should continue to discuss. I understand that with the current implementation of using a `Flyout` that there isn't any issue with how we are using that control. I do agree with @egvijayanand that a `Popup` should not auto dismiss itself in the manner that we are talking. If I present a `Popup` I expect it to only be dismissed by the user clicking outside (if allowed) or if it is programmatically closed (timeout or button tap/click).

There is no quick fix or action to be done but I would like to vote that we either reopen this issue or open a discussion (if one isn't already open) to discuss this functionality further.

**Comment by egvijayanand** [comment] 2022-06-09 20:03
Reflects my concern. When the developer itself is unable to debug it, how can I give this code for testing?

**Comment by bijington** [comment] 2022-06-09 20:06
@egvijayanand that is entirely valid. I guess we have expectations under similar use cases, there could of course be other use cases for why we have this behaviour in Windows so I would like to make sure that we don't lose that during the discussion. Perhaps we even want to push it out to the other platforms.

**Comment by egvijayanand** [comment] 2022-06-09 20:10
I mean to say that this is not a nice-to-have feature but rather a must-have feature for the toolkit's adoption. Should be discussed to find some way(s) to address this.

**Comment by VladislavAntonyuk** [comment] 2022-06-09 20:15
anyway it's a duplicate of https://github.com/CommunityToolkit/Maui/issues/371

**Comment by egvijayanand** [comment] 2022-06-09 20:18
My search keywords need to be more effective :-(

**Comment by bijington** [comment] 2022-06-09 20:20
I really wish GitHub would show similar issues when opening a new issue to help here.

**Comment by egvijayanand** [comment] 2022-06-09 20:23
> I really wish GitHub would show similar issues when opening a new issue to help here.

Nice idea, similar to how Windows and VS feedback does. Shows a list that matches the context while typing the issue title. Feedback for GitHub.

**Comment by bijington** [comment] 2022-06-09 20:43
> > I really wish GitHub would show similar issues when opening a new issue to help here.
> 
> Nice idea, similar to how Windows and VS feedback does. Shows a list that matches the context while typing the issue title. Feedback for GitHub.

I just searched GitHub for any submissions before submitting a feature request only to find someone beat me to it... 😄 

https://github.com/github-community/community/discussions/18185

**Comment by egvijayanand** [comment] 2022-06-09 20:45
I know you folks contribute to this toolkit out of your own interest and I do appreciate that.

So I'll try to check over the weekend on whether I can extend a helping hand on this.

**Comment by egvijayanand** [comment] 2022-06-09 20:47
> > > I really wish GitHub would show similar issues when opening a new issue to help here.
> > 
> > 
> > Nice idea, similar to how Windows and VS feedback does. Shows a list that matches the context while typing the issue title. Feedback for GitHub.
> 
> I just searched GitHub for any submissions before submitting a feature request only to find someone beat me to it... 😄
> 
> [github-community/community#18185](https://github.com/orgs/github-community/discussions/18185)

Need of the hour to save time and effort. I appreciate your effort in the attempt to initiate the discussion. You can upvote to reach the right people.
