### ISSUE TITLE
[BUG]? Popup does not wrap content (on Android)

### ISSUE THREAD

**Issue by Dry-Tech** [CommunityToolkit/Maui#1150] opened 2023-04-20 11:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Hello,
maybe I'm missing something very simple, but it seems that you can't use long texts as a label in a popup, because there is no line break and thus the popup will be wider than the display area.

I attached a sample repository and a screenshot.

### Expected Behavior

Popup takes almost full width of the display because the text is so long, and the label text has line breaks when necessary.

### Steps To Reproduce

1. Run the sample project
2. Click the button
3. You will see the result as shown in the screenshot

### Link to public reproduction project repository

https://github.com/Dry-Tech/NetMauiPopupNoWrapBug

### Environment

```markdown
- .NET MAUI CommunityToolkit: 5.1.0
- OS: Android 10
- .NET MAUI: 7.0
```

### Anything else?

![NetMauiPopupNoWrapBug](https://user-images.githubusercontent.com/113161103/233354411-de7ea6d0-e855-4ebe-9b65-bc267d7e3007.png)

**Comment by VladislavAntonyuk** [comment] 2023-04-21 07:29
Try replacing VerticalStackLayout with Grid

**Comment by Dry-Tech** [comment] 2023-04-21 10:08
> Try replacing VerticalStackLayout with Grid

No sorry, did not work.

**Comment by cat0363** [comment] 2023-08-28 00:35
This issue may be resolved by PR #1361.

**Comment by cat0363** [comment] 2023-11-06 04:19
In API Level 29 and below, the following method is used to obtain the height of the status bar, but this seems to be the problem.

[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.android.cs]

    decorView.GetWindowVisibleDisplayFrame(contentRect);
    statusBarHeight = contentRect.Top;

When you call the above method, the Label will not wrap.
Although it is not very desirable, if you obtain the height of the status bar using the method introduced [below](https://github.com/CommunityToolkit/Maui/pull/1320/commits/e4681ea643f61144b80981bdc87465d0298c4fcf), the label will be wrapped correctly. (This is the method I gave up on in PR #1320.)

    var resourceIdStatus = decorView?.Context?.Resources?.GetIdentifier("status_bar_height", "dimen", "android") ?? 0;
    statusBarHeight = resourceIdStatus > 0 ? decorView?.Context?.Resources?.GetDimensionPixelSize(resourceIdStatus) ?? 0 : 0;

If you can get the height of the status bar without calling the GetWindowVisibleDisplayFrame method, the problem for API Level 29 and below will be resolved.

Below are the results of the operation verification of the latest version of main.

[Use GetWindowVisibleDisplayFrame]

<img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/6bf80586-0e83-41da-9680-4e5d9e664b53" />

[Don't use GetWindowVisibleDisplayFrame]

<img width="250" src="https://github.com/CommunityToolkit/Maui/assets/125236133/e4e8775c-8239-4efe-beab-b3ecd31a6da6" />

API Level 30 and above is working as intended.
I'm looking into how to get the Statusbar height in API Level 29 and below, but I haven't found it yet.

@brminnick , I would like to hear your opinion.

**Comment by cat0363** [comment] 2023-11-06 05:18
@brminnick , I found a solution.

I found a way to calculate the status bar height without using the method below.
I will create a PR.

    var resourceIdStatus = decorView?.Context?.Resources?.GetIdentifier("status_bar_height", "dimen", "android") ?? 0;
    statusBarHeight = resourceIdStatus > 0 ? decorView?.Context?.Resources?.GetDimensionPixelSize(resourceIdStatus) ?? 0 : 0;

**Closed** 2023-11-07 19:07 UTC
Labels: bug, unverified
