### ISSUE TITLE
[BUG] Ambiguous reference error occurs when other package is included that provides its own Colors object

### ISSUE THREAD

**Issue by IIARROWS** [CommunityToolkit/Maui#1535] opened 2023-11-18 18:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When creating a new MAUI project and adding MAUI Community Tookit and another project that includes its own Colors object (e.g. [MudBlazor](https://github.com/MudBlazor/MudBlazor), the following error occurs:
  Error	CS0104	'Colors' is an ambiguous reference between 'Microsoft.Maui.Graphics.Colors' and 'MudBlazor.Colors'  TestProject (net8.0-android)	[...]\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs	36	Active

### Expected Behavior

No error should happen

### Steps To Reproduce

- Create a new .NET MAUI Blazor Hybrid project
- Add CommunityToolkit.Maui nuget
- Add MudBlazor nuget
- Add `global using MudBlazor;`
- Compile the project

### Link to public reproduction project repository
https://github.com/IIARROWS/CommunityToolkitColorsGeneration

### Environment

```markdown
- .NET MAUI CommunityToolkit:7.0.0
- OS: Windows 10
- .NET MAUI: 8.0.3
```

### Anything else?

The bug is related to issue #1331, it behaves the same way, excepts it's referring to a class `Colors` instead of enumerator `Color`.

**Comment by IIARROWS** [comment] 2023-11-18 18:59
Added reproduction https://github.com/IIARROWS/CommunityToolkitColorsGeneration

**Comment by brminnick** [comment] 2023-11-18 19:19
> Add global using MudBlazor;

This breaks `CommunityToolkit.MAUI`. 

I don't recommend using a `global using` for the class `Color`.

**Comment by brminnick** [comment] 2023-11-18 19:20
Closing because it is not a bug in `CommunityToolkit.Maui`

**Closed** 2023-11-18 19:22 UTC
Labels: bug, unverified, needs reproduction
