### ISSUE TITLE
[BUG] CollectionView/ListView into Popup strange behavior when display items(Android Only) when Label VerticalTextAlignment="Center" 

### ISSUE THREAD

**Issue by huytran123** [CommunityToolkit/Maui#1532] opened 2023-11-16 07:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When i add CollectionView/ListView into Popup page. On the first time show, items in listview or CollectionView do not show. I have to scroll up or down to show them. This is my demo strange behavior

https://github.com/CommunityToolkit/Maui/assets/24526707/16fb25b7-b179-4406-9b31-f1d70ef7755f

When remove VerticalTextAlignment or change to HorizontalOptions it working perfectly

### Expected Behavior

show all item in listview or collectionview when i show popup page

### Steps To Reproduce

1. Create popup page
2. Add CollectionView/ListView into Popup page. 
3. Binding Itemsources
4. Show popup page

### Link to public reproduction project repository

https://github.com/huytran123/BugMauiListItemInPopup.git

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.1.0
- OS: MAC OS 13.4.1
- .NET MAUI: net7.0;net7.0-android
```

**Comment by ysipankaja** [comment] 2023-11-16 11:01
Yes, I am facing the same issue with Popup. If I remove the TextAlignment, its working fine.

**Comment by imsam67** [comment] 2024-03-15 20:16
I'm having the same issue and installed the package generated for https://github.com/CommunityToolkit/Maui/pull/1683 and it fixes the issue. Thanks @cat0363

**Comment by imsam67** [comment] 2024-03-15 20:20
BTW, this issue is a duplicate of https://github.com/CommunityToolkit/Maui/issues/1592

**Closed** 2024-03-25 23:40 UTC
Labels: bug, unverified, area/views
