### ISSUE TITLE
[BUG] Hidden layer in media player element

### ISSUE THREAD

**Issue by Strypper** [CommunityToolkit/Maui#1352] opened 2023-08-18 02:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

[AcylicView](https://github.com/sswi/AcrylicView.MAUI) is an open-source library that allows you to blur a layer and create a frosted effect, allowing you to see through to what is beneath it. However, when using it with MediaView, nothing can be seen through the layer. I am not sure what is causing this issue, as shown in the image below
![image](https://github.com/sswi/AcrylicView.MAUI/assets/32596308/7e8c2d76-ff12-42b7-a973-de0a22e7bdd5)
I have already reported this issue to the author of AcylicView, and they have confirmed that it is an issue with the community toolkit
https://github.com/sswi/AcrylicView.MAUI/issues/4

### Expected Behavior

The AcrylicView could see through

### Steps To Reproduce

1. Pull the `MAUIsland` repo (attached below)
2. Create an empty `appsettings.Development.json` file (file name should be exactly like `appsettings.Development.json`, for the content of the file doesn't need to add anything)
3. Navigate to the control gallery
4. Choose a community gallery
5. Choose an acrylic view card (Please notice that we currently have an MAUI issue with this [Button need to click at the bottom left to trigger](https://github.com/dotnet/maui/issues/16285), so you need to click at that position to navigate to the page)
6. Navigate to the bottom at the page to see the issue

### Link to public reproduction project repository

https://github.com/Strypper/mauisland

### Environment

```markdown
- .NET MAUI CommunityToolkit:Latest
- OS: Windows
- .NET MAUI: 7
```

### Anything else?

<img src="https://media1.giphy.com/media/fXnRObM8Q0RkOmR5nf/giphy.gif"/>

**Comment by ne0rrmatrix** [comment] 2024-06-18 00:31
Which devices does this bug affect? Is it windows, android, iOS, or Mac Catalyst. Is it one, all or specific device types that have issues?

**Comment by Strypper** [comment] 2024-06-18 01:46
> Which devices does this bug affect? Is it windows, android, iOS, or Mac Catalyst. Is it one, all or specific device types that have issues?

Only Windows
Android: works fine
IOS,Tizen,MacOS: Not tested

**Comment by lgztx96** [comment] 2024-06-18 11:44
> > Which devices does this bug affect? Is it windows, android, iOS, or Mac Catalyst. Is it one, all or specific device types that have issues?
> 
> Only Windows Android: works fine IOS,Tizen,MacOS: Not tested

On Windows Platforms,  this is currently by design. see https://github.com/microsoft/microsoft-ui-xaml/issues/9267

**Comment by vhugogarcia** [comment] 2024-06-18 14:34
Thanks @lgztx96 for sharing the link from Microsoft UI. Since this is by design and an expected behavior, I'm closing this issue.

**Closed by vhugogarcia** 2024-06-18 14:34 UTC
Labels: bug, unverified, 📽️ MediaElement
