### ISSUE TITLE
Adding community toolkit to razor class library breaks styles.css

### ISSUE THREAD

**Issue by whann0205** [CommunityToolkit/Maui#2104] opened 2024-08-08 18:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Breaks the css 
see for yourself in the reproduction repository

### Expected Behavior

Dont break the css let net maui display correctly

### Steps To Reproduce

1. Create a new blazor hybrid and web solution 
2. Add nugetpackage Community toolkit to it
3. Build and debug 

### Link to public reproduction project repository

https://github.com/whann0205/BlazorHybridWebCommunity

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.2
- OS: Windows
- .NET MAUI: 9.0.0-preview.6.24327.7/9.0.100-preview.6
```

**Comment by bijington** [comment] 2024-08-08 18:50
Would you mind sharing the detail of what is broken in your CSS? I don't have the previews installed on my machine to check. I have to be honest, I would be very surprised if this toolkit it causing something to affect CSS styling.

**Comment by VladislavAntonyuk** [comment] 2024-08-08 19:02
We are not compatible yet with net9. Please check the same behavior in net8

**Comment by whann0205** [comment] 2024-08-08 21:38
<img width="259" alt="Screenshot 2024-08-08 233037" src="https://github.com/user-attachments/assets/af085a73-9d39-4215-89fb-1a08c7f5b8c7">

Thats what i see, instead of the default one every knows.
I have used the new blazorhybridweb template, nothing else added.
I was surprised as well, but it is doing that way.
I am not sure to reproduce since that template uses net.9
Well will it be compatible with .net9?

**Comment by bijington** [comment] 2024-08-09 05:50
We will be compatible with .NET 9 when it GAs. Have you looked into whatever that unhandled exception is? That may well be breaking your CSS

**Comment by whann0205** [comment] 2024-08-09 05:54
Yes, i have used chrome to inspect the app. There i can clearly see that styles.css gets 404 - not found.
So i know why the layout is scrambled but not why it is missing eg. not getting created.

**Comment by bijington** [comment] 2024-08-09 06:04
Can you handled the exception in your app rather than using chrome to debug it? That might help to find out why.

Also are there any build warnings that might indicate issues?

**Comment by whann0205** [comment] 2024-08-09 06:11
So i need to find out how to handle exceptions first? 
No build warnings except that the installed preview version of .net does
not exactly match the ones referenced.
Its easy to reproduce simply 
create a new project based on the new blazor hybrid and web template add community toolkit
is all you need to do to get the error.
I also have uploaded the app to my repository.

**Comment by bijington** [comment] 2024-08-09 06:14
> So i need to find out how to handle exceptions first? 

@jfversluis yiu are my go to expert in MAUI Blazor. Is there a good mechanism for this?

> No build warnings except that the installed preview version of .net does

This could be the issue. If the toolkit is making your app use a different version when building due to dependencies and your template is specific to .NET 9. Can you share one of those warnings?

> not exactly match the ones referenced.
> 
> Its easy to reproduce simply 
> 
> create a new project based on the new blazor hybrid and web template add community toolkit
> 
> is all you need to do to get the error.
> 
> I also have uploaded the app to my repository.
> 
>

**Comment by whann0205** [comment] 2024-08-09 06:46
This is getting confusing. I have created a new solution based on 
https://learn.microsoft.com/aspnet/core/blazor/hybrid/tutorials/maui-blazor-web-app
with my "old" visual studio 17.10.4 and .net8.
Same behavior as described above.
But i have not removed 9.0.100-preview.6.24328.19 nor side by side visual studio preview 17.11 preview 7.
Dont know if thats important just to let you know.

**Comment by whann0205** [comment] 2024-08-09 07:52
![grafik](https://github.com/user-attachments/assets/ae2ce56f-a62d-4428-a6ce-c1dd399001d1)
Thats how it should look like and it looks if you remove the community toolkit reference.
![grafik](https://github.com/user-attachments/assets/cd78074e-6f1e-4e47-a39f-cf82a3d5a208)
Thats how it looks if you add community toolkit reference.
From my index.html
```
head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
    <title>WordAssoTest.Maui</title>
    <base href="/" />
    <link rel="stylesheet" href="_content/WordAssoTest.Shared/css/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="_content/WordAssoTest.Shared/css/app.css" />
    <link rel="stylesheet" href="WordAssoTest.Maui.styles.css" />
    <link rel="icon" type="image/png" href="favicon.png" />
</head>

Hope someone can help me in this matter. Its a showstopper for me since
i want to use some funtionality mention by gerald in youtube....

```

**Comment by jfversluis** [comment] 2024-08-09 08:02
Ah this is the new template that will be introduced interesting. I know its a bit of a hassle but you're being a great help here.

Would you be able to start a new project with Blazor Hybrid, just the app, not the rest so `dotnet new maui-blazor` and see if that shows this same behavior?

**Comment by whann0205** [comment] 2024-08-09 08:23
I am pretty sure that it has to do something with the razor class library or its implementation
since "normal" blazor hybrid works !, just tested it.
What also maybe interesting that i have not used the "new" template in .net8 since it
is not available for this .net version but followed the instructions in
https://learn.microsoft.com/aspnet/core/blazor/hybrid/tutorials/maui-blazor-web-app
and have done it manually.

**Comment by jfversluis** [comment] 2024-08-09 08:29
Aha thats interesting to know. If you are on .NET 9 preview, you should also have access to https://github.com/dotnet/maui/tree/net9.0/src/Templates/src/templates/maui-blazor-solution

What does it list if you do `dotnet new list`? Is it there?

I would be curious if that template works or if you have missed something in setting this up _or_ something is missing in the docs there :)

**Comment by whann0205** [comment] 2024-08-09 08:49
Gerald, you know that its not an .net 9 issue anymore do you?
Please find attached the output of dotnet new list.
[dotnetlist.txt](https://github.com/user-attachments/files/16558566/dotnetlist.txt)
It does not list the template there as i can see.
I would like to test but i DONT want to crash other templates by reinstalling all templates.
Is it possible to just install that one alone?

**Comment by jfversluis** [comment] 2024-08-09 08:55
The top one is this list is exactly the template you're looking for:

> .NET MAUI Blazor Hybrid and Web App       maui-blazor-web             [C#]        MAUI/Android/iOS/macOS/Mac Catalyst/Windows/Tizen/Blazor/Blazor Hybrid/Mobile

I missed that you're saying that this works with .NET 9, that is very interesting. It might then very well be that something got fixed for that.

I just tried this [sample here](https://github.com/BethMassi/BethTimeUntil) which is on .NET 8 and follows the same setup, and that seems to work fine. So something seems to be specific to your project.

**Comment by jfversluis** [comment] 2024-08-09 08:56
Looks like this is also is fixed in the latest .NET MAUI service release.

In your project I just updated these packages to 8.0.80 and that seems to fix it. Can you let me know if that's the same for you?

```xml
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.80" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="8.0.80" />
```

**Comment by whann0205** [comment] 2024-08-09 09:33
Sorry that does not help. 
I also does not know how you could add these references 
to the sample project on my github which
was targetting .net9?
As i wrote is not an issue was a wrong word i mean problem. Its not a problem with .net9 
i can reproduce it with .net8 as well.
Now i can deinstalled visual studio preview and ALL traces of .net9 having now 
installed Visual studio 17.10.4 and 8.0.303 of dotnet as dotnet -version tells me.
Still the same problem so it has no to do with .net9.
In addition i tried to add CommunityToolkit Media Element instead of the main CommunityToolkit package
same problem. I´m lost. Probably you want to take a look via teamviewer?

**Comment by bijington** [comment] 2024-08-09 09:42
Let me try and summarise the issue.

The issue exists on both sides .NET 8.0 and the .NET 9.0 preview.

Gerald is saying that if you use the latest service release `8.0.80` then it should solve your issue. Have you tried this in the scenario where you reproduced this in .NET 8.0?

**Comment by whann0205** [comment] 2024-08-09 09:49
![grafik](https://github.com/user-attachments/assets/435b778c-c5e7-444c-8304-df364b2453c0)
![grafik](https://github.com/user-attachments/assets/c0dc4c33-ac2e-46bf-8302-f75f31921c22)

Yes, i did please take a look on the screenshots.

**Comment by jfversluis** [comment] 2024-08-09 09:52
I think I see what's wrong. Actually it didn't have to do with the MAUI version. You are installing the Community Toolkit package on the Shared project. That will have no use, that is only working for the .NET MAUI project.

Move the `<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="4.0.1" />` line to your `BlazorHybridWebCommunity.csproj` file.

**Comment by whann0205** [comment] 2024-08-09 10:12
Ahhh now everything is clear. Well sorry for wasting your time!
As a "share all dont do any duplicate" type of developer i simply thought i 
could put all stuff inside the shared library which can be used by web and maui 
and make use of dependency injection where appropiate.
i understand that controls as such cannot be used inside razor,
but can one use api´s of community tookit for example the SpeedtoText API  
via dependency injection in razor files at all? 
My objective is to grab the speech of somebody get the text and use the
resulted text inside a razor file. 
Maybe an example in youtube how to share these things would be great!

**Comment by jfversluis** [comment] 2024-08-09 10:18
Maybe this one will help: https://www.youtube.com/watch?v=2dllz4NZC0I

Glad we could figure it out!

**Closed by jfversluis** 2024-08-09 10:18 UTC
Labels: bug, unverified, needs reproduction
