### ISSUE TITLE
[BUG] IconTintColorBehavior doesn't work as expected on Windows

### ISSUE THREAD

**Issue by alpayclsr1** [CommunityToolkit/Maui#1594] opened 2023-12-07 12:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

![image](https://github.com/CommunityToolkit/Maui/assets/105295582/77ffa87a-d8a2-440c-a2ad-c432b0f6ef4f)  Icon tint color behavior works fine on Android and iOS, but when I try to use it on Windows it copies the image.

       
```
  <StackLayout
     Margin="50"
     Spacing="15"
     VerticalOptions="FillAndExpand">
     <HorizontalStackLayout>
         <Image Aspect="AspectFit" Source="png4xfolder.png">
             <Image.Behaviors>
                 <toolkit:IconTintColorBehavior TintColor="Red" />
             </Image.Behaviors>

         </Image>
         <Image Aspect="AspectFit" Source="png4xfolder.png">
             <Image.Behaviors>
                 <toolkit:IconTintColorBehavior TintColor="Blue" />
             </Image.Behaviors>

         </Image>


         <Image Aspect="AspectFit" Source="png4xfolder.png">
             <Image.Behaviors>
                 <toolkit:IconTintColorBehavior TintColor="Orange" />
             </Image.Behaviors>

         </Image>
     </HorizontalStackLayout>











 </StackLayout>
```

### Expected Behavior

![image](https://github.com/CommunityToolkit/Maui/assets/105295582/e1839e56-193b-4012-82c1-c1f22495442d)
works as expected on android

### Steps To Reproduce

1.Run the application with windows and see the bug

### Link to public reproduction project repository

https://github.com/alpayclsr1/BugReproductionApp.git

### Environment

```markdown
- .NET MAUI CommunityToolkit:
- OS:
- .NET MAUI:
```

**Comment by vhugogarcia** [comment] 2023-12-07 14:34
Thanks @alpayclsr1 for creating the issue and creating a sample project with the issue you are experiencing. However, could you please share the Environment details where you are facing that issue?

I'm unable to reproduce the issue with the sample project you shared with us. See screenshot below for reference:
![image](https://github.com/CommunityToolkit/Maui/assets/1047398/96e6da85-96f5-4129-983c-683b3a1df745)

I'm running Windows 11 latest version
![image](https://github.com/CommunityToolkit/Maui/assets/1047398/f460f637-b608-47aa-8ade-cec430bfa646)

If you are not using the latest version of Windows 11, could you please apply the latest OS and test again? 😃

**Comment by SamuelJames101** [comment] 2023-12-08 15:58
I am seeing this issue also, I had to put in the changes 

`        // Requested size requires additional offset to re-center tinted image.
        //var requiresAdditionalCenterOffset = element.WidthRequest != -1 || element.HeightRequest != -1;
        //var offset = requiresAdditionalCenterOffset ? new Vector3(width * anchorPoint.X, height * anchorPoint.Y, 0f) : Vector3.Zero;
        var offset = new Vector3(width * anchorPoint.X, height * anchorPoint.Y, 0f);`

I can't remember who recommend it on another issue that was raised. But will try and find it and add it in here

**Comment by alpayclsr1** [comment] 2023-12-11 05:22
@vhugogarcia The bug has been resolved because I gave a certain height. Can you download sample project again? Windows version:22H2 OS build 22621.2715

**Comment by VladislavAntonyuk** [comment] 2023-12-11 06:26
@alpayclsr1 could you close the issue if byg is resolved?

**Comment by alpayclsr1** [comment] 2023-12-11 07:23
@VladislavAntonyuk The bug continues unless we give exact height to the image. Isn't this a bug?I did not use height request in the current sample project and there is a problem.It would be better not to use height request in the scenario I will use

**Comment by SamuelJames101** [comment] 2023-12-15 15:06
I see the issue if I get the image to "AspectFit" into an area.

**Comment by Bloodyairtimer** [comment] 2024-01-10 07:59
This issue is about to get me go nuts :)

I have attached a sample project where i placed some images in a Grid which are rendered correctly.
Adding the same images to a horizontal stacklayout places the tinted image on a strange offset.

When I update the code in the IconTintColorBehavior.Windows.cs file to not have an offset / anchorpoint in the visualsprite element it is rendered correctly in the stacklayout but not in the grid.

![image](https://github.com/CommunityToolkit/Maui/assets/44552695/521dcf9c-fefe-428f-bf85-3c76aa52913d)


[MauiApp4.zip](https://github.com/CommunityToolkit/Maui/files/13884406/MauiApp4.zip)

**Comment by Ruddy2007** [comment] 2024-02-12 14:17
Hey. I have also just ran into this issue on Windows 10. I have no idea what's going on, it was working fine and then I started using the markup toolkit and since then its duplicating the icons. 

Only just starting to look into it but it does appear some weird bug is at play.

**Comment by NoelleRousselle** [comment] 2024-03-01 09:43
I have the same Issue on Windows 11. For me it works when I set minimum and maximum height/width instead of a height and width request.

**Comment by vhugogarcia** [comment] 2024-07-23 15:06
@NoelleRousselle @alpayclsr1, we have been running some tests locally on Windows 11 using the MAUI Community Toolkit version 9.0.2 and .NET MAUI 8.0.70 and the issue appears to be fixed. If we don't set a height or width on the image, the tint color is applied correctly as well. Please upgrade and let us know the results.

I'm closing this issue for now. We can re-open it, if needed.

![image-icon-tint](https://github.com/user-attachments/assets/8736cf5f-4290-4b0a-b7a4-bad824d97342)

**Closed by vhugogarcia** 2024-07-23 15:06 UTC
Labels: bug, unverified, not-reproduced, area/behaviors
