### ISSUE TITLE
[BUG] Urgent - Map crashes upon reload

### ISSUE THREAD

**Issue by imadofficial** [CommunityToolkit/Maui#2394] opened 2024-12-18 21:18 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Whenever I open the map upon 2nd attempt, it crashes.

### Expected Behavior

I expected it to not crash..

### Steps To Reproduce

1) You open the page once (everything works)
2) You pop the page & re-enter
3) Interact with the map for a 2nd time and it crashes.

### Link to public reproduction project repository

https://github.com/imadofficial/MapIssue

### Environment

```markdown
- .NET MAUI CommunityToolkit: 10.0.0 (Microsoft.Maui.Maps)
- OS: iOS 18.1 (also happens on my phone on iOS 18.3)
- .NET MAUI: 9.0.21
```

### Anything else?

Here's a video of how it happens:
https://github.com/user-attachments/assets/67413e98-a4cb-4949-9897-16a37122d1df

This bug causes major issues with my app's core functionality... Can you guys fix it asap (if possible).

**Comment by bijington** [comment] 2024-12-18 21:24
@imadofficial I think you've got the wrong repository. It looks like you are using Microsoft.Maui.Maps which is .NET MAUI functionality. This is the community toolkit repository. The repository you want is over at: https://github.com/dotnet/maui

I'll close this issue for now

**Closed by bijington** 2024-12-18 21:24 UTC
Labels: bug, unverified

**Comment by imadofficial** [comment] 2024-12-18 21:58
I think you're wrong though...

<img width="403" alt="Image" src="https://github.com/user-attachments/assets/0d1257e2-c3ed-4934-b433-ecfee09ee76d" />

**Comment by brminnick** [comment] 2024-12-18 22:04
Hi @imadofficial! We only provide Maps support for Windows.

Your Issue highlights the problem is on iOS. As Shaun mentioned above, the .NET MAUI Engineering team provides support for `Microsoft.Maui.Maps` on iOS.

**Comment by VladislavAntonyuk** [comment] 2024-12-18 22:21
There is an open issue in MAUI repo. The workaround is using manual behavior for DesconnectHandler
