### ISSUE TITLE
[BUG] TouchBehavior color properties are not theme aware

### ISSUE THREAD

**Issue by zwikk** [CommunityToolkit/Maui#1994] opened 2024-07-02 12:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When binding a color property such as ```DefaultBackgroundColor``` to a theme color with ```AppThemeResource``` or ```AppThemeBinding```, the color doesn't change when switching themes.

Reproduce
1) Consider the following BoxView with touch behavior:
```xml
<BoxView WidthRequest="200" HeightRequest="200">
  <BoxView.Behaviors>
    <toolkit:TouchBehavior
      DefaultBackgroundColor="{toolkit:AppThemeResource DefaultColor}"
      PressedBackgroundColor="{toolkit:AppThemeResource PressedColor}" />
  </BoxView.Behaviors> 
</BoxView>
```
with the following colors:
```xml
<toolkit:AppThemeColor x:Key="DefaultColor" Light="Orange" Dark="LightGreen" />
<toolkit:AppThemeColor x:Key="PressedColor" Light="Red" Dark="Green" />
```
2) In light mode, the view is Orange, and on press, the view changes to Red. Works great.
3) Switch to dark mode
4) Observe that the view remains orange, while it should be LightGreen. Pressing the view in dark mode change the color to Red, which should be Green.

Other observations
- The behavior occurs with all color properties (```DefaultBackgroundColor```, ```PressedBackgroundColor``` and ```HoveredBackgroundColor```
- The behavior occurs with both ```AppThemeBinding``` and ```AppThemeResource```

### Expected Behavior

The TouchBehavior color properties should be made theme aware.

### Steps To Reproduce

1. Clone git repo https://github.com/zwikk/maui-playground
2. Open project [Source/TouchBehaviorTest](https://github.com/zwikk/maui-playground/tree/main/Source/TouchBehaviorTest)
3. Run the project, press the box view, switch theme and observe the incorrect behavior

### Link to public reproduction project repository

https://github.com/zwikk/maui-playground

### Environment

```markdown
- .NET MAUI CommunityToolkit: 9.0.1
- OS: iOS 17.2, Android API 34
- .NET MAUI: 8.0.61
```

**Comment by YZahringer** [comment] 2024-07-18 14:08
Also not working with `DynamicResource`. 
Works only with `StaticResource`.

**Comment by IeuanWalker** [comment] 2024-07-18 16:11
@zwikk as a workaround if it is the pressed colour you want to change, could give my control ago - https://github.com/IeuanWalker/Maui.StateButton

**Comment by YZahringer** [comment] 2024-08-08 09:29
I think the bug is caused by the lack of state update during `propertyChanged` of [BindingProperties](https://github.com/CommunityToolkit/Maui/blob/4a2166a1fd2fb7a27027f501163addeab8b68800/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.shared.cs#L221C42-L221C73)

**Comment by Axemasta** [comment] 2024-08-19 16:11
Does this work with an `AppThemeBinding`?

```xml
<BoxView WidthRequest="200" HeightRequest="200">
  <BoxView.Behaviors>
    <toolkit:TouchBehavior
      DefaultBackgroundColor="{AppThemeBinding Light='Orange, Dark={'LightGreen'}"
      PressedBackgroundColor="{AppThemeBinding Light='Red, Dark={'Green'}" />
  </BoxView.Behaviors> 
</BoxView>
```

**Comment by Axemasta** [comment] 2024-08-25 17:31
I've investigated this issue as I've come to start properly supporting dark mode in my app...

This is a much bigger issue than simply adding a property changed hook. When the control updates its background color it breaks the theme binding, either if set directly or through an `AppThemeColor` resource, because it will manually update the controls background.

What are your thoughts @pictos, if we change the background color of the view when animating, it will unset the app theme binding. This is only a problem when you change themes during use of the app, new elements (ie navigating to a new page) will cause the correct theme color to display. Unless we had dark / light color properties (Which would be silly), I don't know how we can fix this :\

**Comment by Axemasta** [comment] 2024-08-26 08:47
Ok looks like this did all work with theme switching in Xamarin. I will try and port as much of that code as I can and see what I end up with!

**Comment by Axemasta** [comment] 2024-08-27 12:55
After some investigation this is actually a maui issue. `AppThemeColor` uses `AppThemeBinding` under the hood and the `AppThemeBinding` was not firing when the theme changed for this behavior. My PR over in maui addresses the issue and hopefully if it gets approved this issue will be fixed in future maui versions!

**Comment by brminnick** [comment] 2024-10-18 20:20
> After some investigation this is actually a maui issue. AppThemeColor uses AppThemeBinding under the hood and the AppThemeBinding was not firing when the theme changed for this behavior. My PR over in maui addresses the issue and hopefully if it gets approved this issue will be fixed in future maui versions!

Thanks for confirming!

**Closed by brminnick** 2024-10-18 20:20 UTC
Labels: bug, unverified, area/behaviors

**Comment by Axemasta** [comment] 2024-10-19 10:04
@brminnick as an FYI the Maui team aren't prepared to merge any of my fixes for Behaviors. They have decided that Behavior itself should not inherit BindableObject and have essentially said that the way our behaviors (touch and more) are api abuse...

Unless either the team are convinced to change direction and merge the fixes, we might have to consider moving back to Effects both here (MCT) and elsewhere in our apps!

**Comment by brminnick** [comment] 2024-10-19 14:22
We are following their lead. The Community Toolkit will no longer automatically assign bindings for our Behaviors either beginning with .NET 9.

I have detailed this breaking change in our .NET 9 PR and we'll be including in our release notes https://github.com/CommunityToolkit/Maui/pull/2215. 

You can find additional details in the PR for our docs: https://github.com/MicrosoftDocs/CommunityToolkit/pull/486
