### ISSUE TITLE
[BUG] StatusBarBehavior No Longer Working on iOS With Exception

### ISSUE THREAD

**Issue by Nope-Git** [CommunityToolkit/Maui#2284] opened 2024-10-15 21:19 UTC
I'm having trouble with StatusBarBahavior on MAUI iOS. I've tried with iOS 17.5 and 18. My StatusBarBehavior code worked fine before updating MAUI, the MAUI tookit, and XCode. Now I get the following error message.

Microsoft.Maui.Controls.Xaml.XamlParseException: 'Position 8:10. Type toolkit:StatusBarBehavior not found in xmlns http://schemas.microsoft.com/dotnet/2022/maui/toolkit'

I have the following code in my XAML.

```
    <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="MyApp.Pages.CoreAppPage" 
             Title="MyApp" 
             xmlns:ViewModels="clr-namespace:MyApp.ViewModels" 
             xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"> 
    <Page.Behaviors> 
        <toolkit:StatusBarBehavior 
            StatusBarColor="{StaticResource StatusBarColor}"
            StatusBarStyle="LightContent" />
    </Page.Behaviors>... 
```

MauiProgram.cs
```
    var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                // Initialize the .NET MAUI Community Toolkit by adding the below line of code
                .UseMauiCommunityToolkit()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });
```

I've tried restarting both the mac I'm building on and the machine that runs Visual Studio. The bin and object folders were deleted and rebuilt but produced the same error. As stated previously, this was something that was working fine before I updated.

Is this a bug or are there some other things I should be trying to get the app to build after the update?

**Comment by Nope-Git** [comment] 2024-10-16 00:31
Downgrading the community toolkit to 9.0.3 appears to have fixed this behavior.

**Comment by brminnick** [comment] 2024-10-16 19:49
We closed it because we cannot reproduce this error.

This is most likely a misconfiguration of your local environment. Please open a new Issue with a reproduction sample if you are unable to resolve your problem.

@amilici  Please ensure you have installed the following items:
- [ ] Xcode 16.0.0
- [ ] Update to the latest stable version of Visual Studio (or Jet Brains Rider)
- [ ] Download/install the [latest stable version of .NET 8 (v8.0.403)](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)
- [ ] After installing .NET SDK v8.0.403, update to the latest stable version of .NET MAUI
  - On macOS, open the Terminal and enter the following command: `sudo dotnet workload install maui`
  - On Windows, open the command prompt (or Powershell) and enter the following command: `dotnet workload install maui`
- [ ] Add a [`global.json`](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) file to your application with the following parameters to ensure you're not using a unsupported preview version of .NET:

### global.json
```
{
  "sdk": {
    "version": "8.0.403",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}

```

**Closed** 2024-10-16 21:30 UTC
Labels: needs reproduction
