### ISSUE TITLE
[BUG] IconTintColorBehavior to change TintColor at runtime not working

### ISSUE THREAD

**Issue by sesitosvdx** [CommunityToolkit/Maui#957] opened 2023-02-02 10:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Using .Net Maui Community Toolkit to change the TintColor at runtime.
DynamicResource is not working.

### Expected Behavior

DynamicResource works

### Steps To Reproduce

1. Create a new MAUI project
2. Install CommunityToolkit.Maui with version 4.0.0
3. Add the following code in MainPage.xaml, don't forget adding xmlns:mct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit" in the ContentPage property.

            `<Image Source="dotnet_bot.png"
                   SemanticProperties.Description="Cute dot net bot waving hi to you!"
                   HeightRequest="100"
                   HorizontalOptions="Center">
                <Image.Behaviors>
                    <xct:IconTintColorBehavior TintColor="Yellow" />
                </Image.Behaviors>
            </Image>

            <Image Source="dotnet_bot.png"
                   SemanticProperties.Description="Cute dot net bot waving hi to you!"
                   HeightRequest="100"
                   HorizontalOptions="Center">
                <Image.Behaviors>
                    <xct:IconTintColorBehavior TintColor="{StaticResource Cyan}" />
                </Image.Behaviors>
            </Image>

            <Image Source="dotnet_bot.png"
                   SemanticProperties.Description="Cute dot net bot waving hi to you!"
                   HeightRequest="100"
                   HorizontalOptions="Center">
                <Image.Behaviors>
                    <xct:IconTintColorBehavior TintColor="{DynamicResource Red}" />
                </Image.Behaviors>
            </Image>`

<img width="295" alt="image" src="https://user-images.githubusercontent.com/47418326/216304854-e470df46-5cc1-4979-8cbb-9513ba602154.png">

### Link to public reproduction project repository

https://github.com/sesitosvdx/MauiAppForTesting.App

### Environment

```markdown
- .NET MAUI CommunityToolkit: 4.0.0
- OS: Android API30
- .NET MAUI: 7.0.0.49
```

**Comment by rjspencer91** [comment] 2023-03-06 09:17
+1 to this

In the past I've experienced this issue when changing the ImageSource at runtime. Now it happens all the time, as detailed above

The only way I've found is to "bake" the colour into the source image and swap source images out, but this is really not ideal

**Comment by brminnick** [comment] 2023-03-06 16:45
`Behavior` in .NET MAUI don't have support for `ResourceDictionary` and thus do not support `StaticResource` or `DynamicResource`

In .NET MAUI, [`Behavior`](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/Interactivity/Behavior.cs#L10) inherits from `BindableObject`.

For a class to support `ResourceDictionary`, it needs to either inherit from [`VisualElement` where `public ResourceDictionary Resources { get; set; }` exists](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/VisualElement.cs#L770), or implement [`IResourceProvider`](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/IResourcesProvider.cs)

Closing because this is not a bug specific to the .NET MAUI Community Toolkit.

**Closed by brminnick** 2023-03-06 16:45 UTC
Labels: bug, unverified

**Comment by tolgraven** [comment] 2023-10-18 09:58
> `Behavior` in .NET MAUI does not have support for `ResourceDictionary` and thus do not support `StaticResource` or `DynamicResource`
> 
> In .NET MAUI, [`Behavior` inherits from `BindableObject`](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/Interactivity/Behavior.cs#L10).
> 
> For a class to support `ResourceDictionary`, it needs to either inherit from [`VisualElement` where `public ResourceDictionary Resources { get; set; }` exists](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/VisualElement.cs#L770), or implement [`IResourceProvider`](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/IResourcesProvider.cs).
> 
> Closing because this is not a bug specific to the .NET MAUI Community Toolkit.

These are a bunch of implementation details, you're missing the forest for the trees. The only thing important to me as a developer of an app being "upgraded" to Maui: the Xamarin effect has turned into a behavior and as a result apparently doesn't support DynamicResource. This is a very big regression for our use case, a large app with full support for dark mode and hence heavy use of the previous effect.
Please revisit whether having this as a behavior is really the way to go if it can't support something as essential for a modern real-life app as dynamic tinting based on centrally defined values. This isn't the 90s, nobody tints something HTML "Red" or "Blue", hehe.

More importantly, in the meantime, what is your recommended course of action? Bindings with a reference in BaseVM to a central color store populated directly off Application.Resources was my first thought, but this also yields a blank, hmm.
I'm guessing I'm missing something obvious here. How do we update our app without a ton of busywork or redoing manually what we've so far been able to do automatically?

**Comment by bijington** [comment] 2023-12-04 20:27
@tolgraven could you implement a static class that responds to the AppTheme changing and update it's values accordingly? Then you could bind to the values on that static class throughout.

**Comment by pictos** [comment] 2023-12-04 22:51
Didn't the AppThemeBinding work for this scenario?

**Comment by tolgraven** [comment] 2023-12-10 11:55
> Didn't the AppThemeBinding work for this scenario?

For some stuff yes. Works with StaticResource, but not DynamicResource. So as an example you have your defined base colors, but want to use a different color depending on dark mode, but also dark mode tweaks parts of your base scheme for contrast purposes (bumping luminosity primarily).
Maybe esoteric idunno, but at least me and my team aren't skilled enough to pull this off flawlessly without subtly adjusting colors and I can imagine we're not the only ones...

**Comment by tolgraven** [comment] 2023-12-10 12:02
> @tolgraven could you implement a static class that responds to the AppTheme changing and update it's values accordingly? Then you could bind to the values on that static class throughout.

We ended up using SimpleToolkit which has a tintable Icon component. Plus a ContentButton. Feels like both these should be part of the core palette of components really, not even MCT but core. So two steps off, but at least we got it solved :)
<img width="319" alt="Screenshot 2023-12-10 at 12 01 50" src="https://github.com/CommunityToolkit/Maui/assets/9143357/c55fe2ec-d08d-4f3c-a988-a4bd05616b1b">

**Comment by ganeshmeghale** [comment] 2024-05-08 05:13
> `Behavior` in .NET MAUI does not have support for `ResourceDictionary` and thus do not support `StaticResource` or `DynamicResource`
> 
> In .NET MAUI, [`Behavior` inherits from `BindableObject`](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/Interactivity/Behavior.cs#L10).
> 
> For a class to support `ResourceDictionary`, it needs to either inherit from [`VisualElement` where `public ResourceDictionary Resources { get; set; }` exists](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/VisualElement.cs#L770), or implement [`IResourceProvider`](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/IResourcesProvider.cs).
> 
> Closing because this is not a bug specific to the .NET MAUI Community Toolkit.

If someone is still looking for a cleaner workaround
have a look at this link - https://medium.com/@alpay18070005016/net-maui-icontintcolor-b54a74a41f19

**Comment by ganeshmeghale** [comment] 2024-05-08 05:18
> `Behavior` in .NET MAUI does not have support for `ResourceDictionary` and thus do not support `StaticResource` or `DynamicResource`
> 
> In .NET MAUI, [`Behavior` inherits from `BindableObject`](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/Interactivity/Behavior.cs#L10).
> 
> For a class to support `ResourceDictionary`, it needs to either inherit from [`VisualElement` where `public ResourceDictionary Resources { get; set; }` exists](https://github.com/dotnet/maui/blob/599e4798d22306f7c06cd8f80d50b0d14bf6c841/src/Controls/src/Core/VisualElement.cs#L770), or implement [`IResourceProvider`](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/IResourcesProvider.cs).
> 
> Closing because this is not a bug specific to the .NET MAUI Community Toolkit.


**A cleaner workaround for this would be something like this IMO:**
https://medium.com/@alpay18070005016/net-maui-icontintcolor-b54a74a41f19

**Comment by bijington** [comment] 2024-05-08 05:29
@ganeshmeghale its a nice approach to reducing the amount of XAML that has to be written each time but it doesn't provide a workaround for this issue. The issue is specifically around the use of `DynamicResource`

**Comment by Alexgoon** [comment] 2024-06-15 10:33
It's unfortunate that IconTintColorBehavior doesn't work with AppThemeBinding. This appears to be one of the most fundamental usage scenarios.

**Comment by AndyNetDuma** [comment] 2024-07-02 17:09
For those that come across this in the future you can mostly solve the problem by creating an image component wrapper. This is a basic version, just place this CS file somewhere (no xaml required) and replace the namespace. Instead of using a Behaviour in xaml it just adds the TintColor property directly to the component. Then it automatically manages the behaviour based on the colour you select. No extra libraries or significant code pattern changes.

I hope this helps others that run into the same issue.

```cs
using CommunityToolkit.Maui.Behaviors;

namespace REPLACE_ME
{
    public class TintableImage: Image
    {
        public static readonly BindableProperty TintColorProperty = BindableProperty.Create(nameof(TintColor), typeof(Color), typeof(TintableImage), null, propertyChanged: UpdateTintColour);

        public Color TintColor
        {
            get => (Color)GetValue(TintColorProperty);
            set => SetValue(TintColorProperty, value);
        }

        public TintableImage()
        {
            this.Behaviors.Add(new IconTintColorBehavior());
            if (TintColor != null)
            {
                SetTint(TintColor);
            }
        }

        private static void UpdateTintColour(object sender, object oldValue, object newValue)
        {
            if (sender is TintableImage image && newValue is Color color)
            {
                image.SetTint(color);
            }
        }

        private void SetTint(Color color) {
            // Set the tint color
            this.Behaviors.First().SetValue(IconTintColorBehavior.TintColorProperty, color);
        }
    }
}
```

**Comment by TheSundayDev** [comment] 2024-07-04 23:19
thanks AndyNetDuma for sharing your solution! I don't know why but just on IOS sometimes the 'fake' RefColor label works and sometimes doesn't work... randomly.

**Comment by TheSundayDev** [comment] 2024-07-05 13:07
hi all,
I tried all solutions and they work but on IOS just randomly. Sometimes the color is updated and sometimes not.  I don't know why. I'm binding the color to a 'fake' label as
<Label Grid.Row="0" Grid.Column="0" x:Name="RefColor" BackgroundColor="{DynamicResource BackgroundColorTop}" IsEnabled="False" IsVisible="False" />

**Comment by AndyNetDuma** [comment] 2024-07-05 13:40
> hi all, I tried all solutions and they work but on IOS just randomly. Sometimes the color is updated and sometimes not. I don't know why. I'm binding the color to a 'fake' label as
> 
> `<Label Grid.Row="0" Grid.Column="0" x:Name="RefColor" BackgroundColor="{DynamicResource BackgroundColorTop}" IsEnabled="False" IsVisible="False" />`

I'm sorry I don't follow your question. Are you saying when you bind the colour to the label it works but not with the TintableImage component?
I have been using it in iOS and I haven't noticed any issues in the past few days. It hasn't gone to our SQA yet so I can't say it works with 100% confidence but it seems fine.

If your label doesn't work I suggest you check your update pattern for changing the resource dictionary. You should be doing it on the main thread (use MainThread.BeginInvokeOnMainThread). We use this pattern:
```cs
ICollection<ResourceDictionary> mergedDictionaries = Application.Current.Resources.MergedDictionaries;

if (mergedDictionaries != null)
{
    mergedDictionaries.Clear();

    // This crashes
    mergedDictionaries.Add((ResourceDictionary)Activator.CreateInstance(theme.ResourceType));
    mergedDictionaries.Add(new GlobalStyles());
}
```
It's worth noting I'm not sure this is right. It worked perfectly on xamarin forms however in maui it seems to create a single tick of the values being null. For our app that isn't a problem and the component I wrote should be fine with that behaviour but it's worth noting.

If your label works but TintableImage doesn't then I suggest you put a log into SetTint. If you see the log message when expected make sure your colour is valid. If the colour is valid then it's likely something inside the behaviour. Otherwise it's hard to say so you will have to debug it a bit higher.

**Comment by TheSundayDev** [comment] 2024-07-06 16:44
hi,
let me explain better, sorry.
I tried many workaround, the fake label proposed in this thread, your code and they are working but not always. I think it's an issue on the Behaviors becuse sometime the color is correct, sometime not, eg:
- the color is not correct (the one visible is the original one)
- the color is correct but if i go to a new page and then I come back the color is wrong (is the original color of the image)
The problem is that it's randomly.
Seems that sometimes the Behaviors is not working... or maybe I'm doing something wrong....
This happens just on ios.
thanks again

**Comment by AndyNetDuma** [comment] 2024-07-10 09:39
> hi, let me explain better, sorry. I tried many workaround, the fake label proposed in this thread, your code and they are working but not always. I think it's an issue on the Behaviors becuse sometime the color is correct, sometime not, eg:
> 
> * the color is not correct (the one visible is the original one)
> * the color is correct but if i go to a new page and then I come back the color is wrong (is the original color of the image)
>   The problem is that it's randomly.
>   Seems that sometimes the Behaviors is not working... or maybe I'm doing something wrong....
>   This happens just on ios.
>   thanks again

I still don't really understand. I'm pretty confident it's nothing to do with this image or behaviour. You are most likely getting tripped up by misconfiguration of your dynamic resources (themes) or maybe hot reload? Either way this isn't the best place to diagnose it so you are probably better off having a real time conversation on the programming discords/slacks out there

Best of luck resolving your issue

**Comment by AncientLust** [comment] 2024-07-20 14:08
The more reasonable question here is not "Why `toolkit:IconTintColorBehavior` doesn't work with DynamicResources, but "Why in hell it's not a part of core functionality"? Literally any app which have black/white theme will stuble into this issue. Jesus..

**Comment by AncientLust** [comment] 2024-07-20 14:09
The more reasonable question here is not "Why toolkit:IconTintColorBehavior doesn't work with DynamicResources?", but "Why in hell it's not a part of core functionality?". Literally any app which have black/white theme will stuble into this issue. Jesus..

**Comment by AncientLust** [comment] 2024-07-20 14:21
> Had same issue but I resolved it by referencing other element (You can probably make zombie elements just to use them as color reference or match it with others)
> 
> `<Label x:Name="Ref" BackgroundColor="{DynamicResource MyColor}" IsEnabled="False" IsVisible="False" />`
> 
> can be any element for example `Label`
> 
> and then on your image `<toolkit:IconTintColorBehavior TintColor="{Binding Source={x:Reference Ref}, Path=BackgroundColor}" />`

@Kadlerz showed not all heroes wear a cape.

**Comment by info-ajdragasa** [comment] 2024-07-23 05:45
> Had same issue but I resolved it by referencing other element (You can probably make zombie elements just to use them as color reference or match it with others)
> 
> `<Label x:Name="Ref" BackgroundColor="{DynamicResource MyColor}" IsEnabled="False" IsVisible="False" />`
> 
> can be any element for example `Label`
> 
> and then on your image `<toolkit:IconTintColorBehavior TintColor="{Binding Source={x:Reference Ref}, Path=BackgroundColor}" />`

The only thing the works. Thank you

**Comment by TheSundayDev** [comment] 2024-07-28 16:57
Just to share my issue that I have only on IOS.
I have a page called MyPage with 2 controls:

```
<Label x:Name="RefColor" BackgroundColor="{DynamicResource MyColor}" IsEnabled="False" IsVisible="False" />
<ImageButton  BackgroundColor="Transparent" Source="close.png" WidthRequest="30" HeightRequest="30" Padding="0" Command="{Binding GoToPreviousPageCommand}">
    <ImageButton.Behaviors>
        <toolkit:IconTintColorBehavior TintColor="{Binding Source={x:Reference RefColor}, Path=BackgroundColor}" />
    </ImageButton.Behaviors>
</ImageButton>
```

Now if I call Navigation.PushModalAsync(new MyPage(), true); sometimes the IconTintColorBehavior is applied, sometimes not.
Any idea?
thanks a lot

**Comment by TheSundayDev** [comment] 2024-08-01 12:39
thanks for your response.
Already tried:
- a label without IsEnabled="False" and  IsVisible="False"
- border and others elements as rerefence (instead of label)

I think that Behaviors are not always applied on IOS  due to a bug when a page is called with PushModalAsync but I'm asking if I'm the only one with this issue.
thanks a lot!

**Comment by xibeat** [comment] 2024-09-10 18:06
New Day and another setback of using maui. Framework so good that deserves a class action lawsuit. Just kidding but this issue is driving me crazy.
