### ISSUE TITLE
[BUG] [iOS] Toast: AlertView not finding the KeyWindow

### ISSUE THREAD

**Issue by softlion** [CommunityToolkit/Maui#645] opened 2022-09-20 15:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Crashing on iOS device

```
System.InvalidOperationException: KeyWindow is not found
   at CommunityToolkit.Maui.Core.Views.AlertView.get_ParentView() in /_/src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs:line 17
   at CommunityToolkit.Maui.Core.Views.Alert..ctor() in /_/src/CommunityToolkit.Maui.Core/Views/Alert/Alert.macios.cs:line 17
   at CommunityToolkit.Maui.Core.Views.PlatformToast..ctor(String message, UIColor backgroundColor, CGRect cornerRadius, UIColor textColor, UIFont font, Double characterSpacing, NFloat padding) in /_/src/CommunityToolkit.Maui.Core/Views/Toast/PlatformToast.macios.cs:line 28
   at CommunityToolkit.Maui.Alerts.Toast.ShowPlatform(CancellationToken token) in /_/src/CommunityToolkit.Maui/Alerts/Toast/Toast.macios.cs:line 53
   at CommunityToolkit.Maui.Alerts.Toast.Show(CancellationToken token) in /_/src/CommunityToolkit.Maui/Alerts/Toast/Toast.shared.cs:line 77
```

### Expected Behavior

Don't crash.

### Steps To Reproduce

```
using var t = Toast.Make("Something to say", CommunityToolkit.Maui.Core.ToastDuration.Long);
await t.Show();
```

### Link to public reproduction project repository

(tbd)

### Environment

```markdown
- .NET MAUI CommunityToolkit: 1.3.0
- OS: iOS 15
- .NET MAUI: 6.0.536/6.0.400
```

**Comment by VladislavAntonyuk** [comment] 2022-09-20 15:37
The Toast was not able to find the ParentView. where do you call this method? please add link to public reproduction project repository

**Comment by J-Swift** [comment] 2022-09-22 18:54
Interestingly, if you accept the dialog, but then cancel the auth flow, Toast works fine to show my "auth failed" popup. So not sure if its a timing bug or something to do with there being multiple scenes at the point of the auth confirmation prompt. I noticed we explicitly pull the first scene here https://github.com/CommunityToolkit/Maui/blob/6b0f4e6a687f80436b4d6abc78bcd9617d84f699/src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs#L19, so maybe that needs to be tweaked.

**Comment by pictos** [comment] 2022-09-22 19:07
@J-Swift are you able to provide a small sample to reproduce? if so, please upload it to github and share the link, we don't download zip files anymore

**Comment by VladislavAntonyuk** [comment] 2022-09-22 19:13
I think it will not work with your implementation as Popup window no more exist after you click cancel button. You should call toast on another parent view

**Comment by VladislavAntonyuk** [comment] 2022-09-23 06:42
I can propose the next solution:
Make the ParentView virtual so you can override it with your own implementation.

**Comment by softlion** [comment] 2022-09-23 09:39
> I can propose the next solution:
> Make the ParentView virtual so you can override it with your own implementation.

Don’t do that.
Look at the code of this simple library, I worked around this issue:

https://github.com/softlion/UserInteraction

**Comment by VladislavAntonyuk** [comment] 2022-09-24 14:34
@softlion are you pointing at Platform.GetCurrentUIViewController();?

**Comment by VladislavAntonyuk** [comment] 2022-09-28 11:33
@softlion I was not able to reproduce the issue. without the sample we cannot move forward

**Comment by softlion** [comment] 2022-09-28 16:24
> @softlion, @J-Swift I was not able to reproduce the issue. without the sample, we cannot move forward

Of course you can't repro, it's a timing issue that happens on specific timings that I can not repro. I posted that as I stumbled on it.

**Comment by J-Swift** [comment] 2022-09-28 17:23
The ASWebAuthenticationSession is 100% reproducible every time you press cancel, but I will need to get an example outside of my main app that shows this.

**Comment by J-Swift** [comment] 2022-09-28 22:48
OK, I think this should be a repro: https://github.com/J-Swift/maui-popup-repro. After you click login, then cancel, there will be a message logged about the KeyWindow exception (see `NotifyService` for the `catch`).

Note that you want to press cancel on the _initial_ popup that asks for permission, not the subsequent webview.  See screenshot for the one I'm talking about.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/734158/192901980-e26ba1e9-24e4-4df1-ab6e-ed713c93c104.png">

**Comment by J-Swift** [comment] 2022-09-28 22:50
I should also add, the reason I say to press _this_ cancel is because the popup actually works if you press cancel on the _next_ screen. So I think it has to do with the ASWebAuthenticationSession taking over the KeyWindow for its popup.

**Comment by VladislavAntonyuk** [comment] 2022-10-01 10:56
https://user-images.githubusercontent.com/33021114/193406255-85c81a8d-7e2b-4188-8c5e-46ce72ec3653.mov

I still cannot reproduce it. (The only difference I update the Core lib to version 1.3.0 - it was 1.1.0)

**Comment by J-Swift** [comment] 2022-10-01 13:48
Yep, confirmed that 1.3.0 fixed my repro. Will verify on my main app on Monday, but I dont see why it wouldnt work there too. Reading through the release notes, looks like there was a KeyWindow fix in 1.2.0 : D

**Comment by VladislavAntonyuk** [comment] 2022-10-01 14:06
yes, the fix PR: https://github.com/CommunityToolkit/Maui/pull/502/files
Closing it. feel free to reopen if you find the issue again

**Closed by VladislavAntonyuk** 2022-10-01 14:06 UTC
Labels: bug, unverified, needs reproduction

**Comment by halfninja** [comment] 2023-10-27 09:30
Just to help anyone else who might arrive here after doing the same thing as me - you can get this error if you try to make a Toast too early. I was trying to show Toast in a ContentView's constructor (probably not a good place for it anyway), fixed by moving it inside a `Loaded` event callback.
