### ISSUE TITLE
[Proposal] StatusBarEffect

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui#85] opened 2021-09-26 19:15 UTC
# StatusBarEffect

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [ ] macOS Support
  * [ ] Windows Support
* [x] Unit Tests: Not Started
* [x] Sample
* [x] Documentation

## Summary
[summary]: #summary

Set the color and style of the status bar

## Detailed Design
[design]: #detailed-design

### StatusBarEffect.shared.cs

```cs
public class StatusBarEffect : RoutingEffect
{
  public static readonly BindableProperty ColorProperty;
  public static readonly BindableProperty StyleProperty;
  
  public static Color GetColor(BindableObject bindable);
  public static StatusBarStyle GetStyle(BindableObject bindable);
}
```

## Usage Syntax
[usage]: #usage-syntax

### XAML Usage

```xml
<ContentPage local:StatusBarEffect.Color="Blue">

</ContentPage>
```

### C# Usage

```cs
class MyPage : ContentPage
{
  public MyPage()
  {
     StatusBarEffect.SetColor(this, Colors.Black);
  }
}
```

**Comment by pictos** [comment] 2021-10-05 02:26
We should hold this until this  https://github.com/dotnet/maui/pull/2049 get merged or closed

**Comment by maxkoshevoi** [comment] 2021-10-05 07:26
Would like to implement this, in case issue is unblocked

**Comment by maxkoshevoi** [comment] 2022-01-30 10:20
dotnet/maui#2049 is now closed, can we move forward with thins issue?

**Comment by pictos** [comment] 2022-02-06 17:13
This is still blocked by #124

**Comment by KSemenenko** [comment] 2022-08-15 15:13
any updates here?

**Comment by pictos** [comment] 2022-08-15 15:54
@KSemenenko not yet. I'll circle back on .NET MAUI team to see if this will be in the framework or not

**Comment by EPS-Lac** [comment] 2022-09-07 13:45
Hi @pictos, what's the state on this one?

I'm a bit confused with the different issues here and in the MAUI project...
Are you going to implement it in the CommunityToolkit or will the MAUI team add it directly in MAUI?
And has any work on it already started?

I'll need the feature for a customer project...
So if nothing has been implemented yet (nor is in the pipeline to do so shortly), any tips on how to implement it myself?
I need to set it dynamically (in case the user switches themes on runtime), currently just for iOS and Android.

Thanks in advance :)
Any info/help is appreciated!

**Comment by pictos** [comment] 2022-09-07 14:07
Hey @EPS-Lac, it's WIP I should have a PR by the end of this week. I hope this can be in the next stable release, if don't I can guide you on how to implement the feature or how to use the nuget generated by the PR.

**Comment by jfversluis** [comment] 2022-09-07 14:14
Let's make sure we wait for this one for the next release. A lot of people are waiting for this one. Unless something really weird happens, then we'll make a release first while we work on this.

**Comment by maxkoshevoi** [comment] 2022-09-07 14:34
> [Would like to implement this, in case issue is unblocked](https://github.com/CommunityToolkit/Maui/issues/85#issuecomment-934140720)

@pictos Oh, I thought, I would be assigned to port this one..

**Comment by jfversluis** [comment] 2022-09-07 15:04
Probably since it has been a while we forgot to check if you were still available. On to the next one! 😉

**Comment by KSemenenko** [comment] 2022-09-07 15:41
good news :) waiting for it :)

**Comment by maxkoshevoi** [comment] 2022-09-07 15:57
@jfversluis How about https://github.com/CommunityToolkit/Maui/issues/103? =)

**Comment by pictos** [comment] 2022-09-09 02:07
The PR linked to this issue will not implement the `StatusBarStyle`, and it's due to an API change on Apple.

The current way to do this is overriding the preferredStatusBarStyle and we can't do that here... The change should happen in .NET MAUI itself providing a way to control it.

More info [here](https://sarunw.com/posts/how-to-set-status-bar-style/#style-based-on-view-controllers).

IF anyone knows an implementation that works, let me know

**Comment by KSemenenko** [comment] 2022-09-09 07:26
``` cs
private DisplayOrientation _lastOrientation;

protected override Window CreateWindow(IActivationState activationState)
{
    Window window = base.CreateWindow(activationState);
    window.Created += (s, e) => { UpdateStatusBarColor(); };
    window.Destroying += (s, e) =>
    {
        NSNotificationCenter.DefaultCenter.RemoveObserver(new NSString("UIDeviceOrientationDidChangeNotification"));
    };
    MAUICallback.OnBackgroundColorChanged += MAUICallbackOnOnBackgroundColorChanged;
    return window;
}

private void UpdateStatusBarColor()
{
    UIView statusBar;
    if (UIDevice.CurrentDevice.CheckSystemVersion(13, 0))
    {
        int tag = 4567890;
        UIWindow window = UIApplication.SharedApplication.Delegate.GetWindow();
        statusBar = window.ViewWithTag(tag);
        if (statusBar == null || statusBar.Frame != UIApplication.SharedApplication.StatusBarFrame)
        {
            statusBar = statusBar ?? new(UIApplication.SharedApplication.StatusBarFrame);
            statusBar.Frame = UIApplication.SharedApplication.StatusBarFrame;
            statusBar.Tag = tag;
            window.AddSubview(statusBar);
        }
        

        var uiStyle = MAUICallback.StatusBarStyle switch
        {
            StatusBarStyle.LightContent => UIStatusBarStyle.LightContent,
            StatusBarStyle.DarkContent => UIStatusBarStyle.DarkContent,
            _ => UIStatusBarStyle.Default
        };
        UIApplication.SharedApplication.SetStatusBarStyle(uiStyle, false);
    }
    else
    {
        statusBar = UIApplication.SharedApplication.ValueForKey(new NSString("statusBar")) as UIView;
    }

    if (statusBar != null)
    {
        // TODO Make this color come from somewhere shared
        statusBar.BackgroundColor = Color.FromArgb(MAUICallback.CurrentColor).ToUIColor();
        
    }

    NSNotificationCenter.DefaultCenter.AddObserver(new NSString("UIDeviceOrientationDidChangeNotification"), NotificationCenter =>
    {
        // This gets called multiple times on iOS, let's optimize a little bit
        if (_lastOrientation != DeviceDisplay.MainDisplayInfo.Orientation)
        {
            UpdateStatusBarColor();
            _lastOrientation = DeviceDisplay.MainDisplayInfo.Orientation;
        }
    });
}
```

**Comment by pictos** [comment] 2022-09-09 14:02
@KSemenenko, first of the all thanks for the code snippet. 
The StatusBarStyle get updated? And what place do you override your `CreateWindow` method?

**Comment by KSemenenko** [comment] 2022-09-09 15:40
this is in App.xaml.cs, I also will sent you all my file:
``` cs
using System.Globalization;
using Winkt.Mobile.Api.Abstractions;
using Winkt.Mobile.Helpers;
using Winkt.Mobile.Managers;
using Winkt.Mobile.Managers.Interfaces;
using Xamarin.CommunityToolkit.Effects;
#if __IOS__
using Foundation;
using Microsoft.Maui.Controls.Compatibility.Platform.iOS;
using UIKit;
#endif

namespace Winkt.Mobile;

public partial class App : Application
{
    public App()
    {
        InitializeComponent();
        MainPage = new MainPage();
    }

    private void MAUICallbackOnOnBackgroundColorChanged(object sender, string e)
    {
#if __IOS__
        UpdateStatusBarColor();
#endif
    }

    protected override void OnStart()
    {
        WinktStaticHelper.GenerateDeviceID();

        var apiClient = WinktServiceProvider.GetService<IApiClientService>();
        apiClient.AuthApiClient.SetAuthToken(AppSettings.SessionId);
    }

    protected override void OnResume()
    {
        var manager = WinktServiceProvider.GetService<IAuthManager>();
        _ = manager.ResumeSession();
    }

    protected override void OnSleep()
    {
        var manager = WinktServiceProvider.GetService<IAuthManager>();
        _ = manager.PauseSession();
    }

#if __IOS__
    private DisplayOrientation _lastOrientation;

    protected override Window CreateWindow(IActivationState activationState)
    {
        Window window = base.CreateWindow(activationState);
        window.Created += (s, e) => { UpdateStatusBarColor(); };
        window.Destroying += (s, e) =>
        {
            NSNotificationCenter.DefaultCenter.RemoveObserver(new NSString("UIDeviceOrientationDidChangeNotification"));
        };
        MAUICallback.OnBackgroundColorChanged += MAUICallbackOnOnBackgroundColorChanged;
        return window;
    }

    private void UpdateStatusBarColor()
    {
        UIView statusBar;
        if (UIDevice.CurrentDevice.CheckSystemVersion(13, 0))
        {
            int tag = 4567890;
            UIWindow window = UIApplication.SharedApplication.Delegate.GetWindow();
            statusBar = window.ViewWithTag(tag);
            if (statusBar == null || statusBar.Frame != UIApplication.SharedApplication.StatusBarFrame)
            {
                statusBar = statusBar ?? new(UIApplication.SharedApplication.StatusBarFrame);
                statusBar.Frame = UIApplication.SharedApplication.StatusBarFrame;
                statusBar.Tag = tag;
                window.AddSubview(statusBar);
            }
            

            var uiStyle = MAUICallback.StatusBarStyle switch
            {
                StatusBarStyle.LightContent => UIStatusBarStyle.LightContent,
                StatusBarStyle.DarkContent => UIStatusBarStyle.DarkContent,
                _ => UIStatusBarStyle.Default
            };
            UIApplication.SharedApplication.SetStatusBarStyle(uiStyle, false);
        }
        else
        {
            statusBar = UIApplication.SharedApplication.ValueForKey(new NSString("statusBar")) as UIView;
        }

        if (statusBar != null)
        {
            // TODO Make this color come from somewhere shared
            statusBar.BackgroundColor = Color.FromArgb(MAUICallback.CurrentColor).ToUIColor();
            
        }

        NSNotificationCenter.DefaultCenter.AddObserver(new NSString("UIDeviceOrientationDidChangeNotification"), NotificationCenter =>
        {
            // This gets called multiple times on iOS, let's optimize a little bit
            if (_lastOrientation != DeviceDisplay.MainDisplayInfo.Orientation)
            {
                UpdateStatusBarColor();
                _lastOrientation = DeviceDisplay.MainDisplayInfo.Orientation;
            }
        });
    }
#endif
}
```

In mine implementation, I have some static class, and event, so it's not best solution for sure.

**Comment by KSemenenko** [comment] 2022-09-09 15:46
as you can see, the problem is that this thing works on current page.
as in Xamarin.Forms the problem is the same.
To completely solve this issue, we need to put these 2 properties in Page class.
and then when page changes its IsVisible property (or becomes visible) then we will need to applay these properties to paint the status bar.

**Comment by pictos** [comment] 2022-09-09 16:17
well, changing the status bar color works like a charm, with the current implementation that I've for the PR... The StyleBar doesn't, so I can't change the DarkContent to LightContent... From my research is because apple just allows the dynamic in ViewController, when you override the `preferredStatusBarStyle` method. But we can't do that here, this need to be done on .NET MAUI side.
I'll try this window implementation and see how that works and see if I can abstract that here.
Thanks a lot for all this input @KSemenenko

**Comment by KSemenenko** [comment] 2022-09-09 17:27
Maybe it's time to implement our Page? base on Maui Page? 
and put all logic there?

**Comment by pictos** [comment] 2022-09-09 21:15
@KSemenenko I tested your code on my end... And the status bar content keeps in white color. So this doesn't work as well or did something wrong :/
Do you have a project that you can share ?

**Comment by KSemenenko** [comment] 2022-09-10 08:56
this is my original PR 
https://github.com/xamarin/Xamarin.Forms/pull/8298

I will create demo app today, because for me this issue is big blocker, and I will help you as much as need to have this functional :)

**Comment by KSemenenko** [comment] 2022-09-10 11:00
@pictos  did you add into info.plist
```
<key>UIViewControllerBasedStatusBarAppearance</key>
 <false/>
```

**Comment by KSemenenko** [comment] 2022-09-10 14:25
@pictos  it will take more time, it my first time for custom rendered for MAUI,  maybe you have some code, so I can working with it?

**Comment by KSemenenko** [comment] 2022-09-10 14:57
[Maui-StatusBarStule.zip](https://github.com/CommunityToolkit/Maui/files/9540663/Maui-StatusBarStule.zip)
done  iOS works

**Comment by KSemenenko** [comment] 2022-09-10 15:26
[ios_andoird.zip](https://github.com/CommunityToolkit/Maui/files/9540745/ios_andoird.zip)
iOS + and/or
I love MAUI :)

so for iOS this is the issue

```
<key>UIViewControllerBasedStatusBarAppearance</key>
 <false/>
```

**Comment by pictos** [comment] 2022-09-10 16:47
Hey @KSemenenko I could confirm it works at runtime. Thanks for the snippet

**Comment by KSemenenko** [comment] 2022-09-10 17:23
@pictos in my pr you can also find uwp code.
Anyway maybe you need some help?

**Comment by pictos** [comment] 2022-09-10 17:24
@KSemenenko yeah, we are porting this feature from XCT, which is based on your Forms PR. The UWP doesn't work because on Maui we use the WinUI3 APIs, and they didn't implement the ability to change the status bar color manually.

**Comment by KSemenenko** [comment] 2022-09-10 17:37
@pictos realy? Omg….. 
it least we will have it for iOS and Android :)

if you need some help with anything just ping me

**Comment by pictos** [comment] 2022-09-10 17:39
Yeap
this [line](https://github.com/xamarin/XamarinCommunityToolkit/blob/f3a42515611b6c4c0c7db684c09cdb5120977b64/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/StatusBar/PlatformStatusBarEffect.uwp.cs#L58) throws an exception. And this is the related issue.
- https://github.com/microsoft/microsoft-ui-xaml/issues/2509

**Comment by KSemenenko** [comment] 2022-09-10 18:49
We released several apps for uwp, but no one relay use it.
So, we can wait :)

**Comment by KSemenenko** [comment] 2022-09-10 18:54
But the most important thing is that this effect is performed when the visibility of the page changes.

Especially for shell and tabbedpage. Because this is a global application style. And every page will overwrite it. And when you navigate back, if you don't call this method, it will leave the color from the previous page.

**Comment by pictos** [comment] 2022-09-10 22:32
@KSemenenko for now we will leave the responsibility to trigger that to the dev. If that becomes something very necessary we can create an enhancement ticket and cache the value

**Comment by KSemenenko** [comment] 2022-09-11 07:06
> @KSemenenko for now we will leave the responsibility to trigger that to the dev. If that becomes something very necessary we can create an enhancement ticket and cache the value

Then any ui element can trigger this changes

**Closed** 2022-09-27 11:58 UTC
Labels: proposal, champion, documentation approved, in-progress
