### ISSUE TITLE
[BUG] Maps gives exceptions

### ISSUE THREAD

**Issue by eduardoagr** [CommunityToolkit/Maui#2412] opened 2024-12-24 14:52 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [x] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

This morning, when I updated the package, I got this error message

`StackTrace = "   at CommunityToolkit.Maui.Maps.Handlers.MapHandlerWindows.<>c__DisplayClass17_0.<<CallJSMethod>b__0>d.MoveNext()\r\n   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)\r\n   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()", Source = "CommunityToolkit.Maui.Maps", Message = "A method was called at an unexpected time.\r\n\r\nExecuteScriptAsync(): Failed because a valid CoreWebView2 is not present. Make sure one was created, for example by calling EnsureCoreWebView2Async() API.", InnerException = null, HelpLink = null, HResult = -2147483634, Data = Count = 6`

### Expected Behavior

that works

### Steps To Reproduce

Create an app with Maui
Installed the community lootkit map
Run in Windows

### Link to public reproduction project repository

none

### Environment

```markdown
- .NET MAUI CommunityToolkit: 10.0.0
- OS: Windows
- .NET MAUI: 9
```

**Comment by bijington** [comment] 2024-12-24 15:02
I'll close this as it's a duplicate of https://github.com/CommunityToolkit/Maui/issues/2407

**Closed by bijington** 2024-12-24 15:02 UTC
Labels: bug, unverified, needs reproduction
