### ISSUE TITLE
[BUG] Snackbar messages don't anchor properly on iOS

### ISSUE THREAD

**Issue by KeithBoynton** [CommunityToolkit/Maui#1884] opened 2024-05-15 19:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

When anchoring snackbar messages to a UI element on iOS they are not getting anchored above the specified UI element as would be expected. However, on Android they are anchored correctly.

iOS not working, it should be displayed above the button:
![iOSScreenshot](https://github.com/CommunityToolkit/Maui/assets/39023169/18823866-ac06-404e-a244-c3c997f29bf8)

### Expected Behavior

I would expect the snackbar message to be displayed just above the UI element it has been anchored to but on iOS it is displayed in the same (default) place as when no anchor is provided.

Andoid working as expected, above the button:
![AndroidScreenshot](https://github.com/CommunityToolkit/Maui/assets/39023169/7086e8ab-fb40-4008-b00f-c5988a8a6606)

### Steps To Reproduce

1. Clone the attached repository and run the solution on Android.
2. Click the button and observe the snackbar message being displayed correctly.
3. Run the solution on iOS
4. Click the button and observe the snackbar message NOT being displayed correctly

### Link to public reproduction project repository

https://bitbucket.org/KeithBoynton/snackbar-anchor/src/master/

### Environment

```markdown
- .NET MAUI CommunityToolkit.Maui: 9.0.0
- .NET MAUI: 8.0.21
```

**Comment by cat0363** [comment] 2024-05-17 07:28
@KeithBoynton , Is the behavior you expect below?

<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/57e075ad-b8fa-4937-bce6-ca9b870cf9e8"/>

So, if Anchor is placed at the top of the screen, which of the following is the expected behavior?

[Case 1]

<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/732d3706-de48-480e-8af3-cfce5c8caeea"/>

[Case 2]

<img width="300" src="https://github.com/CommunityToolkit/Maui/assets/125236133/cb6e45c6-cfec-4c2d-841c-566d93a9695c"/>

If Anchor is inside the scroll view, case 2 will behave as follows.

https://github.com/CommunityToolkit/Maui/assets/125236133/21071bcb-324a-477d-954b-3b4a3ba4c0df

Both require code modifications on the Community Toolkit side.
You might want to ask why the snackbar is displayed at the bottom, as it is unclear whether it is intentionally displayed at the bottom or if it is a bug.

**Comment by KeithBoynton** [comment] 2024-05-17 15:28
Thanks for the quick reply @cat0363 
Yes the behaviour you illustrated in the first image is what I would expect, that's how it behaves on Android.

Case 2 looks correct if the element being anchored to is at the top of the screen, although I hadn't considered that as I'm not anchoring to an element at the top of the screen. But if I was I imagine that's what I'd want. Your illustration for when it's in a scroll view looks correct too.

Thanks again!

**Comment by cat0363** [comment] 2024-05-20 05:28
@KeithBoynton , Thank you for your reply.
When I investigated the behavior of Android, I found that Android behaved in Case 1.
Since Android cannot behave like Case 2, I think iOS will have no choice but to behave like Case 1.
I think Case 2 is preferable, but it seems like we have no choice but to adapt it to Case 1.

By the way, Case 1 can be implemented by making the following changes.
It can be fixed by changing just one line.

[src\CommunityToolkit.Maui.Core\Views\Alert\AlertView.macios.cs]

	void ConstraintInParent()
	{
		_ = Container ?? throw new InvalidOperationException($"{nameof(AlertView)}.{nameof(Initialize)} not called");

		const int defaultSpacing = 10;
		if (AnchorView is null)
		{
			this.SafeBottomAnchor().ConstraintEqualTo(ParentView.SafeBottomAnchor(), -defaultSpacing).Active = true;
			this.SafeTopAnchor().ConstraintGreaterThanOrEqualTo(ParentView.SafeTopAnchor(), defaultSpacing).Active = true;
		}
		else
		{
			this.SafeBottomAnchor().ConstraintEqualTo(AnchorView.SafeBottomAnchor(), -AnchorView.Frame.Height).Active = true;
		}

		this.SafeLeadingAnchor().ConstraintGreaterThanOrEqualTo(ParentView.SafeLeadingAnchor(), defaultSpacing).Active = true;
		this.SafeTrailingAnchor().ConstraintLessThanOrEqualTo(ParentView.SafeTrailingAnchor(), -defaultSpacing).Active = true;
		this.SafeCenterXAnchor().ConstraintEqualTo(ParentView.SafeCenterXAnchor()).Active = true;

		Container.SafeLeadingAnchor().ConstraintEqualTo(this.SafeLeadingAnchor(), defaultSpacing).Active = true;
		Container.SafeTrailingAnchor().ConstraintEqualTo(this.SafeTrailingAnchor(), -defaultSpacing).Active = true;
		Container.SafeBottomAnchor().ConstraintEqualTo(this.SafeBottomAnchor(), -defaultSpacing).Active = true;
		Container.SafeTopAnchor().ConstraintEqualTo(this.SafeTopAnchor(), defaultSpacing).Active = true;
	}

**Comment by cat0363** [comment] 2024-05-20 08:04
I forgot to mention this, but in the case of Android, if you specify an anchor for the Snackbar using the SetAnchorView method, the Snackbar will be displayed above the Anchor.

https://developer.android.com/reference/com/google/android/material/snackbar/BaseTransientBottomBar?_gl=1*13uplkd*_up*MQ..*_ga*MTMxMjg4Mjg0OC4xNzE2MTkxMjIz*_ga_6HH9YJMN9M*MTcxNjE5MTIyMy4xLjAuMTcxNjE5MTIyMy4wLjAuMA..#setAnchorView(int)

For this reason, it is not possible to display the Snackbar below Anchor on Android.

The other day, I showed a pattern for Case 2, but Android cannot support Case 2, so if it is a pattern for Case 1, I can create a PR.
If there is no problem with the pattern in Case 1 and you need to create a PR, please contact me.
I will leave it up to the Community Toolkit members to decide what to do.

**Comment by raginmari** [comment] 2024-05-23 14:21
The fact that the snackbar does not properly "stack" on top of its `AnchorView` on iOS is [caused by this line](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs#L70): it mistakes the "bottom" anchor for the "top" anchor which _should_ be used because contrary to the default case when the snackbar is positioned _inside_ the window, we want the snackbar to be positioned _outside_ of (and above) the anchor view.

**Comment by brminnick** [comment] 2024-05-23 15:40
Thanks @raginmari! Could you submit a PR with the fix?

**Closed** 2024-05-27 03:30 UTC
Labels: bug, unverified, area/alerts
