### ISSUE TITLE
[BUG] Expander wrapped inside ScrollView doesn't scroll on iOS

### ISSUE THREAD

**Issue by andreeabuzuriu11** [CommunityToolkit/Maui#816] opened 2022-12-08 13:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Expander (from MAUI Community Toolkit) is wrapped inside ScrollView, the scroll is not possible on iOS. On Android it works fine.

I checked this sample when implementing it: https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml. Here the Expander is also created in a ScrollView.

### Expected Behavior

Scroll is possible when having an Expander with multiple items on iOS too.

### Steps To Reproduce

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            BindableLayout.ItemsSource="{Binding ExpandableHeaders}">
            <BindableLayout.ItemTemplate>
                <DataTemplate x:DataType="sampleExpander:HeaderItem">
                    <mct:Expander>
                        <mct:Expander.Header>
                            <Label Text="{Binding Title}"
                                   FontSize="16"/>
                        </mct:Expander.Header>
                        <mct:Expander.Content>
                            <VerticalStackLayout BackgroundColor="LightGray">
                                <Label Text="Item 1" />
                                <Label Text="Item 2" />
                                <Label Text="Item 3" />
                                <Label Text="Item 4" />
                                <Label Text="Item 5" />
                            </VerticalStackLayout>
                        </mct:Expander.Content>
                    </mct:Expander>
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </VerticalStackLayout>
    </ScrollView>

1. Checkout this repository
2. Open the solution
3. Run it on iOS
4. Expand some headers until they don't fit the screen anymore
5. Try to scroll

On iOS:
![Simulator Screen Shot - iPhone 12 mini - 2022-12-08 at 14 42 08](https://user-images.githubusercontent.com/62621512/206449264-a61c4208-4940-4d8b-b9d7-83e9140ed481.png)

On Android:
![Screenshot_20221208-144322](https://user-images.githubusercontent.com/62621512/206449530-ce5ca1ef-5fcb-4f8e-824a-176af4d06fb0.png)

### Link to public reproduction project repository

https://github.com/andreeabuzuriu11/MauiSampleExpander

### Environment

```markdown
- .NET MAUI CommunityToolkit: Version 2.0.0
- OS: Mac OS 12.6
- .NET MAUI: 6.0
```

### Anything else?

Noticed that if I turn the phone on landscape mode, the scroll works on iOS.

**Comment by VladislavAntonyuk** [comment] 2022-12-18 13:47
The problem is with StackLayout/ScrollView which doesn't update the size. If we have more items ScrollView works:
https://user-images.githubusercontent.com/33021114/208301731-63601bd5-8548-4631-8373-7e6fac3bbeb2.mov

@brminnick should we fix it on our side by asking ScrollView to recalculate children's height?

**Comment by VladislavAntonyuk** [comment] 2022-12-18 13:47
https://user-images.githubusercontent.com/33021114/208301845-3180549c-f9de-4196-b8f0-2ed522f2e87f.mov

**Comment by VladislavAntonyuk** [comment] 2023-01-06 22:41
I was able to reproduce the issue with the scrollView:
MainPage.xaml
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="test816.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            BindableLayout.ItemsSource="{Binding Items}">
            <BindableLayout.ItemTemplate>
                <DataTemplate>
                    <VerticalStackLayout>
                        <Label Text="{Binding Label}"/>
                        <Button Clicked="OnCounterClicked" Text="change size"/>
                    </VerticalStackLayout>
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </VerticalStackLayout>
</ScrollView>

</ContentPage>
```

MainPage.xaml.cs
```csharp
using System.Collections.ObjectModel;

namespace test816;

public partial class MainPage : ContentPage
{
	public ObservableCollection<Item> Items { get; set; } = new();
	public MainPage()
	{
		InitializeComponent();
		Items.Add(new() { Label = "1" });
		Items.Add(new() { Label = "2" });
		Items.Add(new() { Label = "3" });
		Items.Add(new() { Label = "4" });
		Items.Add(new() { Label = "5" });
		Items.Add(new() { Label = "6" });
		Items.Add(new() { Label = "7" });
		Items.Add(new() { Label = "8" });
		BindingContext = this;
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		((sender as Button).Parent as VerticalStackLayout).HeightRequest = 200;
	}
}

public class Item
{
	public string Label { get; set; }
}
```

@jfversluis can we move this issue to .NET MAUI repo?

**Comment by VladislavAntonyuk** [comment] 2023-01-13 12:23
@andreeabuzuriu11 Thank you for your effort in creating the issue. We investigated and found it is reproduced with any control and related to ScrollView invalid measument during content size changes. I am closing the issue and ask to recreate it in .NET MAUI repo. Thank you!

**Closed by VladislavAntonyuk** 2023-01-13 12:23 UTC
Labels: bug
