### ISSUE TITLE
[BUG] Map not responding to span (zoom) requests in Windows

### ISSUE THREAD

**Issue by maxcheatham** [CommunityToolkit/Maui#1686] opened 2024-02-09 22:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

The MoveToRegion command of the Map changes the location, but does not change the span or zoom of the map in Windows. IsZoomEnabled is true.

### Expected Behavior

The map should change its zoom/span to the requested parameters.
The Android map is behaving correctly. The map is changing its zoom/span to the requested parameters.

### Steps To Reproduce

1. Open and run the project from the repository
2. Add your keys to AndroidManifest.xml (to verify that it works on Android) and MauiProgram.cs
3. Click Move 1, then Move 2, etc. and observe that the span is not changing, while the location is.
4. Also note that the Add Circle command does not seem to work on Windows.

### Link to public reproduction project repository

https://github.com/bluedot/TestMap2

### Environment

```markdown
- .NET MAUI CommunityToolkit: 2.0.0
- OS: Windows 11
- .NET MAUI: 8.0.3
```

### Anything else?

Hopefully, everything should be in the repository.
```[tasklist]
### Tasks
```

**Comment by maxcheatham** [comment] 2024-02-10 05:28
Removed the keys, so you'll have to add in your own in the two files MauiProgram.cs and AndroidManifest.xml.

**Comment by ckrutsinger** [comment] 2024-02-13 00:50
I can see that in the map handler implementation, the MapSpan is used to set the center but not the width and height of the map view. See https://[raw.githubusercontent.com/CommunityToolkit/Maui/main/src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs](https://raw.githubusercontent.com/CommunityToolkit/Maui/main/src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs)

``` 
	public static new void MapMoveToRegion(IMapHandler handler, IMap map, object? arg)
	{
		var newRegion = arg as MapSpan;
		if (newRegion == null)
		{
			return;
		}

		if (handler is MapHandlerWindows mapHandler)
		{
			mapHandler.regionToGo = newRegion;
		}

		CallJSMethod(handler.PlatformView, $"setRegion({newRegion.Center.Latitude.ToString(CultureInfo.InvariantCulture)},{newRegion.Center.Longitude.ToString(CultureInfo.InvariantCulture)});");
	}
```

[https://learn.microsoft.com/en-us/bingmaps/v8-web-control/map-control-concepts/map/change-the-map-view](https://learn.microsoft.com/en-us/bingmaps/v8-web-control/map-control-concepts/map/change-the-map-view)
shows how to set the entire rectangle.

**Comment by Brosten** [comment] 2024-02-13 07:20
+1
(Also, I didn't get the ItemSource + DataTemplate way of binding Pins to work under Windows, but that's a different bug)

**Comment by bijington** [comment] 2024-03-05 17:52
> Is this something that will be addressed? 

Would you be willing to contribute the fix via a PR?

**Comment by ckrutsinger** [comment] 2024-03-05 18:11
@bijington I don't know how to fix it.

**Comment by bijington** [comment] 2024-03-05 18:53
> @bijington I don't know how to fix it.

Oh sorry I read this comment (https://github.com/CommunityToolkit/Maui/issues/1686#issuecomment-1939939029) and assumed it meant you had an idea where the issue is

**Comment by TFreudi1** [comment] 2024-07-10 10:27
Same here, zomm did'nt work. Is it solved or planned to solve ?

**Comment by mikelor** [comment] 2024-07-22 15:30
@ckrutsinger do you have a simple example that demonstrates this?

The CommunityToolkit.Samples application works for me, but I'm not sure if that's what you are trying to do.

```
	void Button_OnClicked(object? sender, EventArgs e)
	{
		BasicMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Location(50, 6), Distance.FromKilometers(1)));
	}
```

**Comment by TFreudi1** [comment] 2024-07-22 16:48
Try Distance.FromMeters(100)It don't zoom, looks always like 1 km.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: mike lorengo ***@***.***> Datum: 22.07.24  17:31  (GMT+01:00) An: CommunityToolkit/Maui ***@***.***> Cc: TFreudi1 ***@***.***>, Comment ***@***.***> Betreff: Re: [CommunityToolkit/Maui] [BUG] Map not responding to span (zoom) requests in Windows (Issue #1686) 
@ckrutsinger do you have a simple example that demonstrates this?
The CommunityToolkit.Samples application works for me, but I'm not sure if that's what you are trying to do.
	void Button_OnClicked(object? sender, EventArgs e)
	{
		BasicMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Location(50, 6), Distance.FromKilometers(1)));
	}

**Comment by ksoftllc** [comment] 2024-07-22 17:00
@mikelor It does move to the new center, but does not set width and height requested. Clear from the source code snippet provided above.

**Comment by mikelor** [comment] 2024-07-23 20:51
Yep. I was able to duplicate it. 

I took a look and @ckrutsinger is correct. The handler code is only using the center to set the region.
I modified the code so that it looks like this
```
CallJSMethod(handler.PlatformView, $"setRegion({newRegion.Center.Latitude.ToString(CultureInfo.InvariantCulture)},{newRegion.Center.Longitude.ToString(CultureInfo.InvariantCulture)},{newRegion.LatitudeDegrees.ToString(CultureInfo.InvariantCulture)},{newRegion.LongitudeDegrees.ToString(CultureInfo.InvariantCulture)});");
```
and modified the setRegion script as follows

```
function setRegion(latitude, longitude, latitudeDegrees, longitudeDegrees)
{
	map.setView({bounds: new Microsoft.Maps.LocationRect(new Microsoft.Maps.Location(latitude, longitude), latitudeDegrees, longitudeDegrees) });
}
```

That seems to fix it, as shown in the video below.

https://github.com/user-attachments/assets/cbaa43cb-e78a-4691-a2a2-faf1f5e3a847

**Comment by mikelor** [comment] 2024-07-23 20:57
I'm going to test a couple of map projects I have with the new code.

**Comment by losh99** [comment] 2024-10-22 11:44
Any update on implementing this fix and when it will be released?

**Comment by mikelor** [comment] 2024-10-30 14:40
You could implement the code fix listed above. I'm traveling at the moment, so I won't be able to submit a pull request until next week.

**Comment by mikelor** [comment] 2024-11-06 20:19
Hey @bijington, I implemented a fix for this. Let me know if I need to do anything else.

**Closed** 2024-11-07 06:17 UTC
Labels: bug, area/views

**Comment by mikelor** [comment] 2024-11-08 17:14
hey @losh99 this is now in [release 2.04](https://github.com/CommunityToolkit/Maui/releases/tag/2.0.4-maps) of CommunityToolkit.Maui.Maps

**Comment by losh99** [comment] 2024-11-08 17:32
Thanks @mikelor really appreciated!
