### ISSUE TITLE
[BUG] Popup CanBeDismissedByTappingOutsideOfPopup = false not modal and doesn't prevent from interacting with Parent Page

### ISSUE THREAD

**Issue by FedePella94** [CommunityToolkit/Maui#1478] opened 2023-10-26 17:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

If I call a popup where I set the CanBeDismissedByTappingOutsideOfPopup = false; the result is this and it's not modal, I can interact with the page.
![image](https://github.com/CommunityToolkit/Maui/assets/53230921/81bf9db7-a614-4c9f-882a-579c29aa4332)
But if I set the parameters as true, the page gets a layer that prevents the interaction and graphically sets a difference between the popup and the application.
![image](https://github.com/CommunityToolkit/Maui/assets/53230921/53b460fb-f62c-4d43-bd19-3ee363b5edf6)

### Expected Behavior

Have the same behavior as between the two value of the parameter with the difference to not being able to be closed on tapping outside the popup.

### Steps To Reproduce

1. Create a MAUI project with the creation of a maui community toolkit popup. 
2. Call a Popup with CanBeDismissedByTappingOutsideOfPopup = false; an one with CanBeDismissedByTappingOutsideOfPopup = true;

### Link to public reproduction project repository

[Link to Repository](https://github.com/FedePella94/BUG-Popup-MAUI-Community-Toolkit)

### Environment

```markdown
- .NET MAUI CommunityToolkit: 6.0
- OS: Windows 10.0.19041.0
- .NET MAUI: 7.0
```

**Comment by FedePella94** [comment] 2023-10-27 11:01
> Hi @FedePella94. We have added the "needs reproduction" label to this issue, which indicates that we cannot take further action. This issue will be closed automatically in 5 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

Hi @pictos, I added the repository as a simple popup. The problem is with the MenuBarItem that is still working and About the background.
Thanks!

**Comment by cat0363** [comment] 2023-10-30 01:53
On Windows, even if MenuBarItem's IsEnabled was intentionally set to False, it did not become inoperable.
It seems that the issue below is probably related.

https://github.com/dotnet/maui/issues/11602

It is unclear whether this issue will be resolved if the above is resolved.

**Comment by FedePella94** [comment] 2023-10-30 09:53
@cat0363 Ok, I saw that the MenuBarItem seems like living a proper life, but in the previous version of the Toolkit (5.3.0) it was working, there was another bug like the closing of the popup when the window was maximazed and then not, but at least the background was opaque. I'm using a workaround for it but it's a bit complex because of the nature of the software i'm working on it. 
Happy to contribute even in little!

**Comment by cat0363** [comment] 2023-10-30 23:39
@FedePella94 , Thank you for information.
I have confirmed that version 5.3.0 is working as intended. 
I also confirmed that the overlay is no longer present in version 6.0.0.

**Comment by cat0363** [comment] 2023-10-31 01:16
In version 5.3.0, Popup seems to have been implemented using Flyout.
From version 6.0.0, the implementation has been changed to use the following Popup.
With this change, you can no longer catch the Popup's Closing event, and you can no 
longer cancel the Popup's closing as before. 

    Microsoft.UI.Xaml.Controls.Primitives.Popup

Previously, it seems that if the CanBeDismissedByTappingOutsideOfPopup property was false, 
the closing of the Flyout was intentionally canceled in the Flyout's Closing event.
So previously LightDismissOverlayMode was On and IsLightDismissEnabled was true.

I wish I could disable the MenuBarItem, catch the Closing event, or ignore taps on the overlay part. . .

**Comment by cat0363** [comment] 2023-10-31 03:19
As far as I checked, this problem did not resolve itself even if the MenuBarItem issue was resolved.
This is a workaround, but it can be avoided by implementing the following.
The MenuBarItem defect fix has not been backported to .NET 7, so you will need to reimplement the Handler.

    public class CustomMenuBarItemHandler : MenuBarItemHandler
    {
        protected override Microsoft.UI.Xaml.Controls.MenuBarItem CreatePlatformElement()
        {
            Mapper.Add(nameof(MenuBarItem.IsEnabled), MapIsEnabled);
            return base.CreatePlatformElement();
        }
    }

Temporarily save the IsEnabled state of MenuBarItem before opening the Popup, display the Popup with IsEanbled set to false, and then restore the temporarily saved IsEnabled state after closing the Popup.

    Dictionary<MenuBarItem, bool> mapMenuBarEnabled = new Dictionary<MenuBarItem, bool>();
    foreach(MenuBarItem mbi in Shell.Current.CurrentPage.MenuBarItems)
    {
        mapMenuBarEnabled.Add(mbi, mbi.IsEnabled);
        mbi.IsEnabled = false;
    }

    await ShowPopup(popup);

    foreach (MenuBarItem mbi in Shell.Current.CurrentPage.MenuBarItems)
    {
        mbi.IsEnabled = mapMenuBarEnabled[mbi];
    }
    mapMenuBarEnabled.Clear();

https://github.com/CommunityToolkit/Maui/assets/125236133/fcca8619-7d5e-4682-a330-77549a62d724

However, no overlay appears on the Popup background.

**Comment by cat0363** [comment] 2023-10-31 03:35
Assuming that the MenuBarItem handler has been reimplemented, the problem can be solved by implementing the following, but this is not a good implementation.

[src\CommunityToolkit.Maui\Views\Popup\PopupExtensions.windows.cs]

    static void PlatformShowPopup(Popup popup, IMauiContext mauiContext)
    {
        var window = mauiContext.GetPlatformWindow().GetWindow() ?? throw new NullReferenceException("Window is null.");
        popup.Parent = ((Page)window.Content).GetCurrentPage();
        Dictionary<MenuBarItem, bool> mapMenuBarEnabled = new Dictionary<MenuBarItem, bool>();
        popup.Opened += (o, e) =>
        {
            if (Shell.Current.CurrentPage is Page page)
            {
                foreach (MenuBarItem mbi in page.MenuBarItems)
                {
                    mapMenuBarEnabled.Add(mbi, mbi.IsEnabled);
                    mbi.IsEnabled = false;
                }
            }
        };
        popup.Closed += (o, e) =>
        {
            if (Shell.Current.CurrentPage is Page page)
            {
                foreach (MenuBarItem mbi in page.MenuBarItems)
                {
                    mbi.IsEnabled = mapMenuBarEnabled[mbi]; ;
                }
                mapMenuBarEnabled.Clear();
            }
        };
        var platform = popup.ToHandler(mauiContext);
        platform?.Invoke(nameof(IPopup.OnOpened));
    }

**Comment by cat0363** [comment] 2023-10-31 08:45
I was able to resolve the issue by turning off LightDismissOverlayMode and displaying my own overlay.
No tricks like manipulating MenuBarItem are required. 
I would like to refactor the code I created and create a PR tomorrow.

Below is the verification video.

https://github.com/CommunityToolkit/Maui/assets/125236133/8913e070-c035-4b18-bfe8-d2870f7860d2

Can you leave this matter to me?

**Comment by FedePella94** [comment] 2023-10-31 09:24
@cat0363 your solutions are great, and for now I'll try the workaround you wrote. Feel free to do whatever you believe is to to and if you have any questions just ask!
I do have one question: where should i put the workaround code? 
Thank you!

**Comment by cat0363** [comment] 2023-10-31 09:45
@FedePella94 , I got home and left my desk, so I'll teach you tomorrow.
If you can wait for a solution, it's much better than a workaround, so it's better to wait.

**Comment by cat0363** [comment] 2023-11-01 03:03
@FedePella94 , The method to apply the workaround is described below.

1. Please create the following class in the location below.

[BUG-Popup-MAUI-Community-Toolkit\BUG-Popup-MAUI-Community-Toolkit\Platforms\Windows\CustomMenuBarItemHandler.cs]

    using Microsoft.Maui.Handlers;
    namespace BUG_Popup_MAUI_Community_Toolkit.Platforms.Windows;
    public class CustomMenuBarItemHandler : MenuBarItemHandler
    {
        protected override Microsoft.UI.Xaml.Controls.MenuBarItem CreatePlatformElement()
        {
            Mapper.Add(nameof(MenuBarItem.IsEnabled), MapIsEnabled);
            return base.CreatePlatformElement();
        }
    }

2. Please modify the method in the file below.

[BUG-Popup-MAUI-Community-Toolkit\BUG-Popup-MAUI-Community-Toolkit\Helpers\PopupManager.cs]

    public async Task ShowPopup(Popup popup) //implementare la gestione dell'errore
    {
        try
        {
            Page page = new();
            if (Application.Current?.MainPage?.Navigation?.ModalStack?.Count == 1)
            {
                page = Application.Current?.MainPage?.Navigation?.ModalStack[0] ?? throw new NullReferenceException();
            }
            else
            {
                page = Application.Current?.MainPage ?? throw new NullReferenceException();
            }
				
            Dictionary<MenuBarItem, bool> mapMenuBarEnabled = new Dictionary<MenuBarItem, bool>();
            foreach(MenuBarItem mbi in Shell.Current.CurrentPage.MenuBarItems)
            {
                mapMenuBarEnabled.Add(mbi, mbi.IsEnabled);
                mbi.IsEnabled = false;
            }

            await page.ShowPopupAsync(popup);

            foreach (MenuBarItem mbi in Shell.Current.CurrentPage.MenuBarItems)
            {
                mbi.IsEnabled = mapMenuBarEnabled[mbi];
            }
            mapMenuBarEnabled.Clear();
        }
        catch (Exception)
        {
            throw new Exception("Errore nella creazione del popup");
        }            
    }

3. Please modify the file below as follows.

[src\BUG-Popup-MAUI-Community-Toolkit\BUG-Popup-MAUI-Community-Toolkit\MauiProgram.cs]

    using Microsoft.Extensions.Logging;
    using CommunityToolkit.Maui;
    using Microsoft.Maui.Handlers;
    #if WINDOWS
    using BUG_Popup_MAUI_Community_Toolkit.Platforms.Windows;
    #endif

    namespace BUG_Popup_MAUI_Community_Toolkit;

    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
            .UseMauiApp<App>()
            .UseMauiCommunityToolkit()
            .ConfigureMauiHandlers(handlers =>
            {
    #if WINDOWS
                handlers.AddHandler<MenuBarItem, CustomMenuBarItemHandler>();
    #endif
            })
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });

    #if DEBUG
            builder.Logging.AddDebug();
    #endif

            return builder.Build();
        }
    }

**Closed** 2023-11-02 22:26 UTC
Labels: bug, unverified
